// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChurnEventsColumns holds the columns for the "churn_events" table.
	ChurnEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "runner_name", Type: field.TypeString},
		{Name: "set_name", Type: field.TypeString, Default: ""},
		{Name: "kind", Type: field.TypeString},
		{Name: "ts", Type: field.TypeInt64},
	}
	// ChurnEventsTable holds the schema information for the "churn_events" table.
	ChurnEventsTable = &schema.Table{
		Name:       "churn_events",
		Columns:    ChurnEventsColumns,
		PrimaryKey: []*schema.Column{ChurnEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "churnevent_runner_name_kind",
				Unique:  true,
				Columns: []*schema.Column{ChurnEventsColumns[1], ChurnEventsColumns[3]},
			},
			{
				Name:    "churnevent_set_name_ts",
				Unique:  false,
				Columns: []*schema.Column{ChurnEventsColumns[2], ChurnEventsColumns[4]},
			},
			{
				Name:    "churnevent_ts",
				Unique:  false,
				Columns: []*schema.Column{ChurnEventsColumns[4]},
			},
		},
	}
	// JobObservationsColumns holds the columns for the "job_observations" table.
	JobObservationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "runner_name", Type: field.TypeString},
		{Name: "set_name", Type: field.TypeString, Default: ""},
		{Name: "repository", Type: field.TypeString, Default: ""},
		{Name: "workflow", Type: field.TypeString, Default: ""},
		{Name: "job_name", Type: field.TypeString, Default: ""},
		{Name: "run_id", Type: field.TypeInt64, Default: 0},
		{Name: "started_at", Type: field.TypeInt64},
		{Name: "finished_at", Type: field.TypeInt64, Default: 0},
		{Name: "succeeded", Type: field.TypeBool, Default: false},
		{Name: "cpu_seconds", Type: field.TypeFloat64, Default: 0},
		{Name: "mem_byte_seconds", Type: field.TypeFloat64, Default: 0},
	}
	// JobObservationsTable holds the schema information for the "job_observations" table.
	JobObservationsTable = &schema.Table{
		Name:       "job_observations",
		Columns:    JobObservationsColumns,
		PrimaryKey: []*schema.Column{JobObservationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "jobobservation_runner_name_run_id_job_name",
				Unique:  true,
				Columns: []*schema.Column{JobObservationsColumns[1], JobObservationsColumns[6], JobObservationsColumns[5]},
			},
			{
				Name:    "jobobservation_set_name_started_at",
				Unique:  false,
				Columns: []*schema.Column{JobObservationsColumns[2], JobObservationsColumns[7]},
			},
			{
				Name:    "jobobservation_repository_started_at",
				Unique:  false,
				Columns: []*schema.Column{JobObservationsColumns[3], JobObservationsColumns[7]},
			},
			{
				Name:    "jobobservation_finished_at",
				Unique:  false,
				Columns: []*schema.Column{JobObservationsColumns[8]},
			},
		},
	}
	// PhaseTransitionsColumns holds the columns for the "phase_transitions" table.
	PhaseTransitionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "runner_name", Type: field.TypeString},
		{Name: "set_name", Type: field.TypeString, Default: ""},
		{Name: "phase", Type: field.TypeString},
		{Name: "started_at", Type: field.TypeInt64},
		{Name: "ended_at", Type: field.TypeInt64, Default: 0},
	}
	// PhaseTransitionsTable holds the schema information for the "phase_transitions" table.
	PhaseTransitionsTable = &schema.Table{
		Name:       "phase_transitions",
		Columns:    PhaseTransitionsColumns,
		PrimaryKey: []*schema.Column{PhaseTransitionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "phasetransition_runner_name_phase_started_at",
				Unique:  true,
				Columns: []*schema.Column{PhaseTransitionsColumns[1], PhaseTransitionsColumns[3], PhaseTransitionsColumns[4]},
			},
			{
				Name:    "phasetransition_runner_name_started_at",
				Unique:  false,
				Columns: []*schema.Column{PhaseTransitionsColumns[1], PhaseTransitionsColumns[4]},
			},
			{
				Name:    "phasetransition_started_at",
				Unique:  false,
				Columns: []*schema.Column{PhaseTransitionsColumns[4]},
			},
		},
	}
	// SamplesColumns holds the columns for the "samples" table.
	SamplesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ts", Type: field.TypeInt64},
		{Name: "scope", Type: field.TypeString},
		{Name: "scope_id", Type: field.TypeString, Default: ""},
		{Name: "tier", Type: field.TypeString},
		{Name: "metric", Type: field.TypeString},
		{Name: "value", Type: field.TypeFloat64},
	}
	// SamplesTable holds the schema information for the "samples" table.
	SamplesTable = &schema.Table{
		Name:       "samples",
		Columns:    SamplesColumns,
		PrimaryKey: []*schema.Column{SamplesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sample_scope_scope_id_metric_tier_ts",
				Unique:  true,
				Columns: []*schema.Column{SamplesColumns[2], SamplesColumns[3], SamplesColumns[5], SamplesColumns[4], SamplesColumns[1]},
			},
			{
				Name:    "sample_tier_ts",
				Unique:  false,
				Columns: []*schema.Column{SamplesColumns[4], SamplesColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChurnEventsTable,
		JobObservationsTable,
		PhaseTransitionsTable,
		SamplesTable,
	}
)

func init() {
}
