// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/churnevent"
	"arc-ui/internal/store/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChurnEventUpdate is the builder for updating ChurnEvent entities.
type ChurnEventUpdate struct {
	config
	hooks    []Hook
	mutation *ChurnEventMutation
}

// Where appends a list predicates to the ChurnEventUpdate builder.
func (_u *ChurnEventUpdate) Where(ps ...predicate.ChurnEvent) *ChurnEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRunnerName sets the "runner_name" field.
func (_u *ChurnEventUpdate) SetRunnerName(v string) *ChurnEventUpdate {
	_u.mutation.SetRunnerName(v)
	return _u
}

// SetNillableRunnerName sets the "runner_name" field if the given value is not nil.
func (_u *ChurnEventUpdate) SetNillableRunnerName(v *string) *ChurnEventUpdate {
	if v != nil {
		_u.SetRunnerName(*v)
	}
	return _u
}

// SetSetName sets the "set_name" field.
func (_u *ChurnEventUpdate) SetSetName(v string) *ChurnEventUpdate {
	_u.mutation.SetSetName(v)
	return _u
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_u *ChurnEventUpdate) SetNillableSetName(v *string) *ChurnEventUpdate {
	if v != nil {
		_u.SetSetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ChurnEventUpdate) SetKind(v string) *ChurnEventUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ChurnEventUpdate) SetNillableKind(v *string) *ChurnEventUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTs sets the "ts" field.
func (_u *ChurnEventUpdate) SetTs(v int64) *ChurnEventUpdate {
	_u.mutation.ResetTs()
	_u.mutation.SetTs(v)
	return _u
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (_u *ChurnEventUpdate) SetNillableTs(v *int64) *ChurnEventUpdate {
	if v != nil {
		_u.SetTs(*v)
	}
	return _u
}

// AddTs adds value to the "ts" field.
func (_u *ChurnEventUpdate) AddTs(v int64) *ChurnEventUpdate {
	_u.mutation.AddTs(v)
	return _u
}

// Mutation returns the ChurnEventMutation object of the builder.
func (_u *ChurnEventUpdate) Mutation() *ChurnEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChurnEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChurnEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChurnEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChurnEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ChurnEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(churnevent.Table, churnevent.Columns, sqlgraph.NewFieldSpec(churnevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunnerName(); ok {
		_spec.SetField(churnevent.FieldRunnerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SetName(); ok {
		_spec.SetField(churnevent.FieldSetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(churnevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ts(); ok {
		_spec.SetField(churnevent.FieldTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTs(); ok {
		_spec.AddField(churnevent.FieldTs, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{churnevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChurnEventUpdateOne is the builder for updating a single ChurnEvent entity.
type ChurnEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChurnEventMutation
}

// SetRunnerName sets the "runner_name" field.
func (_u *ChurnEventUpdateOne) SetRunnerName(v string) *ChurnEventUpdateOne {
	_u.mutation.SetRunnerName(v)
	return _u
}

// SetNillableRunnerName sets the "runner_name" field if the given value is not nil.
func (_u *ChurnEventUpdateOne) SetNillableRunnerName(v *string) *ChurnEventUpdateOne {
	if v != nil {
		_u.SetRunnerName(*v)
	}
	return _u
}

// SetSetName sets the "set_name" field.
func (_u *ChurnEventUpdateOne) SetSetName(v string) *ChurnEventUpdateOne {
	_u.mutation.SetSetName(v)
	return _u
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_u *ChurnEventUpdateOne) SetNillableSetName(v *string) *ChurnEventUpdateOne {
	if v != nil {
		_u.SetSetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ChurnEventUpdateOne) SetKind(v string) *ChurnEventUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ChurnEventUpdateOne) SetNillableKind(v *string) *ChurnEventUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTs sets the "ts" field.
func (_u *ChurnEventUpdateOne) SetTs(v int64) *ChurnEventUpdateOne {
	_u.mutation.ResetTs()
	_u.mutation.SetTs(v)
	return _u
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (_u *ChurnEventUpdateOne) SetNillableTs(v *int64) *ChurnEventUpdateOne {
	if v != nil {
		_u.SetTs(*v)
	}
	return _u
}

// AddTs adds value to the "ts" field.
func (_u *ChurnEventUpdateOne) AddTs(v int64) *ChurnEventUpdateOne {
	_u.mutation.AddTs(v)
	return _u
}

// Mutation returns the ChurnEventMutation object of the builder.
func (_u *ChurnEventUpdateOne) Mutation() *ChurnEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChurnEventUpdate builder.
func (_u *ChurnEventUpdateOne) Where(ps ...predicate.ChurnEvent) *ChurnEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChurnEventUpdateOne) Select(field string, fields ...string) *ChurnEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChurnEvent entity.
func (_u *ChurnEventUpdateOne) Save(ctx context.Context) (*ChurnEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChurnEventUpdateOne) SaveX(ctx context.Context) *ChurnEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChurnEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChurnEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ChurnEventUpdateOne) sqlSave(ctx context.Context) (_node *ChurnEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(churnevent.Table, churnevent.Columns, sqlgraph.NewFieldSpec(churnevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChurnEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, churnevent.FieldID)
		for _, f := range fields {
			if !churnevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != churnevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunnerName(); ok {
		_spec.SetField(churnevent.FieldRunnerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SetName(); ok {
		_spec.SetField(churnevent.FieldSetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(churnevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ts(); ok {
		_spec.SetField(churnevent.FieldTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTs(); ok {
		_spec.AddField(churnevent.FieldTs, field.TypeInt64, value)
	}
	_node = &ChurnEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{churnevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
