// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/churnevent"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ChurnEvent is the model entity for the ChurnEvent schema.
type ChurnEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RunnerName holds the value of the "runner_name" field.
	RunnerName string `json:"runner_name,omitempty"`
	// SetName holds the value of the "set_name" field.
	SetName string `json:"set_name,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Ts holds the value of the "ts" field.
	Ts           int64 `json:"ts,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChurnEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case churnevent.FieldID, churnevent.FieldTs:
			values[i] = new(sql.NullInt64)
		case churnevent.FieldRunnerName, churnevent.FieldSetName, churnevent.FieldKind:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChurnEvent fields.
func (_m *ChurnEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case churnevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case churnevent.FieldRunnerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field runner_name", values[i])
			} else if value.Valid {
				_m.RunnerName = value.String
			}
		case churnevent.FieldSetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field set_name", values[i])
			} else if value.Valid {
				_m.SetName = value.String
			}
		case churnevent.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case churnevent.FieldTs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ts", values[i])
			} else if value.Valid {
				_m.Ts = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChurnEvent.
// This includes values selected through modifiers, order, etc.
func (_m *ChurnEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ChurnEvent.
// Note that you need to call ChurnEvent.Unwrap() before calling this method if this ChurnEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChurnEvent) Update() *ChurnEventUpdateOne {
	return NewChurnEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChurnEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChurnEvent) Unwrap() *ChurnEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChurnEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChurnEvent) String() string {
	var builder strings.Builder
	builder.WriteString("ChurnEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("runner_name=")
	builder.WriteString(_m.RunnerName)
	builder.WriteString(", ")
	builder.WriteString("set_name=")
	builder.WriteString(_m.SetName)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("ts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ts))
	builder.WriteByte(')')
	return builder.String()
}

// ChurnEvents is a parsable slice of ChurnEvent.
type ChurnEvents []*ChurnEvent
