// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/churnevent"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChurnEventCreate is the builder for creating a ChurnEvent entity.
type ChurnEventCreate struct {
	config
	mutation *ChurnEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRunnerName sets the "runner_name" field.
func (_c *ChurnEventCreate) SetRunnerName(v string) *ChurnEventCreate {
	_c.mutation.SetRunnerName(v)
	return _c
}

// SetSetName sets the "set_name" field.
func (_c *ChurnEventCreate) SetSetName(v string) *ChurnEventCreate {
	_c.mutation.SetSetName(v)
	return _c
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_c *ChurnEventCreate) SetNillableSetName(v *string) *ChurnEventCreate {
	if v != nil {
		_c.SetSetName(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *ChurnEventCreate) SetKind(v string) *ChurnEventCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetTs sets the "ts" field.
func (_c *ChurnEventCreate) SetTs(v int64) *ChurnEventCreate {
	_c.mutation.SetTs(v)
	return _c
}

// Mutation returns the ChurnEventMutation object of the builder.
func (_c *ChurnEventCreate) Mutation() *ChurnEventMutation {
	return _c.mutation
}

// Save creates the ChurnEvent in the database.
func (_c *ChurnEventCreate) Save(ctx context.Context) (*ChurnEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChurnEventCreate) SaveX(ctx context.Context) *ChurnEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChurnEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChurnEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChurnEventCreate) defaults() {
	if _, ok := _c.mutation.SetName(); !ok {
		v := churnevent.DefaultSetName
		_c.mutation.SetSetName(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChurnEventCreate) check() error {
	if _, ok := _c.mutation.RunnerName(); !ok {
		return &ValidationError{Name: "runner_name", err: errors.New(`ent: missing required field "ChurnEvent.runner_name"`)}
	}
	if _, ok := _c.mutation.SetName(); !ok {
		return &ValidationError{Name: "set_name", err: errors.New(`ent: missing required field "ChurnEvent.set_name"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "ChurnEvent.kind"`)}
	}
	if _, ok := _c.mutation.Ts(); !ok {
		return &ValidationError{Name: "ts", err: errors.New(`ent: missing required field "ChurnEvent.ts"`)}
	}
	return nil
}

func (_c *ChurnEventCreate) sqlSave(ctx context.Context) (*ChurnEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChurnEventCreate) createSpec() (*ChurnEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ChurnEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(churnevent.Table, sqlgraph.NewFieldSpec(churnevent.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RunnerName(); ok {
		_spec.SetField(churnevent.FieldRunnerName, field.TypeString, value)
		_node.RunnerName = value
	}
	if value, ok := _c.mutation.SetName(); ok {
		_spec.SetField(churnevent.FieldSetName, field.TypeString, value)
		_node.SetName = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(churnevent.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Ts(); ok {
		_spec.SetField(churnevent.FieldTs, field.TypeInt64, value)
		_node.Ts = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChurnEvent.Create().
//		SetRunnerName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChurnEventUpsert) {
//			SetRunnerName(v+v).
//		}).
//		Exec(ctx)
func (_c *ChurnEventCreate) OnConflict(opts ...sql.ConflictOption) *ChurnEventUpsertOne {
	_c.conflict = opts
	return &ChurnEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChurnEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChurnEventCreate) OnConflictColumns(columns ...string) *ChurnEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChurnEventUpsertOne{
		create: _c,
	}
}

type (
	// ChurnEventUpsertOne is the builder for "upsert"-ing
	//  one ChurnEvent node.
	ChurnEventUpsertOne struct {
		create *ChurnEventCreate
	}

	// ChurnEventUpsert is the "OnConflict" setter.
	ChurnEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetRunnerName sets the "runner_name" field.
func (u *ChurnEventUpsert) SetRunnerName(v string) *ChurnEventUpsert {
	u.Set(churnevent.FieldRunnerName, v)
	return u
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *ChurnEventUpsert) UpdateRunnerName() *ChurnEventUpsert {
	u.SetExcluded(churnevent.FieldRunnerName)
	return u
}

// SetSetName sets the "set_name" field.
func (u *ChurnEventUpsert) SetSetName(v string) *ChurnEventUpsert {
	u.Set(churnevent.FieldSetName, v)
	return u
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *ChurnEventUpsert) UpdateSetName() *ChurnEventUpsert {
	u.SetExcluded(churnevent.FieldSetName)
	return u
}

// SetKind sets the "kind" field.
func (u *ChurnEventUpsert) SetKind(v string) *ChurnEventUpsert {
	u.Set(churnevent.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ChurnEventUpsert) UpdateKind() *ChurnEventUpsert {
	u.SetExcluded(churnevent.FieldKind)
	return u
}

// SetTs sets the "ts" field.
func (u *ChurnEventUpsert) SetTs(v int64) *ChurnEventUpsert {
	u.Set(churnevent.FieldTs, v)
	return u
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *ChurnEventUpsert) UpdateTs() *ChurnEventUpsert {
	u.SetExcluded(churnevent.FieldTs)
	return u
}

// AddTs adds v to the "ts" field.
func (u *ChurnEventUpsert) AddTs(v int64) *ChurnEventUpsert {
	u.Add(churnevent.FieldTs, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChurnEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChurnEventUpsertOne) UpdateNewValues() *ChurnEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChurnEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChurnEventUpsertOne) Ignore() *ChurnEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChurnEventUpsertOne) DoNothing() *ChurnEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChurnEventCreate.OnConflict
// documentation for more info.
func (u *ChurnEventUpsertOne) Update(set func(*ChurnEventUpsert)) *ChurnEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChurnEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunnerName sets the "runner_name" field.
func (u *ChurnEventUpsertOne) SetRunnerName(v string) *ChurnEventUpsertOne {
	return u.Update(func(s *ChurnEventUpsert) {
		s.SetRunnerName(v)
	})
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *ChurnEventUpsertOne) UpdateRunnerName() *ChurnEventUpsertOne {
	return u.Update(func(s *ChurnEventUpsert) {
		s.UpdateRunnerName()
	})
}

// SetSetName sets the "set_name" field.
func (u *ChurnEventUpsertOne) SetSetName(v string) *ChurnEventUpsertOne {
	return u.Update(func(s *ChurnEventUpsert) {
		s.SetSetName(v)
	})
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *ChurnEventUpsertOne) UpdateSetName() *ChurnEventUpsertOne {
	return u.Update(func(s *ChurnEventUpsert) {
		s.UpdateSetName()
	})
}

// SetKind sets the "kind" field.
func (u *ChurnEventUpsertOne) SetKind(v string) *ChurnEventUpsertOne {
	return u.Update(func(s *ChurnEventUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ChurnEventUpsertOne) UpdateKind() *ChurnEventUpsertOne {
	return u.Update(func(s *ChurnEventUpsert) {
		s.UpdateKind()
	})
}

// SetTs sets the "ts" field.
func (u *ChurnEventUpsertOne) SetTs(v int64) *ChurnEventUpsertOne {
	return u.Update(func(s *ChurnEventUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *ChurnEventUpsertOne) AddTs(v int64) *ChurnEventUpsertOne {
	return u.Update(func(s *ChurnEventUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *ChurnEventUpsertOne) UpdateTs() *ChurnEventUpsertOne {
	return u.Update(func(s *ChurnEventUpsert) {
		s.UpdateTs()
	})
}

// Exec executes the query.
func (u *ChurnEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChurnEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChurnEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChurnEventUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChurnEventUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChurnEventCreateBulk is the builder for creating many ChurnEvent entities in bulk.
type ChurnEventCreateBulk struct {
	config
	err      error
	builders []*ChurnEventCreate
	conflict []sql.ConflictOption
}

// Save creates the ChurnEvent entities in the database.
func (_c *ChurnEventCreateBulk) Save(ctx context.Context) ([]*ChurnEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChurnEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChurnEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChurnEventCreateBulk) SaveX(ctx context.Context) []*ChurnEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChurnEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChurnEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChurnEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChurnEventUpsert) {
//			SetRunnerName(v+v).
//		}).
//		Exec(ctx)
func (_c *ChurnEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChurnEventUpsertBulk {
	_c.conflict = opts
	return &ChurnEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChurnEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChurnEventCreateBulk) OnConflictColumns(columns ...string) *ChurnEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChurnEventUpsertBulk{
		create: _c,
	}
}

// ChurnEventUpsertBulk is the builder for "upsert"-ing
// a bulk of ChurnEvent nodes.
type ChurnEventUpsertBulk struct {
	create *ChurnEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChurnEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChurnEventUpsertBulk) UpdateNewValues() *ChurnEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChurnEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChurnEventUpsertBulk) Ignore() *ChurnEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChurnEventUpsertBulk) DoNothing() *ChurnEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChurnEventCreateBulk.OnConflict
// documentation for more info.
func (u *ChurnEventUpsertBulk) Update(set func(*ChurnEventUpsert)) *ChurnEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChurnEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunnerName sets the "runner_name" field.
func (u *ChurnEventUpsertBulk) SetRunnerName(v string) *ChurnEventUpsertBulk {
	return u.Update(func(s *ChurnEventUpsert) {
		s.SetRunnerName(v)
	})
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *ChurnEventUpsertBulk) UpdateRunnerName() *ChurnEventUpsertBulk {
	return u.Update(func(s *ChurnEventUpsert) {
		s.UpdateRunnerName()
	})
}

// SetSetName sets the "set_name" field.
func (u *ChurnEventUpsertBulk) SetSetName(v string) *ChurnEventUpsertBulk {
	return u.Update(func(s *ChurnEventUpsert) {
		s.SetSetName(v)
	})
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *ChurnEventUpsertBulk) UpdateSetName() *ChurnEventUpsertBulk {
	return u.Update(func(s *ChurnEventUpsert) {
		s.UpdateSetName()
	})
}

// SetKind sets the "kind" field.
func (u *ChurnEventUpsertBulk) SetKind(v string) *ChurnEventUpsertBulk {
	return u.Update(func(s *ChurnEventUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ChurnEventUpsertBulk) UpdateKind() *ChurnEventUpsertBulk {
	return u.Update(func(s *ChurnEventUpsert) {
		s.UpdateKind()
	})
}

// SetTs sets the "ts" field.
func (u *ChurnEventUpsertBulk) SetTs(v int64) *ChurnEventUpsertBulk {
	return u.Update(func(s *ChurnEventUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *ChurnEventUpsertBulk) AddTs(v int64) *ChurnEventUpsertBulk {
	return u.Update(func(s *ChurnEventUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *ChurnEventUpsertBulk) UpdateTs() *ChurnEventUpsertBulk {
	return u.Update(func(s *ChurnEventUpsert) {
		s.UpdateTs()
	})
}

// Exec executes the query.
func (u *ChurnEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChurnEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChurnEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChurnEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
