// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"arc-ui/internal/store/ent/migrate"

	"arc-ui/internal/store/ent/churnevent"
	"arc-ui/internal/store/ent/jobobservation"
	"arc-ui/internal/store/ent/phasetransition"
	"arc-ui/internal/store/ent/runnerfailure"
	"arc-ui/internal/store/ent/sample"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ChurnEvent is the client for interacting with the ChurnEvent builders.
	ChurnEvent *ChurnEventClient
	// JobObservation is the client for interacting with the JobObservation builders.
	JobObservation *JobObservationClient
	// PhaseTransition is the client for interacting with the PhaseTransition builders.
	PhaseTransition *PhaseTransitionClient
	// RunnerFailure is the client for interacting with the RunnerFailure builders.
	RunnerFailure *RunnerFailureClient
	// Sample is the client for interacting with the Sample builders.
	Sample *SampleClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ChurnEvent = NewChurnEventClient(c.config)
	c.JobObservation = NewJobObservationClient(c.config)
	c.PhaseTransition = NewPhaseTransitionClient(c.config)
	c.RunnerFailure = NewRunnerFailureClient(c.config)
	c.Sample = NewSampleClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		ChurnEvent:      NewChurnEventClient(cfg),
		JobObservation:  NewJobObservationClient(cfg),
		PhaseTransition: NewPhaseTransitionClient(cfg),
		RunnerFailure:   NewRunnerFailureClient(cfg),
		Sample:          NewSampleClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		ChurnEvent:      NewChurnEventClient(cfg),
		JobObservation:  NewJobObservationClient(cfg),
		PhaseTransition: NewPhaseTransitionClient(cfg),
		RunnerFailure:   NewRunnerFailureClient(cfg),
		Sample:          NewSampleClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ChurnEvent.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ChurnEvent.Use(hooks...)
	c.JobObservation.Use(hooks...)
	c.PhaseTransition.Use(hooks...)
	c.RunnerFailure.Use(hooks...)
	c.Sample.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.ChurnEvent.Intercept(interceptors...)
	c.JobObservation.Intercept(interceptors...)
	c.PhaseTransition.Intercept(interceptors...)
	c.RunnerFailure.Intercept(interceptors...)
	c.Sample.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ChurnEventMutation:
		return c.ChurnEvent.mutate(ctx, m)
	case *JobObservationMutation:
		return c.JobObservation.mutate(ctx, m)
	case *PhaseTransitionMutation:
		return c.PhaseTransition.mutate(ctx, m)
	case *RunnerFailureMutation:
		return c.RunnerFailure.mutate(ctx, m)
	case *SampleMutation:
		return c.Sample.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ChurnEventClient is a client for the ChurnEvent schema.
type ChurnEventClient struct {
	config
}

// NewChurnEventClient returns a client for the ChurnEvent from the given config.
func NewChurnEventClient(c config) *ChurnEventClient {
	return &ChurnEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `churnevent.Hooks(f(g(h())))`.
func (c *ChurnEventClient) Use(hooks ...Hook) {
	c.hooks.ChurnEvent = append(c.hooks.ChurnEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `churnevent.Intercept(f(g(h())))`.
func (c *ChurnEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChurnEvent = append(c.inters.ChurnEvent, interceptors...)
}

// Create returns a builder for creating a ChurnEvent entity.
func (c *ChurnEventClient) Create() *ChurnEventCreate {
	mutation := newChurnEventMutation(c.config, OpCreate)
	return &ChurnEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChurnEvent entities.
func (c *ChurnEventClient) CreateBulk(builders ...*ChurnEventCreate) *ChurnEventCreateBulk {
	return &ChurnEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChurnEventClient) MapCreateBulk(slice any, setFunc func(*ChurnEventCreate, int)) *ChurnEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChurnEventCreateBulk{err: fmt.Errorf("calling to ChurnEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChurnEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChurnEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChurnEvent.
func (c *ChurnEventClient) Update() *ChurnEventUpdate {
	mutation := newChurnEventMutation(c.config, OpUpdate)
	return &ChurnEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChurnEventClient) UpdateOne(_m *ChurnEvent) *ChurnEventUpdateOne {
	mutation := newChurnEventMutation(c.config, OpUpdateOne, withChurnEvent(_m))
	return &ChurnEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChurnEventClient) UpdateOneID(id int) *ChurnEventUpdateOne {
	mutation := newChurnEventMutation(c.config, OpUpdateOne, withChurnEventID(id))
	return &ChurnEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChurnEvent.
func (c *ChurnEventClient) Delete() *ChurnEventDelete {
	mutation := newChurnEventMutation(c.config, OpDelete)
	return &ChurnEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChurnEventClient) DeleteOne(_m *ChurnEvent) *ChurnEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChurnEventClient) DeleteOneID(id int) *ChurnEventDeleteOne {
	builder := c.Delete().Where(churnevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChurnEventDeleteOne{builder}
}

// Query returns a query builder for ChurnEvent.
func (c *ChurnEventClient) Query() *ChurnEventQuery {
	return &ChurnEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChurnEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a ChurnEvent entity by its id.
func (c *ChurnEventClient) Get(ctx context.Context, id int) (*ChurnEvent, error) {
	return c.Query().Where(churnevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChurnEventClient) GetX(ctx context.Context, id int) *ChurnEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ChurnEventClient) Hooks() []Hook {
	return c.hooks.ChurnEvent
}

// Interceptors returns the client interceptors.
func (c *ChurnEventClient) Interceptors() []Interceptor {
	return c.inters.ChurnEvent
}

func (c *ChurnEventClient) mutate(ctx context.Context, m *ChurnEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChurnEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChurnEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChurnEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChurnEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChurnEvent mutation op: %q", m.Op())
	}
}

// JobObservationClient is a client for the JobObservation schema.
type JobObservationClient struct {
	config
}

// NewJobObservationClient returns a client for the JobObservation from the given config.
func NewJobObservationClient(c config) *JobObservationClient {
	return &JobObservationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `jobobservation.Hooks(f(g(h())))`.
func (c *JobObservationClient) Use(hooks ...Hook) {
	c.hooks.JobObservation = append(c.hooks.JobObservation, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `jobobservation.Intercept(f(g(h())))`.
func (c *JobObservationClient) Intercept(interceptors ...Interceptor) {
	c.inters.JobObservation = append(c.inters.JobObservation, interceptors...)
}

// Create returns a builder for creating a JobObservation entity.
func (c *JobObservationClient) Create() *JobObservationCreate {
	mutation := newJobObservationMutation(c.config, OpCreate)
	return &JobObservationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of JobObservation entities.
func (c *JobObservationClient) CreateBulk(builders ...*JobObservationCreate) *JobObservationCreateBulk {
	return &JobObservationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *JobObservationClient) MapCreateBulk(slice any, setFunc func(*JobObservationCreate, int)) *JobObservationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &JobObservationCreateBulk{err: fmt.Errorf("calling to JobObservationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*JobObservationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &JobObservationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for JobObservation.
func (c *JobObservationClient) Update() *JobObservationUpdate {
	mutation := newJobObservationMutation(c.config, OpUpdate)
	return &JobObservationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *JobObservationClient) UpdateOne(_m *JobObservation) *JobObservationUpdateOne {
	mutation := newJobObservationMutation(c.config, OpUpdateOne, withJobObservation(_m))
	return &JobObservationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *JobObservationClient) UpdateOneID(id int) *JobObservationUpdateOne {
	mutation := newJobObservationMutation(c.config, OpUpdateOne, withJobObservationID(id))
	return &JobObservationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for JobObservation.
func (c *JobObservationClient) Delete() *JobObservationDelete {
	mutation := newJobObservationMutation(c.config, OpDelete)
	return &JobObservationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *JobObservationClient) DeleteOne(_m *JobObservation) *JobObservationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *JobObservationClient) DeleteOneID(id int) *JobObservationDeleteOne {
	builder := c.Delete().Where(jobobservation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &JobObservationDeleteOne{builder}
}

// Query returns a query builder for JobObservation.
func (c *JobObservationClient) Query() *JobObservationQuery {
	return &JobObservationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeJobObservation},
		inters: c.Interceptors(),
	}
}

// Get returns a JobObservation entity by its id.
func (c *JobObservationClient) Get(ctx context.Context, id int) (*JobObservation, error) {
	return c.Query().Where(jobobservation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *JobObservationClient) GetX(ctx context.Context, id int) *JobObservation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *JobObservationClient) Hooks() []Hook {
	return c.hooks.JobObservation
}

// Interceptors returns the client interceptors.
func (c *JobObservationClient) Interceptors() []Interceptor {
	return c.inters.JobObservation
}

func (c *JobObservationClient) mutate(ctx context.Context, m *JobObservationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&JobObservationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&JobObservationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&JobObservationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&JobObservationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown JobObservation mutation op: %q", m.Op())
	}
}

// PhaseTransitionClient is a client for the PhaseTransition schema.
type PhaseTransitionClient struct {
	config
}

// NewPhaseTransitionClient returns a client for the PhaseTransition from the given config.
func NewPhaseTransitionClient(c config) *PhaseTransitionClient {
	return &PhaseTransitionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `phasetransition.Hooks(f(g(h())))`.
func (c *PhaseTransitionClient) Use(hooks ...Hook) {
	c.hooks.PhaseTransition = append(c.hooks.PhaseTransition, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `phasetransition.Intercept(f(g(h())))`.
func (c *PhaseTransitionClient) Intercept(interceptors ...Interceptor) {
	c.inters.PhaseTransition = append(c.inters.PhaseTransition, interceptors...)
}

// Create returns a builder for creating a PhaseTransition entity.
func (c *PhaseTransitionClient) Create() *PhaseTransitionCreate {
	mutation := newPhaseTransitionMutation(c.config, OpCreate)
	return &PhaseTransitionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PhaseTransition entities.
func (c *PhaseTransitionClient) CreateBulk(builders ...*PhaseTransitionCreate) *PhaseTransitionCreateBulk {
	return &PhaseTransitionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PhaseTransitionClient) MapCreateBulk(slice any, setFunc func(*PhaseTransitionCreate, int)) *PhaseTransitionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PhaseTransitionCreateBulk{err: fmt.Errorf("calling to PhaseTransitionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PhaseTransitionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PhaseTransitionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PhaseTransition.
func (c *PhaseTransitionClient) Update() *PhaseTransitionUpdate {
	mutation := newPhaseTransitionMutation(c.config, OpUpdate)
	return &PhaseTransitionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PhaseTransitionClient) UpdateOne(_m *PhaseTransition) *PhaseTransitionUpdateOne {
	mutation := newPhaseTransitionMutation(c.config, OpUpdateOne, withPhaseTransition(_m))
	return &PhaseTransitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PhaseTransitionClient) UpdateOneID(id int) *PhaseTransitionUpdateOne {
	mutation := newPhaseTransitionMutation(c.config, OpUpdateOne, withPhaseTransitionID(id))
	return &PhaseTransitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PhaseTransition.
func (c *PhaseTransitionClient) Delete() *PhaseTransitionDelete {
	mutation := newPhaseTransitionMutation(c.config, OpDelete)
	return &PhaseTransitionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PhaseTransitionClient) DeleteOne(_m *PhaseTransition) *PhaseTransitionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PhaseTransitionClient) DeleteOneID(id int) *PhaseTransitionDeleteOne {
	builder := c.Delete().Where(phasetransition.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PhaseTransitionDeleteOne{builder}
}

// Query returns a query builder for PhaseTransition.
func (c *PhaseTransitionClient) Query() *PhaseTransitionQuery {
	return &PhaseTransitionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePhaseTransition},
		inters: c.Interceptors(),
	}
}

// Get returns a PhaseTransition entity by its id.
func (c *PhaseTransitionClient) Get(ctx context.Context, id int) (*PhaseTransition, error) {
	return c.Query().Where(phasetransition.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PhaseTransitionClient) GetX(ctx context.Context, id int) *PhaseTransition {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PhaseTransitionClient) Hooks() []Hook {
	return c.hooks.PhaseTransition
}

// Interceptors returns the client interceptors.
func (c *PhaseTransitionClient) Interceptors() []Interceptor {
	return c.inters.PhaseTransition
}

func (c *PhaseTransitionClient) mutate(ctx context.Context, m *PhaseTransitionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PhaseTransitionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PhaseTransitionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PhaseTransitionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PhaseTransitionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PhaseTransition mutation op: %q", m.Op())
	}
}

// RunnerFailureClient is a client for the RunnerFailure schema.
type RunnerFailureClient struct {
	config
}

// NewRunnerFailureClient returns a client for the RunnerFailure from the given config.
func NewRunnerFailureClient(c config) *RunnerFailureClient {
	return &RunnerFailureClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `runnerfailure.Hooks(f(g(h())))`.
func (c *RunnerFailureClient) Use(hooks ...Hook) {
	c.hooks.RunnerFailure = append(c.hooks.RunnerFailure, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `runnerfailure.Intercept(f(g(h())))`.
func (c *RunnerFailureClient) Intercept(interceptors ...Interceptor) {
	c.inters.RunnerFailure = append(c.inters.RunnerFailure, interceptors...)
}

// Create returns a builder for creating a RunnerFailure entity.
func (c *RunnerFailureClient) Create() *RunnerFailureCreate {
	mutation := newRunnerFailureMutation(c.config, OpCreate)
	return &RunnerFailureCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RunnerFailure entities.
func (c *RunnerFailureClient) CreateBulk(builders ...*RunnerFailureCreate) *RunnerFailureCreateBulk {
	return &RunnerFailureCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RunnerFailureClient) MapCreateBulk(slice any, setFunc func(*RunnerFailureCreate, int)) *RunnerFailureCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RunnerFailureCreateBulk{err: fmt.Errorf("calling to RunnerFailureClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RunnerFailureCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RunnerFailureCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RunnerFailure.
func (c *RunnerFailureClient) Update() *RunnerFailureUpdate {
	mutation := newRunnerFailureMutation(c.config, OpUpdate)
	return &RunnerFailureUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RunnerFailureClient) UpdateOne(_m *RunnerFailure) *RunnerFailureUpdateOne {
	mutation := newRunnerFailureMutation(c.config, OpUpdateOne, withRunnerFailure(_m))
	return &RunnerFailureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RunnerFailureClient) UpdateOneID(id int) *RunnerFailureUpdateOne {
	mutation := newRunnerFailureMutation(c.config, OpUpdateOne, withRunnerFailureID(id))
	return &RunnerFailureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RunnerFailure.
func (c *RunnerFailureClient) Delete() *RunnerFailureDelete {
	mutation := newRunnerFailureMutation(c.config, OpDelete)
	return &RunnerFailureDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RunnerFailureClient) DeleteOne(_m *RunnerFailure) *RunnerFailureDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RunnerFailureClient) DeleteOneID(id int) *RunnerFailureDeleteOne {
	builder := c.Delete().Where(runnerfailure.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RunnerFailureDeleteOne{builder}
}

// Query returns a query builder for RunnerFailure.
func (c *RunnerFailureClient) Query() *RunnerFailureQuery {
	return &RunnerFailureQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRunnerFailure},
		inters: c.Interceptors(),
	}
}

// Get returns a RunnerFailure entity by its id.
func (c *RunnerFailureClient) Get(ctx context.Context, id int) (*RunnerFailure, error) {
	return c.Query().Where(runnerfailure.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RunnerFailureClient) GetX(ctx context.Context, id int) *RunnerFailure {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RunnerFailureClient) Hooks() []Hook {
	return c.hooks.RunnerFailure
}

// Interceptors returns the client interceptors.
func (c *RunnerFailureClient) Interceptors() []Interceptor {
	return c.inters.RunnerFailure
}

func (c *RunnerFailureClient) mutate(ctx context.Context, m *RunnerFailureMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RunnerFailureCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RunnerFailureUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RunnerFailureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RunnerFailureDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RunnerFailure mutation op: %q", m.Op())
	}
}

// SampleClient is a client for the Sample schema.
type SampleClient struct {
	config
}

// NewSampleClient returns a client for the Sample from the given config.
func NewSampleClient(c config) *SampleClient {
	return &SampleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sample.Hooks(f(g(h())))`.
func (c *SampleClient) Use(hooks ...Hook) {
	c.hooks.Sample = append(c.hooks.Sample, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sample.Intercept(f(g(h())))`.
func (c *SampleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Sample = append(c.inters.Sample, interceptors...)
}

// Create returns a builder for creating a Sample entity.
func (c *SampleClient) Create() *SampleCreate {
	mutation := newSampleMutation(c.config, OpCreate)
	return &SampleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Sample entities.
func (c *SampleClient) CreateBulk(builders ...*SampleCreate) *SampleCreateBulk {
	return &SampleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SampleClient) MapCreateBulk(slice any, setFunc func(*SampleCreate, int)) *SampleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SampleCreateBulk{err: fmt.Errorf("calling to SampleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SampleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SampleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Sample.
func (c *SampleClient) Update() *SampleUpdate {
	mutation := newSampleMutation(c.config, OpUpdate)
	return &SampleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SampleClient) UpdateOne(_m *Sample) *SampleUpdateOne {
	mutation := newSampleMutation(c.config, OpUpdateOne, withSample(_m))
	return &SampleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SampleClient) UpdateOneID(id int) *SampleUpdateOne {
	mutation := newSampleMutation(c.config, OpUpdateOne, withSampleID(id))
	return &SampleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Sample.
func (c *SampleClient) Delete() *SampleDelete {
	mutation := newSampleMutation(c.config, OpDelete)
	return &SampleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SampleClient) DeleteOne(_m *Sample) *SampleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SampleClient) DeleteOneID(id int) *SampleDeleteOne {
	builder := c.Delete().Where(sample.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SampleDeleteOne{builder}
}

// Query returns a query builder for Sample.
func (c *SampleClient) Query() *SampleQuery {
	return &SampleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSample},
		inters: c.Interceptors(),
	}
}

// Get returns a Sample entity by its id.
func (c *SampleClient) Get(ctx context.Context, id int) (*Sample, error) {
	return c.Query().Where(sample.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SampleClient) GetX(ctx context.Context, id int) *Sample {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SampleClient) Hooks() []Hook {
	return c.hooks.Sample
}

// Interceptors returns the client interceptors.
func (c *SampleClient) Interceptors() []Interceptor {
	return c.inters.Sample
}

func (c *SampleClient) mutate(ctx context.Context, m *SampleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SampleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SampleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SampleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SampleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Sample mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ChurnEvent, JobObservation, PhaseTransition, RunnerFailure, Sample []ent.Hook
	}
	inters struct {
		ChurnEvent, JobObservation, PhaseTransition, RunnerFailure,
		Sample []ent.Interceptor
	}
)
