// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/jobobservation"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// JobObservation is the model entity for the JobObservation schema.
type JobObservation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RunnerName holds the value of the "runner_name" field.
	RunnerName string `json:"runner_name,omitempty"`
	// SetName holds the value of the "set_name" field.
	SetName string `json:"set_name,omitempty"`
	// Repository holds the value of the "repository" field.
	Repository string `json:"repository,omitempty"`
	// Workflow holds the value of the "workflow" field.
	Workflow string `json:"workflow,omitempty"`
	// JobName holds the value of the "job_name" field.
	JobName string `json:"job_name,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID int64 `json:"run_id,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt int64 `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt int64 `json:"finished_at,omitempty"`
	// Succeeded holds the value of the "succeeded" field.
	Succeeded bool `json:"succeeded,omitempty"`
	// CPUSeconds holds the value of the "cpu_seconds" field.
	CPUSeconds float64 `json:"cpu_seconds,omitempty"`
	// MemByteSeconds holds the value of the "mem_byte_seconds" field.
	MemByteSeconds float64 `json:"mem_byte_seconds,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JobObservation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case jobobservation.FieldSucceeded:
			values[i] = new(sql.NullBool)
		case jobobservation.FieldCPUSeconds, jobobservation.FieldMemByteSeconds:
			values[i] = new(sql.NullFloat64)
		case jobobservation.FieldID, jobobservation.FieldRunID, jobobservation.FieldStartedAt, jobobservation.FieldFinishedAt:
			values[i] = new(sql.NullInt64)
		case jobobservation.FieldRunnerName, jobobservation.FieldSetName, jobobservation.FieldRepository, jobobservation.FieldWorkflow, jobobservation.FieldJobName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JobObservation fields.
func (_m *JobObservation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jobobservation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case jobobservation.FieldRunnerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field runner_name", values[i])
			} else if value.Valid {
				_m.RunnerName = value.String
			}
		case jobobservation.FieldSetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field set_name", values[i])
			} else if value.Valid {
				_m.SetName = value.String
			}
		case jobobservation.FieldRepository:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repository", values[i])
			} else if value.Valid {
				_m.Repository = value.String
			}
		case jobobservation.FieldWorkflow:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow", values[i])
			} else if value.Valid {
				_m.Workflow = value.String
			}
		case jobobservation.FieldJobName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_name", values[i])
			} else if value.Valid {
				_m.JobName = value.String
			}
		case jobobservation.FieldRunID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = value.Int64
			}
		case jobobservation.FieldStartedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Int64
			}
		case jobobservation.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = value.Int64
			}
		case jobobservation.FieldSucceeded:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field succeeded", values[i])
			} else if value.Valid {
				_m.Succeeded = value.Bool
			}
		case jobobservation.FieldCPUSeconds:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cpu_seconds", values[i])
			} else if value.Valid {
				_m.CPUSeconds = value.Float64
			}
		case jobobservation.FieldMemByteSeconds:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field mem_byte_seconds", values[i])
			} else if value.Valid {
				_m.MemByteSeconds = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JobObservation.
// This includes values selected through modifiers, order, etc.
func (_m *JobObservation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this JobObservation.
// Note that you need to call JobObservation.Unwrap() before calling this method if this JobObservation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *JobObservation) Update() *JobObservationUpdateOne {
	return NewJobObservationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the JobObservation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *JobObservation) Unwrap() *JobObservation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: JobObservation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *JobObservation) String() string {
	var builder strings.Builder
	builder.WriteString("JobObservation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("runner_name=")
	builder.WriteString(_m.RunnerName)
	builder.WriteString(", ")
	builder.WriteString("set_name=")
	builder.WriteString(_m.SetName)
	builder.WriteString(", ")
	builder.WriteString("repository=")
	builder.WriteString(_m.Repository)
	builder.WriteString(", ")
	builder.WriteString("workflow=")
	builder.WriteString(_m.Workflow)
	builder.WriteString(", ")
	builder.WriteString("job_name=")
	builder.WriteString(_m.JobName)
	builder.WriteString(", ")
	builder.WriteString("run_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RunID))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartedAt))
	builder.WriteString(", ")
	builder.WriteString("finished_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.FinishedAt))
	builder.WriteString(", ")
	builder.WriteString("succeeded=")
	builder.WriteString(fmt.Sprintf("%v", _m.Succeeded))
	builder.WriteString(", ")
	builder.WriteString("cpu_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.CPUSeconds))
	builder.WriteString(", ")
	builder.WriteString("mem_byte_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemByteSeconds))
	builder.WriteByte(')')
	return builder.String()
}

// JobObservations is a parsable slice of JobObservation.
type JobObservations []*JobObservation
