// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/jobobservation"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobObservationCreate is the builder for creating a JobObservation entity.
type JobObservationCreate struct {
	config
	mutation *JobObservationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRunnerName sets the "runner_name" field.
func (_c *JobObservationCreate) SetRunnerName(v string) *JobObservationCreate {
	_c.mutation.SetRunnerName(v)
	return _c
}

// SetSetName sets the "set_name" field.
func (_c *JobObservationCreate) SetSetName(v string) *JobObservationCreate {
	_c.mutation.SetSetName(v)
	return _c
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_c *JobObservationCreate) SetNillableSetName(v *string) *JobObservationCreate {
	if v != nil {
		_c.SetSetName(*v)
	}
	return _c
}

// SetRepository sets the "repository" field.
func (_c *JobObservationCreate) SetRepository(v string) *JobObservationCreate {
	_c.mutation.SetRepository(v)
	return _c
}

// SetNillableRepository sets the "repository" field if the given value is not nil.
func (_c *JobObservationCreate) SetNillableRepository(v *string) *JobObservationCreate {
	if v != nil {
		_c.SetRepository(*v)
	}
	return _c
}

// SetWorkflow sets the "workflow" field.
func (_c *JobObservationCreate) SetWorkflow(v string) *JobObservationCreate {
	_c.mutation.SetWorkflow(v)
	return _c
}

// SetNillableWorkflow sets the "workflow" field if the given value is not nil.
func (_c *JobObservationCreate) SetNillableWorkflow(v *string) *JobObservationCreate {
	if v != nil {
		_c.SetWorkflow(*v)
	}
	return _c
}

// SetJobName sets the "job_name" field.
func (_c *JobObservationCreate) SetJobName(v string) *JobObservationCreate {
	_c.mutation.SetJobName(v)
	return _c
}

// SetNillableJobName sets the "job_name" field if the given value is not nil.
func (_c *JobObservationCreate) SetNillableJobName(v *string) *JobObservationCreate {
	if v != nil {
		_c.SetJobName(*v)
	}
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *JobObservationCreate) SetRunID(v int64) *JobObservationCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_c *JobObservationCreate) SetNillableRunID(v *int64) *JobObservationCreate {
	if v != nil {
		_c.SetRunID(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *JobObservationCreate) SetStartedAt(v int64) *JobObservationCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *JobObservationCreate) SetFinishedAt(v int64) *JobObservationCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *JobObservationCreate) SetNillableFinishedAt(v *int64) *JobObservationCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetSucceeded sets the "succeeded" field.
func (_c *JobObservationCreate) SetSucceeded(v bool) *JobObservationCreate {
	_c.mutation.SetSucceeded(v)
	return _c
}

// SetNillableSucceeded sets the "succeeded" field if the given value is not nil.
func (_c *JobObservationCreate) SetNillableSucceeded(v *bool) *JobObservationCreate {
	if v != nil {
		_c.SetSucceeded(*v)
	}
	return _c
}

// SetCPUSeconds sets the "cpu_seconds" field.
func (_c *JobObservationCreate) SetCPUSeconds(v float64) *JobObservationCreate {
	_c.mutation.SetCPUSeconds(v)
	return _c
}

// SetNillableCPUSeconds sets the "cpu_seconds" field if the given value is not nil.
func (_c *JobObservationCreate) SetNillableCPUSeconds(v *float64) *JobObservationCreate {
	if v != nil {
		_c.SetCPUSeconds(*v)
	}
	return _c
}

// SetMemByteSeconds sets the "mem_byte_seconds" field.
func (_c *JobObservationCreate) SetMemByteSeconds(v float64) *JobObservationCreate {
	_c.mutation.SetMemByteSeconds(v)
	return _c
}

// SetNillableMemByteSeconds sets the "mem_byte_seconds" field if the given value is not nil.
func (_c *JobObservationCreate) SetNillableMemByteSeconds(v *float64) *JobObservationCreate {
	if v != nil {
		_c.SetMemByteSeconds(*v)
	}
	return _c
}

// Mutation returns the JobObservationMutation object of the builder.
func (_c *JobObservationCreate) Mutation() *JobObservationMutation {
	return _c.mutation
}

// Save creates the JobObservation in the database.
func (_c *JobObservationCreate) Save(ctx context.Context) (*JobObservation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JobObservationCreate) SaveX(ctx context.Context) *JobObservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobObservationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobObservationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *JobObservationCreate) defaults() {
	if _, ok := _c.mutation.SetName(); !ok {
		v := jobobservation.DefaultSetName
		_c.mutation.SetSetName(v)
	}
	if _, ok := _c.mutation.Repository(); !ok {
		v := jobobservation.DefaultRepository
		_c.mutation.SetRepository(v)
	}
	if _, ok := _c.mutation.Workflow(); !ok {
		v := jobobservation.DefaultWorkflow
		_c.mutation.SetWorkflow(v)
	}
	if _, ok := _c.mutation.JobName(); !ok {
		v := jobobservation.DefaultJobName
		_c.mutation.SetJobName(v)
	}
	if _, ok := _c.mutation.RunID(); !ok {
		v := jobobservation.DefaultRunID
		_c.mutation.SetRunID(v)
	}
	if _, ok := _c.mutation.FinishedAt(); !ok {
		v := jobobservation.DefaultFinishedAt
		_c.mutation.SetFinishedAt(v)
	}
	if _, ok := _c.mutation.Succeeded(); !ok {
		v := jobobservation.DefaultSucceeded
		_c.mutation.SetSucceeded(v)
	}
	if _, ok := _c.mutation.CPUSeconds(); !ok {
		v := jobobservation.DefaultCPUSeconds
		_c.mutation.SetCPUSeconds(v)
	}
	if _, ok := _c.mutation.MemByteSeconds(); !ok {
		v := jobobservation.DefaultMemByteSeconds
		_c.mutation.SetMemByteSeconds(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JobObservationCreate) check() error {
	if _, ok := _c.mutation.RunnerName(); !ok {
		return &ValidationError{Name: "runner_name", err: errors.New(`ent: missing required field "JobObservation.runner_name"`)}
	}
	if _, ok := _c.mutation.SetName(); !ok {
		return &ValidationError{Name: "set_name", err: errors.New(`ent: missing required field "JobObservation.set_name"`)}
	}
	if _, ok := _c.mutation.Repository(); !ok {
		return &ValidationError{Name: "repository", err: errors.New(`ent: missing required field "JobObservation.repository"`)}
	}
	if _, ok := _c.mutation.Workflow(); !ok {
		return &ValidationError{Name: "workflow", err: errors.New(`ent: missing required field "JobObservation.workflow"`)}
	}
	if _, ok := _c.mutation.JobName(); !ok {
		return &ValidationError{Name: "job_name", err: errors.New(`ent: missing required field "JobObservation.job_name"`)}
	}
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "JobObservation.run_id"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "JobObservation.started_at"`)}
	}
	if _, ok := _c.mutation.FinishedAt(); !ok {
		return &ValidationError{Name: "finished_at", err: errors.New(`ent: missing required field "JobObservation.finished_at"`)}
	}
	if _, ok := _c.mutation.Succeeded(); !ok {
		return &ValidationError{Name: "succeeded", err: errors.New(`ent: missing required field "JobObservation.succeeded"`)}
	}
	if _, ok := _c.mutation.CPUSeconds(); !ok {
		return &ValidationError{Name: "cpu_seconds", err: errors.New(`ent: missing required field "JobObservation.cpu_seconds"`)}
	}
	if _, ok := _c.mutation.MemByteSeconds(); !ok {
		return &ValidationError{Name: "mem_byte_seconds", err: errors.New(`ent: missing required field "JobObservation.mem_byte_seconds"`)}
	}
	return nil
}

func (_c *JobObservationCreate) sqlSave(ctx context.Context) (*JobObservation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JobObservationCreate) createSpec() (*JobObservation, *sqlgraph.CreateSpec) {
	var (
		_node = &JobObservation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(jobobservation.Table, sqlgraph.NewFieldSpec(jobobservation.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RunnerName(); ok {
		_spec.SetField(jobobservation.FieldRunnerName, field.TypeString, value)
		_node.RunnerName = value
	}
	if value, ok := _c.mutation.SetName(); ok {
		_spec.SetField(jobobservation.FieldSetName, field.TypeString, value)
		_node.SetName = value
	}
	if value, ok := _c.mutation.Repository(); ok {
		_spec.SetField(jobobservation.FieldRepository, field.TypeString, value)
		_node.Repository = value
	}
	if value, ok := _c.mutation.Workflow(); ok {
		_spec.SetField(jobobservation.FieldWorkflow, field.TypeString, value)
		_node.Workflow = value
	}
	if value, ok := _c.mutation.JobName(); ok {
		_spec.SetField(jobobservation.FieldJobName, field.TypeString, value)
		_node.JobName = value
	}
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(jobobservation.FieldRunID, field.TypeInt64, value)
		_node.RunID = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(jobobservation.FieldStartedAt, field.TypeInt64, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(jobobservation.FieldFinishedAt, field.TypeInt64, value)
		_node.FinishedAt = value
	}
	if value, ok := _c.mutation.Succeeded(); ok {
		_spec.SetField(jobobservation.FieldSucceeded, field.TypeBool, value)
		_node.Succeeded = value
	}
	if value, ok := _c.mutation.CPUSeconds(); ok {
		_spec.SetField(jobobservation.FieldCPUSeconds, field.TypeFloat64, value)
		_node.CPUSeconds = value
	}
	if value, ok := _c.mutation.MemByteSeconds(); ok {
		_spec.SetField(jobobservation.FieldMemByteSeconds, field.TypeFloat64, value)
		_node.MemByteSeconds = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.JobObservation.Create().
//		SetRunnerName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.JobObservationUpsert) {
//			SetRunnerName(v+v).
//		}).
//		Exec(ctx)
func (_c *JobObservationCreate) OnConflict(opts ...sql.ConflictOption) *JobObservationUpsertOne {
	_c.conflict = opts
	return &JobObservationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.JobObservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *JobObservationCreate) OnConflictColumns(columns ...string) *JobObservationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &JobObservationUpsertOne{
		create: _c,
	}
}

type (
	// JobObservationUpsertOne is the builder for "upsert"-ing
	//  one JobObservation node.
	JobObservationUpsertOne struct {
		create *JobObservationCreate
	}

	// JobObservationUpsert is the "OnConflict" setter.
	JobObservationUpsert struct {
		*sql.UpdateSet
	}
)

// SetRunnerName sets the "runner_name" field.
func (u *JobObservationUpsert) SetRunnerName(v string) *JobObservationUpsert {
	u.Set(jobobservation.FieldRunnerName, v)
	return u
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *JobObservationUpsert) UpdateRunnerName() *JobObservationUpsert {
	u.SetExcluded(jobobservation.FieldRunnerName)
	return u
}

// SetSetName sets the "set_name" field.
func (u *JobObservationUpsert) SetSetName(v string) *JobObservationUpsert {
	u.Set(jobobservation.FieldSetName, v)
	return u
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *JobObservationUpsert) UpdateSetName() *JobObservationUpsert {
	u.SetExcluded(jobobservation.FieldSetName)
	return u
}

// SetRepository sets the "repository" field.
func (u *JobObservationUpsert) SetRepository(v string) *JobObservationUpsert {
	u.Set(jobobservation.FieldRepository, v)
	return u
}

// UpdateRepository sets the "repository" field to the value that was provided on create.
func (u *JobObservationUpsert) UpdateRepository() *JobObservationUpsert {
	u.SetExcluded(jobobservation.FieldRepository)
	return u
}

// SetWorkflow sets the "workflow" field.
func (u *JobObservationUpsert) SetWorkflow(v string) *JobObservationUpsert {
	u.Set(jobobservation.FieldWorkflow, v)
	return u
}

// UpdateWorkflow sets the "workflow" field to the value that was provided on create.
func (u *JobObservationUpsert) UpdateWorkflow() *JobObservationUpsert {
	u.SetExcluded(jobobservation.FieldWorkflow)
	return u
}

// SetJobName sets the "job_name" field.
func (u *JobObservationUpsert) SetJobName(v string) *JobObservationUpsert {
	u.Set(jobobservation.FieldJobName, v)
	return u
}

// UpdateJobName sets the "job_name" field to the value that was provided on create.
func (u *JobObservationUpsert) UpdateJobName() *JobObservationUpsert {
	u.SetExcluded(jobobservation.FieldJobName)
	return u
}

// SetRunID sets the "run_id" field.
func (u *JobObservationUpsert) SetRunID(v int64) *JobObservationUpsert {
	u.Set(jobobservation.FieldRunID, v)
	return u
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *JobObservationUpsert) UpdateRunID() *JobObservationUpsert {
	u.SetExcluded(jobobservation.FieldRunID)
	return u
}

// AddRunID adds v to the "run_id" field.
func (u *JobObservationUpsert) AddRunID(v int64) *JobObservationUpsert {
	u.Add(jobobservation.FieldRunID, v)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *JobObservationUpsert) SetStartedAt(v int64) *JobObservationUpsert {
	u.Set(jobobservation.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *JobObservationUpsert) UpdateStartedAt() *JobObservationUpsert {
	u.SetExcluded(jobobservation.FieldStartedAt)
	return u
}

// AddStartedAt adds v to the "started_at" field.
func (u *JobObservationUpsert) AddStartedAt(v int64) *JobObservationUpsert {
	u.Add(jobobservation.FieldStartedAt, v)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *JobObservationUpsert) SetFinishedAt(v int64) *JobObservationUpsert {
	u.Set(jobobservation.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *JobObservationUpsert) UpdateFinishedAt() *JobObservationUpsert {
	u.SetExcluded(jobobservation.FieldFinishedAt)
	return u
}

// AddFinishedAt adds v to the "finished_at" field.
func (u *JobObservationUpsert) AddFinishedAt(v int64) *JobObservationUpsert {
	u.Add(jobobservation.FieldFinishedAt, v)
	return u
}

// SetSucceeded sets the "succeeded" field.
func (u *JobObservationUpsert) SetSucceeded(v bool) *JobObservationUpsert {
	u.Set(jobobservation.FieldSucceeded, v)
	return u
}

// UpdateSucceeded sets the "succeeded" field to the value that was provided on create.
func (u *JobObservationUpsert) UpdateSucceeded() *JobObservationUpsert {
	u.SetExcluded(jobobservation.FieldSucceeded)
	return u
}

// SetCPUSeconds sets the "cpu_seconds" field.
func (u *JobObservationUpsert) SetCPUSeconds(v float64) *JobObservationUpsert {
	u.Set(jobobservation.FieldCPUSeconds, v)
	return u
}

// UpdateCPUSeconds sets the "cpu_seconds" field to the value that was provided on create.
func (u *JobObservationUpsert) UpdateCPUSeconds() *JobObservationUpsert {
	u.SetExcluded(jobobservation.FieldCPUSeconds)
	return u
}

// AddCPUSeconds adds v to the "cpu_seconds" field.
func (u *JobObservationUpsert) AddCPUSeconds(v float64) *JobObservationUpsert {
	u.Add(jobobservation.FieldCPUSeconds, v)
	return u
}

// SetMemByteSeconds sets the "mem_byte_seconds" field.
func (u *JobObservationUpsert) SetMemByteSeconds(v float64) *JobObservationUpsert {
	u.Set(jobobservation.FieldMemByteSeconds, v)
	return u
}

// UpdateMemByteSeconds sets the "mem_byte_seconds" field to the value that was provided on create.
func (u *JobObservationUpsert) UpdateMemByteSeconds() *JobObservationUpsert {
	u.SetExcluded(jobobservation.FieldMemByteSeconds)
	return u
}

// AddMemByteSeconds adds v to the "mem_byte_seconds" field.
func (u *JobObservationUpsert) AddMemByteSeconds(v float64) *JobObservationUpsert {
	u.Add(jobobservation.FieldMemByteSeconds, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.JobObservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *JobObservationUpsertOne) UpdateNewValues() *JobObservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.JobObservation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *JobObservationUpsertOne) Ignore() *JobObservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *JobObservationUpsertOne) DoNothing() *JobObservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the JobObservationCreate.OnConflict
// documentation for more info.
func (u *JobObservationUpsertOne) Update(set func(*JobObservationUpsert)) *JobObservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&JobObservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunnerName sets the "runner_name" field.
func (u *JobObservationUpsertOne) SetRunnerName(v string) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetRunnerName(v)
	})
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *JobObservationUpsertOne) UpdateRunnerName() *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateRunnerName()
	})
}

// SetSetName sets the "set_name" field.
func (u *JobObservationUpsertOne) SetSetName(v string) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetSetName(v)
	})
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *JobObservationUpsertOne) UpdateSetName() *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateSetName()
	})
}

// SetRepository sets the "repository" field.
func (u *JobObservationUpsertOne) SetRepository(v string) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetRepository(v)
	})
}

// UpdateRepository sets the "repository" field to the value that was provided on create.
func (u *JobObservationUpsertOne) UpdateRepository() *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateRepository()
	})
}

// SetWorkflow sets the "workflow" field.
func (u *JobObservationUpsertOne) SetWorkflow(v string) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetWorkflow(v)
	})
}

// UpdateWorkflow sets the "workflow" field to the value that was provided on create.
func (u *JobObservationUpsertOne) UpdateWorkflow() *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateWorkflow()
	})
}

// SetJobName sets the "job_name" field.
func (u *JobObservationUpsertOne) SetJobName(v string) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetJobName(v)
	})
}

// UpdateJobName sets the "job_name" field to the value that was provided on create.
func (u *JobObservationUpsertOne) UpdateJobName() *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateJobName()
	})
}

// SetRunID sets the "run_id" field.
func (u *JobObservationUpsertOne) SetRunID(v int64) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetRunID(v)
	})
}

// AddRunID adds v to the "run_id" field.
func (u *JobObservationUpsertOne) AddRunID(v int64) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.AddRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *JobObservationUpsertOne) UpdateRunID() *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateRunID()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *JobObservationUpsertOne) SetStartedAt(v int64) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetStartedAt(v)
	})
}

// AddStartedAt adds v to the "started_at" field.
func (u *JobObservationUpsertOne) AddStartedAt(v int64) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.AddStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *JobObservationUpsertOne) UpdateStartedAt() *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *JobObservationUpsertOne) SetFinishedAt(v int64) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetFinishedAt(v)
	})
}

// AddFinishedAt adds v to the "finished_at" field.
func (u *JobObservationUpsertOne) AddFinishedAt(v int64) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.AddFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *JobObservationUpsertOne) UpdateFinishedAt() *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateFinishedAt()
	})
}

// SetSucceeded sets the "succeeded" field.
func (u *JobObservationUpsertOne) SetSucceeded(v bool) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetSucceeded(v)
	})
}

// UpdateSucceeded sets the "succeeded" field to the value that was provided on create.
func (u *JobObservationUpsertOne) UpdateSucceeded() *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateSucceeded()
	})
}

// SetCPUSeconds sets the "cpu_seconds" field.
func (u *JobObservationUpsertOne) SetCPUSeconds(v float64) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetCPUSeconds(v)
	})
}

// AddCPUSeconds adds v to the "cpu_seconds" field.
func (u *JobObservationUpsertOne) AddCPUSeconds(v float64) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.AddCPUSeconds(v)
	})
}

// UpdateCPUSeconds sets the "cpu_seconds" field to the value that was provided on create.
func (u *JobObservationUpsertOne) UpdateCPUSeconds() *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateCPUSeconds()
	})
}

// SetMemByteSeconds sets the "mem_byte_seconds" field.
func (u *JobObservationUpsertOne) SetMemByteSeconds(v float64) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetMemByteSeconds(v)
	})
}

// AddMemByteSeconds adds v to the "mem_byte_seconds" field.
func (u *JobObservationUpsertOne) AddMemByteSeconds(v float64) *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.AddMemByteSeconds(v)
	})
}

// UpdateMemByteSeconds sets the "mem_byte_seconds" field to the value that was provided on create.
func (u *JobObservationUpsertOne) UpdateMemByteSeconds() *JobObservationUpsertOne {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateMemByteSeconds()
	})
}

// Exec executes the query.
func (u *JobObservationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for JobObservationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *JobObservationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *JobObservationUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *JobObservationUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// JobObservationCreateBulk is the builder for creating many JobObservation entities in bulk.
type JobObservationCreateBulk struct {
	config
	err      error
	builders []*JobObservationCreate
	conflict []sql.ConflictOption
}

// Save creates the JobObservation entities in the database.
func (_c *JobObservationCreateBulk) Save(ctx context.Context) ([]*JobObservation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*JobObservation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobObservationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JobObservationCreateBulk) SaveX(ctx context.Context) []*JobObservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobObservationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobObservationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.JobObservation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.JobObservationUpsert) {
//			SetRunnerName(v+v).
//		}).
//		Exec(ctx)
func (_c *JobObservationCreateBulk) OnConflict(opts ...sql.ConflictOption) *JobObservationUpsertBulk {
	_c.conflict = opts
	return &JobObservationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.JobObservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *JobObservationCreateBulk) OnConflictColumns(columns ...string) *JobObservationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &JobObservationUpsertBulk{
		create: _c,
	}
}

// JobObservationUpsertBulk is the builder for "upsert"-ing
// a bulk of JobObservation nodes.
type JobObservationUpsertBulk struct {
	create *JobObservationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.JobObservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *JobObservationUpsertBulk) UpdateNewValues() *JobObservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.JobObservation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *JobObservationUpsertBulk) Ignore() *JobObservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *JobObservationUpsertBulk) DoNothing() *JobObservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the JobObservationCreateBulk.OnConflict
// documentation for more info.
func (u *JobObservationUpsertBulk) Update(set func(*JobObservationUpsert)) *JobObservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&JobObservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunnerName sets the "runner_name" field.
func (u *JobObservationUpsertBulk) SetRunnerName(v string) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetRunnerName(v)
	})
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *JobObservationUpsertBulk) UpdateRunnerName() *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateRunnerName()
	})
}

// SetSetName sets the "set_name" field.
func (u *JobObservationUpsertBulk) SetSetName(v string) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetSetName(v)
	})
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *JobObservationUpsertBulk) UpdateSetName() *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateSetName()
	})
}

// SetRepository sets the "repository" field.
func (u *JobObservationUpsertBulk) SetRepository(v string) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetRepository(v)
	})
}

// UpdateRepository sets the "repository" field to the value that was provided on create.
func (u *JobObservationUpsertBulk) UpdateRepository() *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateRepository()
	})
}

// SetWorkflow sets the "workflow" field.
func (u *JobObservationUpsertBulk) SetWorkflow(v string) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetWorkflow(v)
	})
}

// UpdateWorkflow sets the "workflow" field to the value that was provided on create.
func (u *JobObservationUpsertBulk) UpdateWorkflow() *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateWorkflow()
	})
}

// SetJobName sets the "job_name" field.
func (u *JobObservationUpsertBulk) SetJobName(v string) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetJobName(v)
	})
}

// UpdateJobName sets the "job_name" field to the value that was provided on create.
func (u *JobObservationUpsertBulk) UpdateJobName() *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateJobName()
	})
}

// SetRunID sets the "run_id" field.
func (u *JobObservationUpsertBulk) SetRunID(v int64) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetRunID(v)
	})
}

// AddRunID adds v to the "run_id" field.
func (u *JobObservationUpsertBulk) AddRunID(v int64) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.AddRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *JobObservationUpsertBulk) UpdateRunID() *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateRunID()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *JobObservationUpsertBulk) SetStartedAt(v int64) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetStartedAt(v)
	})
}

// AddStartedAt adds v to the "started_at" field.
func (u *JobObservationUpsertBulk) AddStartedAt(v int64) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.AddStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *JobObservationUpsertBulk) UpdateStartedAt() *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *JobObservationUpsertBulk) SetFinishedAt(v int64) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetFinishedAt(v)
	})
}

// AddFinishedAt adds v to the "finished_at" field.
func (u *JobObservationUpsertBulk) AddFinishedAt(v int64) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.AddFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *JobObservationUpsertBulk) UpdateFinishedAt() *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateFinishedAt()
	})
}

// SetSucceeded sets the "succeeded" field.
func (u *JobObservationUpsertBulk) SetSucceeded(v bool) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetSucceeded(v)
	})
}

// UpdateSucceeded sets the "succeeded" field to the value that was provided on create.
func (u *JobObservationUpsertBulk) UpdateSucceeded() *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateSucceeded()
	})
}

// SetCPUSeconds sets the "cpu_seconds" field.
func (u *JobObservationUpsertBulk) SetCPUSeconds(v float64) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetCPUSeconds(v)
	})
}

// AddCPUSeconds adds v to the "cpu_seconds" field.
func (u *JobObservationUpsertBulk) AddCPUSeconds(v float64) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.AddCPUSeconds(v)
	})
}

// UpdateCPUSeconds sets the "cpu_seconds" field to the value that was provided on create.
func (u *JobObservationUpsertBulk) UpdateCPUSeconds() *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateCPUSeconds()
	})
}

// SetMemByteSeconds sets the "mem_byte_seconds" field.
func (u *JobObservationUpsertBulk) SetMemByteSeconds(v float64) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.SetMemByteSeconds(v)
	})
}

// AddMemByteSeconds adds v to the "mem_byte_seconds" field.
func (u *JobObservationUpsertBulk) AddMemByteSeconds(v float64) *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.AddMemByteSeconds(v)
	})
}

// UpdateMemByteSeconds sets the "mem_byte_seconds" field to the value that was provided on create.
func (u *JobObservationUpsertBulk) UpdateMemByteSeconds() *JobObservationUpsertBulk {
	return u.Update(func(s *JobObservationUpsert) {
		s.UpdateMemByteSeconds()
	})
}

// Exec executes the query.
func (u *JobObservationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the JobObservationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for JobObservationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *JobObservationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
