// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/jobobservation"
	"arc-ui/internal/store/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobObservationUpdate is the builder for updating JobObservation entities.
type JobObservationUpdate struct {
	config
	hooks    []Hook
	mutation *JobObservationMutation
}

// Where appends a list predicates to the JobObservationUpdate builder.
func (_u *JobObservationUpdate) Where(ps ...predicate.JobObservation) *JobObservationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRunnerName sets the "runner_name" field.
func (_u *JobObservationUpdate) SetRunnerName(v string) *JobObservationUpdate {
	_u.mutation.SetRunnerName(v)
	return _u
}

// SetNillableRunnerName sets the "runner_name" field if the given value is not nil.
func (_u *JobObservationUpdate) SetNillableRunnerName(v *string) *JobObservationUpdate {
	if v != nil {
		_u.SetRunnerName(*v)
	}
	return _u
}

// SetSetName sets the "set_name" field.
func (_u *JobObservationUpdate) SetSetName(v string) *JobObservationUpdate {
	_u.mutation.SetSetName(v)
	return _u
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_u *JobObservationUpdate) SetNillableSetName(v *string) *JobObservationUpdate {
	if v != nil {
		_u.SetSetName(*v)
	}
	return _u
}

// SetRepository sets the "repository" field.
func (_u *JobObservationUpdate) SetRepository(v string) *JobObservationUpdate {
	_u.mutation.SetRepository(v)
	return _u
}

// SetNillableRepository sets the "repository" field if the given value is not nil.
func (_u *JobObservationUpdate) SetNillableRepository(v *string) *JobObservationUpdate {
	if v != nil {
		_u.SetRepository(*v)
	}
	return _u
}

// SetWorkflow sets the "workflow" field.
func (_u *JobObservationUpdate) SetWorkflow(v string) *JobObservationUpdate {
	_u.mutation.SetWorkflow(v)
	return _u
}

// SetNillableWorkflow sets the "workflow" field if the given value is not nil.
func (_u *JobObservationUpdate) SetNillableWorkflow(v *string) *JobObservationUpdate {
	if v != nil {
		_u.SetWorkflow(*v)
	}
	return _u
}

// SetJobName sets the "job_name" field.
func (_u *JobObservationUpdate) SetJobName(v string) *JobObservationUpdate {
	_u.mutation.SetJobName(v)
	return _u
}

// SetNillableJobName sets the "job_name" field if the given value is not nil.
func (_u *JobObservationUpdate) SetNillableJobName(v *string) *JobObservationUpdate {
	if v != nil {
		_u.SetJobName(*v)
	}
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *JobObservationUpdate) SetRunID(v int64) *JobObservationUpdate {
	_u.mutation.ResetRunID()
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *JobObservationUpdate) SetNillableRunID(v *int64) *JobObservationUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// AddRunID adds value to the "run_id" field.
func (_u *JobObservationUpdate) AddRunID(v int64) *JobObservationUpdate {
	_u.mutation.AddRunID(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *JobObservationUpdate) SetStartedAt(v int64) *JobObservationUpdate {
	_u.mutation.ResetStartedAt()
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *JobObservationUpdate) SetNillableStartedAt(v *int64) *JobObservationUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// AddStartedAt adds value to the "started_at" field.
func (_u *JobObservationUpdate) AddStartedAt(v int64) *JobObservationUpdate {
	_u.mutation.AddStartedAt(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobObservationUpdate) SetFinishedAt(v int64) *JobObservationUpdate {
	_u.mutation.ResetFinishedAt()
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobObservationUpdate) SetNillableFinishedAt(v *int64) *JobObservationUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// AddFinishedAt adds value to the "finished_at" field.
func (_u *JobObservationUpdate) AddFinishedAt(v int64) *JobObservationUpdate {
	_u.mutation.AddFinishedAt(v)
	return _u
}

// SetSucceeded sets the "succeeded" field.
func (_u *JobObservationUpdate) SetSucceeded(v bool) *JobObservationUpdate {
	_u.mutation.SetSucceeded(v)
	return _u
}

// SetNillableSucceeded sets the "succeeded" field if the given value is not nil.
func (_u *JobObservationUpdate) SetNillableSucceeded(v *bool) *JobObservationUpdate {
	if v != nil {
		_u.SetSucceeded(*v)
	}
	return _u
}

// SetCPUSeconds sets the "cpu_seconds" field.
func (_u *JobObservationUpdate) SetCPUSeconds(v float64) *JobObservationUpdate {
	_u.mutation.ResetCPUSeconds()
	_u.mutation.SetCPUSeconds(v)
	return _u
}

// SetNillableCPUSeconds sets the "cpu_seconds" field if the given value is not nil.
func (_u *JobObservationUpdate) SetNillableCPUSeconds(v *float64) *JobObservationUpdate {
	if v != nil {
		_u.SetCPUSeconds(*v)
	}
	return _u
}

// AddCPUSeconds adds value to the "cpu_seconds" field.
func (_u *JobObservationUpdate) AddCPUSeconds(v float64) *JobObservationUpdate {
	_u.mutation.AddCPUSeconds(v)
	return _u
}

// SetMemByteSeconds sets the "mem_byte_seconds" field.
func (_u *JobObservationUpdate) SetMemByteSeconds(v float64) *JobObservationUpdate {
	_u.mutation.ResetMemByteSeconds()
	_u.mutation.SetMemByteSeconds(v)
	return _u
}

// SetNillableMemByteSeconds sets the "mem_byte_seconds" field if the given value is not nil.
func (_u *JobObservationUpdate) SetNillableMemByteSeconds(v *float64) *JobObservationUpdate {
	if v != nil {
		_u.SetMemByteSeconds(*v)
	}
	return _u
}

// AddMemByteSeconds adds value to the "mem_byte_seconds" field.
func (_u *JobObservationUpdate) AddMemByteSeconds(v float64) *JobObservationUpdate {
	_u.mutation.AddMemByteSeconds(v)
	return _u
}

// Mutation returns the JobObservationMutation object of the builder.
func (_u *JobObservationUpdate) Mutation() *JobObservationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JobObservationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobObservationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JobObservationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobObservationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *JobObservationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(jobobservation.Table, jobobservation.Columns, sqlgraph.NewFieldSpec(jobobservation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunnerName(); ok {
		_spec.SetField(jobobservation.FieldRunnerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SetName(); ok {
		_spec.SetField(jobobservation.FieldSetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Repository(); ok {
		_spec.SetField(jobobservation.FieldRepository, field.TypeString, value)
	}
	if value, ok := _u.mutation.Workflow(); ok {
		_spec.SetField(jobobservation.FieldWorkflow, field.TypeString, value)
	}
	if value, ok := _u.mutation.JobName(); ok {
		_spec.SetField(jobobservation.FieldJobName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(jobobservation.FieldRunID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRunID(); ok {
		_spec.AddField(jobobservation.FieldRunID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(jobobservation.FieldStartedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStartedAt(); ok {
		_spec.AddField(jobobservation.FieldStartedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(jobobservation.FieldFinishedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFinishedAt(); ok {
		_spec.AddField(jobobservation.FieldFinishedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Succeeded(); ok {
		_spec.SetField(jobobservation.FieldSucceeded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CPUSeconds(); ok {
		_spec.SetField(jobobservation.FieldCPUSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCPUSeconds(); ok {
		_spec.AddField(jobobservation.FieldCPUSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MemByteSeconds(); ok {
		_spec.SetField(jobobservation.FieldMemByteSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMemByteSeconds(); ok {
		_spec.AddField(jobobservation.FieldMemByteSeconds, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobobservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JobObservationUpdateOne is the builder for updating a single JobObservation entity.
type JobObservationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobObservationMutation
}

// SetRunnerName sets the "runner_name" field.
func (_u *JobObservationUpdateOne) SetRunnerName(v string) *JobObservationUpdateOne {
	_u.mutation.SetRunnerName(v)
	return _u
}

// SetNillableRunnerName sets the "runner_name" field if the given value is not nil.
func (_u *JobObservationUpdateOne) SetNillableRunnerName(v *string) *JobObservationUpdateOne {
	if v != nil {
		_u.SetRunnerName(*v)
	}
	return _u
}

// SetSetName sets the "set_name" field.
func (_u *JobObservationUpdateOne) SetSetName(v string) *JobObservationUpdateOne {
	_u.mutation.SetSetName(v)
	return _u
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_u *JobObservationUpdateOne) SetNillableSetName(v *string) *JobObservationUpdateOne {
	if v != nil {
		_u.SetSetName(*v)
	}
	return _u
}

// SetRepository sets the "repository" field.
func (_u *JobObservationUpdateOne) SetRepository(v string) *JobObservationUpdateOne {
	_u.mutation.SetRepository(v)
	return _u
}

// SetNillableRepository sets the "repository" field if the given value is not nil.
func (_u *JobObservationUpdateOne) SetNillableRepository(v *string) *JobObservationUpdateOne {
	if v != nil {
		_u.SetRepository(*v)
	}
	return _u
}

// SetWorkflow sets the "workflow" field.
func (_u *JobObservationUpdateOne) SetWorkflow(v string) *JobObservationUpdateOne {
	_u.mutation.SetWorkflow(v)
	return _u
}

// SetNillableWorkflow sets the "workflow" field if the given value is not nil.
func (_u *JobObservationUpdateOne) SetNillableWorkflow(v *string) *JobObservationUpdateOne {
	if v != nil {
		_u.SetWorkflow(*v)
	}
	return _u
}

// SetJobName sets the "job_name" field.
func (_u *JobObservationUpdateOne) SetJobName(v string) *JobObservationUpdateOne {
	_u.mutation.SetJobName(v)
	return _u
}

// SetNillableJobName sets the "job_name" field if the given value is not nil.
func (_u *JobObservationUpdateOne) SetNillableJobName(v *string) *JobObservationUpdateOne {
	if v != nil {
		_u.SetJobName(*v)
	}
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *JobObservationUpdateOne) SetRunID(v int64) *JobObservationUpdateOne {
	_u.mutation.ResetRunID()
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *JobObservationUpdateOne) SetNillableRunID(v *int64) *JobObservationUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// AddRunID adds value to the "run_id" field.
func (_u *JobObservationUpdateOne) AddRunID(v int64) *JobObservationUpdateOne {
	_u.mutation.AddRunID(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *JobObservationUpdateOne) SetStartedAt(v int64) *JobObservationUpdateOne {
	_u.mutation.ResetStartedAt()
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *JobObservationUpdateOne) SetNillableStartedAt(v *int64) *JobObservationUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// AddStartedAt adds value to the "started_at" field.
func (_u *JobObservationUpdateOne) AddStartedAt(v int64) *JobObservationUpdateOne {
	_u.mutation.AddStartedAt(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobObservationUpdateOne) SetFinishedAt(v int64) *JobObservationUpdateOne {
	_u.mutation.ResetFinishedAt()
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobObservationUpdateOne) SetNillableFinishedAt(v *int64) *JobObservationUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// AddFinishedAt adds value to the "finished_at" field.
func (_u *JobObservationUpdateOne) AddFinishedAt(v int64) *JobObservationUpdateOne {
	_u.mutation.AddFinishedAt(v)
	return _u
}

// SetSucceeded sets the "succeeded" field.
func (_u *JobObservationUpdateOne) SetSucceeded(v bool) *JobObservationUpdateOne {
	_u.mutation.SetSucceeded(v)
	return _u
}

// SetNillableSucceeded sets the "succeeded" field if the given value is not nil.
func (_u *JobObservationUpdateOne) SetNillableSucceeded(v *bool) *JobObservationUpdateOne {
	if v != nil {
		_u.SetSucceeded(*v)
	}
	return _u
}

// SetCPUSeconds sets the "cpu_seconds" field.
func (_u *JobObservationUpdateOne) SetCPUSeconds(v float64) *JobObservationUpdateOne {
	_u.mutation.ResetCPUSeconds()
	_u.mutation.SetCPUSeconds(v)
	return _u
}

// SetNillableCPUSeconds sets the "cpu_seconds" field if the given value is not nil.
func (_u *JobObservationUpdateOne) SetNillableCPUSeconds(v *float64) *JobObservationUpdateOne {
	if v != nil {
		_u.SetCPUSeconds(*v)
	}
	return _u
}

// AddCPUSeconds adds value to the "cpu_seconds" field.
func (_u *JobObservationUpdateOne) AddCPUSeconds(v float64) *JobObservationUpdateOne {
	_u.mutation.AddCPUSeconds(v)
	return _u
}

// SetMemByteSeconds sets the "mem_byte_seconds" field.
func (_u *JobObservationUpdateOne) SetMemByteSeconds(v float64) *JobObservationUpdateOne {
	_u.mutation.ResetMemByteSeconds()
	_u.mutation.SetMemByteSeconds(v)
	return _u
}

// SetNillableMemByteSeconds sets the "mem_byte_seconds" field if the given value is not nil.
func (_u *JobObservationUpdateOne) SetNillableMemByteSeconds(v *float64) *JobObservationUpdateOne {
	if v != nil {
		_u.SetMemByteSeconds(*v)
	}
	return _u
}

// AddMemByteSeconds adds value to the "mem_byte_seconds" field.
func (_u *JobObservationUpdateOne) AddMemByteSeconds(v float64) *JobObservationUpdateOne {
	_u.mutation.AddMemByteSeconds(v)
	return _u
}

// Mutation returns the JobObservationMutation object of the builder.
func (_u *JobObservationUpdateOne) Mutation() *JobObservationMutation {
	return _u.mutation
}

// Where appends a list predicates to the JobObservationUpdate builder.
func (_u *JobObservationUpdateOne) Where(ps ...predicate.JobObservation) *JobObservationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JobObservationUpdateOne) Select(field string, fields ...string) *JobObservationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated JobObservation entity.
func (_u *JobObservationUpdateOne) Save(ctx context.Context) (*JobObservation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobObservationUpdateOne) SaveX(ctx context.Context) *JobObservation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JobObservationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobObservationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *JobObservationUpdateOne) sqlSave(ctx context.Context) (_node *JobObservation, err error) {
	_spec := sqlgraph.NewUpdateSpec(jobobservation.Table, jobobservation.Columns, sqlgraph.NewFieldSpec(jobobservation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "JobObservation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobobservation.FieldID)
		for _, f := range fields {
			if !jobobservation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != jobobservation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunnerName(); ok {
		_spec.SetField(jobobservation.FieldRunnerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SetName(); ok {
		_spec.SetField(jobobservation.FieldSetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Repository(); ok {
		_spec.SetField(jobobservation.FieldRepository, field.TypeString, value)
	}
	if value, ok := _u.mutation.Workflow(); ok {
		_spec.SetField(jobobservation.FieldWorkflow, field.TypeString, value)
	}
	if value, ok := _u.mutation.JobName(); ok {
		_spec.SetField(jobobservation.FieldJobName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(jobobservation.FieldRunID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRunID(); ok {
		_spec.AddField(jobobservation.FieldRunID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(jobobservation.FieldStartedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStartedAt(); ok {
		_spec.AddField(jobobservation.FieldStartedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(jobobservation.FieldFinishedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFinishedAt(); ok {
		_spec.AddField(jobobservation.FieldFinishedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Succeeded(); ok {
		_spec.SetField(jobobservation.FieldSucceeded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CPUSeconds(); ok {
		_spec.SetField(jobobservation.FieldCPUSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCPUSeconds(); ok {
		_spec.AddField(jobobservation.FieldCPUSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MemByteSeconds(); ok {
		_spec.SetField(jobobservation.FieldMemByteSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMemByteSeconds(); ok {
		_spec.AddField(jobobservation.FieldMemByteSeconds, field.TypeFloat64, value)
	}
	_node = &JobObservation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobobservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
