// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/jobsample"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// JobSample is the model entity for the JobSample schema.
type JobSample struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID int `json:"job_id,omitempty"`
	// Ts holds the value of the "ts" field.
	Ts int64 `json:"ts,omitempty"`
	// CPUCores holds the value of the "cpu_cores" field.
	CPUCores float64 `json:"cpu_cores,omitempty"`
	// MemBytes holds the value of the "mem_bytes" field.
	MemBytes float64 `json:"mem_bytes,omitempty"`
	// Samples holds the value of the "samples" field.
	Samples      int `json:"samples,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JobSample) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case jobsample.FieldCPUCores, jobsample.FieldMemBytes:
			values[i] = new(sql.NullFloat64)
		case jobsample.FieldID, jobsample.FieldJobID, jobsample.FieldTs, jobsample.FieldSamples:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JobSample fields.
func (_m *JobSample) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jobsample.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case jobsample.FieldJobID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = int(value.Int64)
			}
		case jobsample.FieldTs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ts", values[i])
			} else if value.Valid {
				_m.Ts = value.Int64
			}
		case jobsample.FieldCPUCores:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cpu_cores", values[i])
			} else if value.Valid {
				_m.CPUCores = value.Float64
			}
		case jobsample.FieldMemBytes:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field mem_bytes", values[i])
			} else if value.Valid {
				_m.MemBytes = value.Float64
			}
		case jobsample.FieldSamples:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field samples", values[i])
			} else if value.Valid {
				_m.Samples = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JobSample.
// This includes values selected through modifiers, order, etc.
func (_m *JobSample) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this JobSample.
// Note that you need to call JobSample.Unwrap() before calling this method if this JobSample
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *JobSample) Update() *JobSampleUpdateOne {
	return NewJobSampleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the JobSample entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *JobSample) Unwrap() *JobSample {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: JobSample is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *JobSample) String() string {
	var builder strings.Builder
	builder.WriteString("JobSample(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("job_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.JobID))
	builder.WriteString(", ")
	builder.WriteString("ts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ts))
	builder.WriteString(", ")
	builder.WriteString("cpu_cores=")
	builder.WriteString(fmt.Sprintf("%v", _m.CPUCores))
	builder.WriteString(", ")
	builder.WriteString("mem_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemBytes))
	builder.WriteString(", ")
	builder.WriteString("samples=")
	builder.WriteString(fmt.Sprintf("%v", _m.Samples))
	builder.WriteByte(')')
	return builder.String()
}

// JobSamples is a parsable slice of JobSample.
type JobSamples []*JobSample
