// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/jobsample"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobSampleCreate is the builder for creating a JobSample entity.
type JobSampleCreate struct {
	config
	mutation *JobSampleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetJobID sets the "job_id" field.
func (_c *JobSampleCreate) SetJobID(v int) *JobSampleCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetTs sets the "ts" field.
func (_c *JobSampleCreate) SetTs(v int64) *JobSampleCreate {
	_c.mutation.SetTs(v)
	return _c
}

// SetCPUCores sets the "cpu_cores" field.
func (_c *JobSampleCreate) SetCPUCores(v float64) *JobSampleCreate {
	_c.mutation.SetCPUCores(v)
	return _c
}

// SetNillableCPUCores sets the "cpu_cores" field if the given value is not nil.
func (_c *JobSampleCreate) SetNillableCPUCores(v *float64) *JobSampleCreate {
	if v != nil {
		_c.SetCPUCores(*v)
	}
	return _c
}

// SetMemBytes sets the "mem_bytes" field.
func (_c *JobSampleCreate) SetMemBytes(v float64) *JobSampleCreate {
	_c.mutation.SetMemBytes(v)
	return _c
}

// SetNillableMemBytes sets the "mem_bytes" field if the given value is not nil.
func (_c *JobSampleCreate) SetNillableMemBytes(v *float64) *JobSampleCreate {
	if v != nil {
		_c.SetMemBytes(*v)
	}
	return _c
}

// SetSamples sets the "samples" field.
func (_c *JobSampleCreate) SetSamples(v int) *JobSampleCreate {
	_c.mutation.SetSamples(v)
	return _c
}

// SetNillableSamples sets the "samples" field if the given value is not nil.
func (_c *JobSampleCreate) SetNillableSamples(v *int) *JobSampleCreate {
	if v != nil {
		_c.SetSamples(*v)
	}
	return _c
}

// Mutation returns the JobSampleMutation object of the builder.
func (_c *JobSampleCreate) Mutation() *JobSampleMutation {
	return _c.mutation
}

// Save creates the JobSample in the database.
func (_c *JobSampleCreate) Save(ctx context.Context) (*JobSample, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JobSampleCreate) SaveX(ctx context.Context) *JobSample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobSampleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobSampleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *JobSampleCreate) defaults() {
	if _, ok := _c.mutation.CPUCores(); !ok {
		v := jobsample.DefaultCPUCores
		_c.mutation.SetCPUCores(v)
	}
	if _, ok := _c.mutation.MemBytes(); !ok {
		v := jobsample.DefaultMemBytes
		_c.mutation.SetMemBytes(v)
	}
	if _, ok := _c.mutation.Samples(); !ok {
		v := jobsample.DefaultSamples
		_c.mutation.SetSamples(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JobSampleCreate) check() error {
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "JobSample.job_id"`)}
	}
	if _, ok := _c.mutation.Ts(); !ok {
		return &ValidationError{Name: "ts", err: errors.New(`ent: missing required field "JobSample.ts"`)}
	}
	if _, ok := _c.mutation.CPUCores(); !ok {
		return &ValidationError{Name: "cpu_cores", err: errors.New(`ent: missing required field "JobSample.cpu_cores"`)}
	}
	if _, ok := _c.mutation.MemBytes(); !ok {
		return &ValidationError{Name: "mem_bytes", err: errors.New(`ent: missing required field "JobSample.mem_bytes"`)}
	}
	if _, ok := _c.mutation.Samples(); !ok {
		return &ValidationError{Name: "samples", err: errors.New(`ent: missing required field "JobSample.samples"`)}
	}
	return nil
}

func (_c *JobSampleCreate) sqlSave(ctx context.Context) (*JobSample, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JobSampleCreate) createSpec() (*JobSample, *sqlgraph.CreateSpec) {
	var (
		_node = &JobSample{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(jobsample.Table, sqlgraph.NewFieldSpec(jobsample.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.JobID(); ok {
		_spec.SetField(jobsample.FieldJobID, field.TypeInt, value)
		_node.JobID = value
	}
	if value, ok := _c.mutation.Ts(); ok {
		_spec.SetField(jobsample.FieldTs, field.TypeInt64, value)
		_node.Ts = value
	}
	if value, ok := _c.mutation.CPUCores(); ok {
		_spec.SetField(jobsample.FieldCPUCores, field.TypeFloat64, value)
		_node.CPUCores = value
	}
	if value, ok := _c.mutation.MemBytes(); ok {
		_spec.SetField(jobsample.FieldMemBytes, field.TypeFloat64, value)
		_node.MemBytes = value
	}
	if value, ok := _c.mutation.Samples(); ok {
		_spec.SetField(jobsample.FieldSamples, field.TypeInt, value)
		_node.Samples = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.JobSample.Create().
//		SetJobID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.JobSampleUpsert) {
//			SetJobID(v+v).
//		}).
//		Exec(ctx)
func (_c *JobSampleCreate) OnConflict(opts ...sql.ConflictOption) *JobSampleUpsertOne {
	_c.conflict = opts
	return &JobSampleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.JobSample.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *JobSampleCreate) OnConflictColumns(columns ...string) *JobSampleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &JobSampleUpsertOne{
		create: _c,
	}
}

type (
	// JobSampleUpsertOne is the builder for "upsert"-ing
	//  one JobSample node.
	JobSampleUpsertOne struct {
		create *JobSampleCreate
	}

	// JobSampleUpsert is the "OnConflict" setter.
	JobSampleUpsert struct {
		*sql.UpdateSet
	}
)

// SetJobID sets the "job_id" field.
func (u *JobSampleUpsert) SetJobID(v int) *JobSampleUpsert {
	u.Set(jobsample.FieldJobID, v)
	return u
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *JobSampleUpsert) UpdateJobID() *JobSampleUpsert {
	u.SetExcluded(jobsample.FieldJobID)
	return u
}

// AddJobID adds v to the "job_id" field.
func (u *JobSampleUpsert) AddJobID(v int) *JobSampleUpsert {
	u.Add(jobsample.FieldJobID, v)
	return u
}

// SetTs sets the "ts" field.
func (u *JobSampleUpsert) SetTs(v int64) *JobSampleUpsert {
	u.Set(jobsample.FieldTs, v)
	return u
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *JobSampleUpsert) UpdateTs() *JobSampleUpsert {
	u.SetExcluded(jobsample.FieldTs)
	return u
}

// AddTs adds v to the "ts" field.
func (u *JobSampleUpsert) AddTs(v int64) *JobSampleUpsert {
	u.Add(jobsample.FieldTs, v)
	return u
}

// SetCPUCores sets the "cpu_cores" field.
func (u *JobSampleUpsert) SetCPUCores(v float64) *JobSampleUpsert {
	u.Set(jobsample.FieldCPUCores, v)
	return u
}

// UpdateCPUCores sets the "cpu_cores" field to the value that was provided on create.
func (u *JobSampleUpsert) UpdateCPUCores() *JobSampleUpsert {
	u.SetExcluded(jobsample.FieldCPUCores)
	return u
}

// AddCPUCores adds v to the "cpu_cores" field.
func (u *JobSampleUpsert) AddCPUCores(v float64) *JobSampleUpsert {
	u.Add(jobsample.FieldCPUCores, v)
	return u
}

// SetMemBytes sets the "mem_bytes" field.
func (u *JobSampleUpsert) SetMemBytes(v float64) *JobSampleUpsert {
	u.Set(jobsample.FieldMemBytes, v)
	return u
}

// UpdateMemBytes sets the "mem_bytes" field to the value that was provided on create.
func (u *JobSampleUpsert) UpdateMemBytes() *JobSampleUpsert {
	u.SetExcluded(jobsample.FieldMemBytes)
	return u
}

// AddMemBytes adds v to the "mem_bytes" field.
func (u *JobSampleUpsert) AddMemBytes(v float64) *JobSampleUpsert {
	u.Add(jobsample.FieldMemBytes, v)
	return u
}

// SetSamples sets the "samples" field.
func (u *JobSampleUpsert) SetSamples(v int) *JobSampleUpsert {
	u.Set(jobsample.FieldSamples, v)
	return u
}

// UpdateSamples sets the "samples" field to the value that was provided on create.
func (u *JobSampleUpsert) UpdateSamples() *JobSampleUpsert {
	u.SetExcluded(jobsample.FieldSamples)
	return u
}

// AddSamples adds v to the "samples" field.
func (u *JobSampleUpsert) AddSamples(v int) *JobSampleUpsert {
	u.Add(jobsample.FieldSamples, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.JobSample.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *JobSampleUpsertOne) UpdateNewValues() *JobSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.JobSample.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *JobSampleUpsertOne) Ignore() *JobSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *JobSampleUpsertOne) DoNothing() *JobSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the JobSampleCreate.OnConflict
// documentation for more info.
func (u *JobSampleUpsertOne) Update(set func(*JobSampleUpsert)) *JobSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&JobSampleUpsert{UpdateSet: update})
	}))
	return u
}

// SetJobID sets the "job_id" field.
func (u *JobSampleUpsertOne) SetJobID(v int) *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.SetJobID(v)
	})
}

// AddJobID adds v to the "job_id" field.
func (u *JobSampleUpsertOne) AddJobID(v int) *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.AddJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *JobSampleUpsertOne) UpdateJobID() *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.UpdateJobID()
	})
}

// SetTs sets the "ts" field.
func (u *JobSampleUpsertOne) SetTs(v int64) *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *JobSampleUpsertOne) AddTs(v int64) *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *JobSampleUpsertOne) UpdateTs() *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.UpdateTs()
	})
}

// SetCPUCores sets the "cpu_cores" field.
func (u *JobSampleUpsertOne) SetCPUCores(v float64) *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.SetCPUCores(v)
	})
}

// AddCPUCores adds v to the "cpu_cores" field.
func (u *JobSampleUpsertOne) AddCPUCores(v float64) *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.AddCPUCores(v)
	})
}

// UpdateCPUCores sets the "cpu_cores" field to the value that was provided on create.
func (u *JobSampleUpsertOne) UpdateCPUCores() *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.UpdateCPUCores()
	})
}

// SetMemBytes sets the "mem_bytes" field.
func (u *JobSampleUpsertOne) SetMemBytes(v float64) *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.SetMemBytes(v)
	})
}

// AddMemBytes adds v to the "mem_bytes" field.
func (u *JobSampleUpsertOne) AddMemBytes(v float64) *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.AddMemBytes(v)
	})
}

// UpdateMemBytes sets the "mem_bytes" field to the value that was provided on create.
func (u *JobSampleUpsertOne) UpdateMemBytes() *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.UpdateMemBytes()
	})
}

// SetSamples sets the "samples" field.
func (u *JobSampleUpsertOne) SetSamples(v int) *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.SetSamples(v)
	})
}

// AddSamples adds v to the "samples" field.
func (u *JobSampleUpsertOne) AddSamples(v int) *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.AddSamples(v)
	})
}

// UpdateSamples sets the "samples" field to the value that was provided on create.
func (u *JobSampleUpsertOne) UpdateSamples() *JobSampleUpsertOne {
	return u.Update(func(s *JobSampleUpsert) {
		s.UpdateSamples()
	})
}

// Exec executes the query.
func (u *JobSampleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for JobSampleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *JobSampleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *JobSampleUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *JobSampleUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// JobSampleCreateBulk is the builder for creating many JobSample entities in bulk.
type JobSampleCreateBulk struct {
	config
	err      error
	builders []*JobSampleCreate
	conflict []sql.ConflictOption
}

// Save creates the JobSample entities in the database.
func (_c *JobSampleCreateBulk) Save(ctx context.Context) ([]*JobSample, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*JobSample, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobSampleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JobSampleCreateBulk) SaveX(ctx context.Context) []*JobSample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobSampleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobSampleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.JobSample.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.JobSampleUpsert) {
//			SetJobID(v+v).
//		}).
//		Exec(ctx)
func (_c *JobSampleCreateBulk) OnConflict(opts ...sql.ConflictOption) *JobSampleUpsertBulk {
	_c.conflict = opts
	return &JobSampleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.JobSample.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *JobSampleCreateBulk) OnConflictColumns(columns ...string) *JobSampleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &JobSampleUpsertBulk{
		create: _c,
	}
}

// JobSampleUpsertBulk is the builder for "upsert"-ing
// a bulk of JobSample nodes.
type JobSampleUpsertBulk struct {
	create *JobSampleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.JobSample.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *JobSampleUpsertBulk) UpdateNewValues() *JobSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.JobSample.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *JobSampleUpsertBulk) Ignore() *JobSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *JobSampleUpsertBulk) DoNothing() *JobSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the JobSampleCreateBulk.OnConflict
// documentation for more info.
func (u *JobSampleUpsertBulk) Update(set func(*JobSampleUpsert)) *JobSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&JobSampleUpsert{UpdateSet: update})
	}))
	return u
}

// SetJobID sets the "job_id" field.
func (u *JobSampleUpsertBulk) SetJobID(v int) *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.SetJobID(v)
	})
}

// AddJobID adds v to the "job_id" field.
func (u *JobSampleUpsertBulk) AddJobID(v int) *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.AddJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *JobSampleUpsertBulk) UpdateJobID() *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.UpdateJobID()
	})
}

// SetTs sets the "ts" field.
func (u *JobSampleUpsertBulk) SetTs(v int64) *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *JobSampleUpsertBulk) AddTs(v int64) *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *JobSampleUpsertBulk) UpdateTs() *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.UpdateTs()
	})
}

// SetCPUCores sets the "cpu_cores" field.
func (u *JobSampleUpsertBulk) SetCPUCores(v float64) *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.SetCPUCores(v)
	})
}

// AddCPUCores adds v to the "cpu_cores" field.
func (u *JobSampleUpsertBulk) AddCPUCores(v float64) *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.AddCPUCores(v)
	})
}

// UpdateCPUCores sets the "cpu_cores" field to the value that was provided on create.
func (u *JobSampleUpsertBulk) UpdateCPUCores() *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.UpdateCPUCores()
	})
}

// SetMemBytes sets the "mem_bytes" field.
func (u *JobSampleUpsertBulk) SetMemBytes(v float64) *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.SetMemBytes(v)
	})
}

// AddMemBytes adds v to the "mem_bytes" field.
func (u *JobSampleUpsertBulk) AddMemBytes(v float64) *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.AddMemBytes(v)
	})
}

// UpdateMemBytes sets the "mem_bytes" field to the value that was provided on create.
func (u *JobSampleUpsertBulk) UpdateMemBytes() *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.UpdateMemBytes()
	})
}

// SetSamples sets the "samples" field.
func (u *JobSampleUpsertBulk) SetSamples(v int) *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.SetSamples(v)
	})
}

// AddSamples adds v to the "samples" field.
func (u *JobSampleUpsertBulk) AddSamples(v int) *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.AddSamples(v)
	})
}

// UpdateSamples sets the "samples" field to the value that was provided on create.
func (u *JobSampleUpsertBulk) UpdateSamples() *JobSampleUpsertBulk {
	return u.Update(func(s *JobSampleUpsert) {
		s.UpdateSamples()
	})
}

// Exec executes the query.
func (u *JobSampleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the JobSampleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for JobSampleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *JobSampleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
