// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/churnevent"
	"arc-ui/internal/store/ent/jobobservation"
	"arc-ui/internal/store/ent/phasetransition"
	"arc-ui/internal/store/ent/predicate"
	"arc-ui/internal/store/ent/sample"
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeChurnEvent      = "ChurnEvent"
	TypeJobObservation  = "JobObservation"
	TypePhaseTransition = "PhaseTransition"
	TypeSample          = "Sample"
)

// ChurnEventMutation represents an operation that mutates the ChurnEvent nodes in the graph.
type ChurnEventMutation struct {
	config
	op            Op
	typ           string
	id            *int
	runner_name   *string
	set_name      *string
	kind          *string
	ts            *int64
	addts         *int64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ChurnEvent, error)
	predicates    []predicate.ChurnEvent
}

var _ ent.Mutation = (*ChurnEventMutation)(nil)

// churneventOption allows management of the mutation configuration using functional options.
type churneventOption func(*ChurnEventMutation)

// newChurnEventMutation creates new mutation for the ChurnEvent entity.
func newChurnEventMutation(c config, op Op, opts ...churneventOption) *ChurnEventMutation {
	m := &ChurnEventMutation{
		config:        c,
		op:            op,
		typ:           TypeChurnEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withChurnEventID sets the ID field of the mutation.
func withChurnEventID(id int) churneventOption {
	return func(m *ChurnEventMutation) {
		var (
			err   error
			once  sync.Once
			value *ChurnEvent
		)
		m.oldValue = func(ctx context.Context) (*ChurnEvent, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ChurnEvent.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withChurnEvent sets the old ChurnEvent of the mutation.
func withChurnEvent(node *ChurnEvent) churneventOption {
	return func(m *ChurnEventMutation) {
		m.oldValue = func(context.Context) (*ChurnEvent, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ChurnEventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ChurnEventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ChurnEventMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ChurnEventMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ChurnEvent.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetRunnerName sets the "runner_name" field.
func (m *ChurnEventMutation) SetRunnerName(s string) {
	m.runner_name = &s
}

// RunnerName returns the value of the "runner_name" field in the mutation.
func (m *ChurnEventMutation) RunnerName() (r string, exists bool) {
	v := m.runner_name
	if v == nil {
		return
	}
	return *v, true
}

// OldRunnerName returns the old "runner_name" field's value of the ChurnEvent entity.
// If the ChurnEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ChurnEventMutation) OldRunnerName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRunnerName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRunnerName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRunnerName: %w", err)
	}
	return oldValue.RunnerName, nil
}

// ResetRunnerName resets all changes to the "runner_name" field.
func (m *ChurnEventMutation) ResetRunnerName() {
	m.runner_name = nil
}

// SetSetName sets the "set_name" field.
func (m *ChurnEventMutation) SetSetName(s string) {
	m.set_name = &s
}

// SetName returns the value of the "set_name" field in the mutation.
func (m *ChurnEventMutation) SetName() (r string, exists bool) {
	v := m.set_name
	if v == nil {
		return
	}
	return *v, true
}

// OldSetName returns the old "set_name" field's value of the ChurnEvent entity.
// If the ChurnEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ChurnEventMutation) OldSetName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSetName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSetName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSetName: %w", err)
	}
	return oldValue.SetName, nil
}

// ResetSetName resets all changes to the "set_name" field.
func (m *ChurnEventMutation) ResetSetName() {
	m.set_name = nil
}

// SetKind sets the "kind" field.
func (m *ChurnEventMutation) SetKind(s string) {
	m.kind = &s
}

// Kind returns the value of the "kind" field in the mutation.
func (m *ChurnEventMutation) Kind() (r string, exists bool) {
	v := m.kind
	if v == nil {
		return
	}
	return *v, true
}

// OldKind returns the old "kind" field's value of the ChurnEvent entity.
// If the ChurnEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ChurnEventMutation) OldKind(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKind is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKind requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKind: %w", err)
	}
	return oldValue.Kind, nil
}

// ResetKind resets all changes to the "kind" field.
func (m *ChurnEventMutation) ResetKind() {
	m.kind = nil
}

// SetTs sets the "ts" field.
func (m *ChurnEventMutation) SetTs(i int64) {
	m.ts = &i
	m.addts = nil
}

// Ts returns the value of the "ts" field in the mutation.
func (m *ChurnEventMutation) Ts() (r int64, exists bool) {
	v := m.ts
	if v == nil {
		return
	}
	return *v, true
}

// OldTs returns the old "ts" field's value of the ChurnEvent entity.
// If the ChurnEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ChurnEventMutation) OldTs(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTs: %w", err)
	}
	return oldValue.Ts, nil
}

// AddTs adds i to the "ts" field.
func (m *ChurnEventMutation) AddTs(i int64) {
	if m.addts != nil {
		*m.addts += i
	} else {
		m.addts = &i
	}
}

// AddedTs returns the value that was added to the "ts" field in this mutation.
func (m *ChurnEventMutation) AddedTs() (r int64, exists bool) {
	v := m.addts
	if v == nil {
		return
	}
	return *v, true
}

// ResetTs resets all changes to the "ts" field.
func (m *ChurnEventMutation) ResetTs() {
	m.ts = nil
	m.addts = nil
}

// Where appends a list predicates to the ChurnEventMutation builder.
func (m *ChurnEventMutation) Where(ps ...predicate.ChurnEvent) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ChurnEventMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ChurnEventMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ChurnEvent, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ChurnEventMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ChurnEventMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ChurnEvent).
func (m *ChurnEventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ChurnEventMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.runner_name != nil {
		fields = append(fields, churnevent.FieldRunnerName)
	}
	if m.set_name != nil {
		fields = append(fields, churnevent.FieldSetName)
	}
	if m.kind != nil {
		fields = append(fields, churnevent.FieldKind)
	}
	if m.ts != nil {
		fields = append(fields, churnevent.FieldTs)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ChurnEventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case churnevent.FieldRunnerName:
		return m.RunnerName()
	case churnevent.FieldSetName:
		return m.SetName()
	case churnevent.FieldKind:
		return m.Kind()
	case churnevent.FieldTs:
		return m.Ts()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ChurnEventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case churnevent.FieldRunnerName:
		return m.OldRunnerName(ctx)
	case churnevent.FieldSetName:
		return m.OldSetName(ctx)
	case churnevent.FieldKind:
		return m.OldKind(ctx)
	case churnevent.FieldTs:
		return m.OldTs(ctx)
	}
	return nil, fmt.Errorf("unknown ChurnEvent field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ChurnEventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case churnevent.FieldRunnerName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRunnerName(v)
		return nil
	case churnevent.FieldSetName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSetName(v)
		return nil
	case churnevent.FieldKind:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKind(v)
		return nil
	case churnevent.FieldTs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTs(v)
		return nil
	}
	return fmt.Errorf("unknown ChurnEvent field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ChurnEventMutation) AddedFields() []string {
	var fields []string
	if m.addts != nil {
		fields = append(fields, churnevent.FieldTs)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ChurnEventMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case churnevent.FieldTs:
		return m.AddedTs()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ChurnEventMutation) AddField(name string, value ent.Value) error {
	switch name {
	case churnevent.FieldTs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTs(v)
		return nil
	}
	return fmt.Errorf("unknown ChurnEvent numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ChurnEventMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ChurnEventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ChurnEventMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ChurnEvent nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ChurnEventMutation) ResetField(name string) error {
	switch name {
	case churnevent.FieldRunnerName:
		m.ResetRunnerName()
		return nil
	case churnevent.FieldSetName:
		m.ResetSetName()
		return nil
	case churnevent.FieldKind:
		m.ResetKind()
		return nil
	case churnevent.FieldTs:
		m.ResetTs()
		return nil
	}
	return fmt.Errorf("unknown ChurnEvent field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ChurnEventMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ChurnEventMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ChurnEventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ChurnEventMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ChurnEventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ChurnEventMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ChurnEventMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ChurnEvent unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ChurnEventMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ChurnEvent edge %s", name)
}

// JobObservationMutation represents an operation that mutates the JobObservation nodes in the graph.
type JobObservationMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int
	runner_name         *string
	set_name            *string
	repository          *string
	workflow            *string
	job_name            *string
	run_id              *int64
	addrun_id           *int64
	started_at          *int64
	addstarted_at       *int64
	finished_at         *int64
	addfinished_at      *int64
	succeeded           *bool
	cpu_seconds         *float64
	addcpu_seconds      *float64
	mem_byte_seconds    *float64
	addmem_byte_seconds *float64
	clearedFields       map[string]struct{}
	done                bool
	oldValue            func(context.Context) (*JobObservation, error)
	predicates          []predicate.JobObservation
}

var _ ent.Mutation = (*JobObservationMutation)(nil)

// jobobservationOption allows management of the mutation configuration using functional options.
type jobobservationOption func(*JobObservationMutation)

// newJobObservationMutation creates new mutation for the JobObservation entity.
func newJobObservationMutation(c config, op Op, opts ...jobobservationOption) *JobObservationMutation {
	m := &JobObservationMutation{
		config:        c,
		op:            op,
		typ:           TypeJobObservation,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withJobObservationID sets the ID field of the mutation.
func withJobObservationID(id int) jobobservationOption {
	return func(m *JobObservationMutation) {
		var (
			err   error
			once  sync.Once
			value *JobObservation
		)
		m.oldValue = func(ctx context.Context) (*JobObservation, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().JobObservation.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withJobObservation sets the old JobObservation of the mutation.
func withJobObservation(node *JobObservation) jobobservationOption {
	return func(m *JobObservationMutation) {
		m.oldValue = func(context.Context) (*JobObservation, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m JobObservationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m JobObservationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *JobObservationMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *JobObservationMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().JobObservation.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetRunnerName sets the "runner_name" field.
func (m *JobObservationMutation) SetRunnerName(s string) {
	m.runner_name = &s
}

// RunnerName returns the value of the "runner_name" field in the mutation.
func (m *JobObservationMutation) RunnerName() (r string, exists bool) {
	v := m.runner_name
	if v == nil {
		return
	}
	return *v, true
}

// OldRunnerName returns the old "runner_name" field's value of the JobObservation entity.
// If the JobObservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobObservationMutation) OldRunnerName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRunnerName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRunnerName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRunnerName: %w", err)
	}
	return oldValue.RunnerName, nil
}

// ResetRunnerName resets all changes to the "runner_name" field.
func (m *JobObservationMutation) ResetRunnerName() {
	m.runner_name = nil
}

// SetSetName sets the "set_name" field.
func (m *JobObservationMutation) SetSetName(s string) {
	m.set_name = &s
}

// SetName returns the value of the "set_name" field in the mutation.
func (m *JobObservationMutation) SetName() (r string, exists bool) {
	v := m.set_name
	if v == nil {
		return
	}
	return *v, true
}

// OldSetName returns the old "set_name" field's value of the JobObservation entity.
// If the JobObservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobObservationMutation) OldSetName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSetName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSetName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSetName: %w", err)
	}
	return oldValue.SetName, nil
}

// ResetSetName resets all changes to the "set_name" field.
func (m *JobObservationMutation) ResetSetName() {
	m.set_name = nil
}

// SetRepository sets the "repository" field.
func (m *JobObservationMutation) SetRepository(s string) {
	m.repository = &s
}

// Repository returns the value of the "repository" field in the mutation.
func (m *JobObservationMutation) Repository() (r string, exists bool) {
	v := m.repository
	if v == nil {
		return
	}
	return *v, true
}

// OldRepository returns the old "repository" field's value of the JobObservation entity.
// If the JobObservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobObservationMutation) OldRepository(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRepository is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRepository requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRepository: %w", err)
	}
	return oldValue.Repository, nil
}

// ResetRepository resets all changes to the "repository" field.
func (m *JobObservationMutation) ResetRepository() {
	m.repository = nil
}

// SetWorkflow sets the "workflow" field.
func (m *JobObservationMutation) SetWorkflow(s string) {
	m.workflow = &s
}

// Workflow returns the value of the "workflow" field in the mutation.
func (m *JobObservationMutation) Workflow() (r string, exists bool) {
	v := m.workflow
	if v == nil {
		return
	}
	return *v, true
}

// OldWorkflow returns the old "workflow" field's value of the JobObservation entity.
// If the JobObservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobObservationMutation) OldWorkflow(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWorkflow is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWorkflow requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWorkflow: %w", err)
	}
	return oldValue.Workflow, nil
}

// ResetWorkflow resets all changes to the "workflow" field.
func (m *JobObservationMutation) ResetWorkflow() {
	m.workflow = nil
}

// SetJobName sets the "job_name" field.
func (m *JobObservationMutation) SetJobName(s string) {
	m.job_name = &s
}

// JobName returns the value of the "job_name" field in the mutation.
func (m *JobObservationMutation) JobName() (r string, exists bool) {
	v := m.job_name
	if v == nil {
		return
	}
	return *v, true
}

// OldJobName returns the old "job_name" field's value of the JobObservation entity.
// If the JobObservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobObservationMutation) OldJobName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldJobName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldJobName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldJobName: %w", err)
	}
	return oldValue.JobName, nil
}

// ResetJobName resets all changes to the "job_name" field.
func (m *JobObservationMutation) ResetJobName() {
	m.job_name = nil
}

// SetRunID sets the "run_id" field.
func (m *JobObservationMutation) SetRunID(i int64) {
	m.run_id = &i
	m.addrun_id = nil
}

// RunID returns the value of the "run_id" field in the mutation.
func (m *JobObservationMutation) RunID() (r int64, exists bool) {
	v := m.run_id
	if v == nil {
		return
	}
	return *v, true
}

// OldRunID returns the old "run_id" field's value of the JobObservation entity.
// If the JobObservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobObservationMutation) OldRunID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRunID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRunID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRunID: %w", err)
	}
	return oldValue.RunID, nil
}

// AddRunID adds i to the "run_id" field.
func (m *JobObservationMutation) AddRunID(i int64) {
	if m.addrun_id != nil {
		*m.addrun_id += i
	} else {
		m.addrun_id = &i
	}
}

// AddedRunID returns the value that was added to the "run_id" field in this mutation.
func (m *JobObservationMutation) AddedRunID() (r int64, exists bool) {
	v := m.addrun_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetRunID resets all changes to the "run_id" field.
func (m *JobObservationMutation) ResetRunID() {
	m.run_id = nil
	m.addrun_id = nil
}

// SetStartedAt sets the "started_at" field.
func (m *JobObservationMutation) SetStartedAt(i int64) {
	m.started_at = &i
	m.addstarted_at = nil
}

// StartedAt returns the value of the "started_at" field in the mutation.
func (m *JobObservationMutation) StartedAt() (r int64, exists bool) {
	v := m.started_at
	if v == nil {
		return
	}
	return *v, true
}

// OldStartedAt returns the old "started_at" field's value of the JobObservation entity.
// If the JobObservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobObservationMutation) OldStartedAt(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartedAt: %w", err)
	}
	return oldValue.StartedAt, nil
}

// AddStartedAt adds i to the "started_at" field.
func (m *JobObservationMutation) AddStartedAt(i int64) {
	if m.addstarted_at != nil {
		*m.addstarted_at += i
	} else {
		m.addstarted_at = &i
	}
}

// AddedStartedAt returns the value that was added to the "started_at" field in this mutation.
func (m *JobObservationMutation) AddedStartedAt() (r int64, exists bool) {
	v := m.addstarted_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetStartedAt resets all changes to the "started_at" field.
func (m *JobObservationMutation) ResetStartedAt() {
	m.started_at = nil
	m.addstarted_at = nil
}

// SetFinishedAt sets the "finished_at" field.
func (m *JobObservationMutation) SetFinishedAt(i int64) {
	m.finished_at = &i
	m.addfinished_at = nil
}

// FinishedAt returns the value of the "finished_at" field in the mutation.
func (m *JobObservationMutation) FinishedAt() (r int64, exists bool) {
	v := m.finished_at
	if v == nil {
		return
	}
	return *v, true
}

// OldFinishedAt returns the old "finished_at" field's value of the JobObservation entity.
// If the JobObservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobObservationMutation) OldFinishedAt(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFinishedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFinishedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFinishedAt: %w", err)
	}
	return oldValue.FinishedAt, nil
}

// AddFinishedAt adds i to the "finished_at" field.
func (m *JobObservationMutation) AddFinishedAt(i int64) {
	if m.addfinished_at != nil {
		*m.addfinished_at += i
	} else {
		m.addfinished_at = &i
	}
}

// AddedFinishedAt returns the value that was added to the "finished_at" field in this mutation.
func (m *JobObservationMutation) AddedFinishedAt() (r int64, exists bool) {
	v := m.addfinished_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetFinishedAt resets all changes to the "finished_at" field.
func (m *JobObservationMutation) ResetFinishedAt() {
	m.finished_at = nil
	m.addfinished_at = nil
}

// SetSucceeded sets the "succeeded" field.
func (m *JobObservationMutation) SetSucceeded(b bool) {
	m.succeeded = &b
}

// Succeeded returns the value of the "succeeded" field in the mutation.
func (m *JobObservationMutation) Succeeded() (r bool, exists bool) {
	v := m.succeeded
	if v == nil {
		return
	}
	return *v, true
}

// OldSucceeded returns the old "succeeded" field's value of the JobObservation entity.
// If the JobObservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobObservationMutation) OldSucceeded(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSucceeded is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSucceeded requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSucceeded: %w", err)
	}
	return oldValue.Succeeded, nil
}

// ResetSucceeded resets all changes to the "succeeded" field.
func (m *JobObservationMutation) ResetSucceeded() {
	m.succeeded = nil
}

// SetCPUSeconds sets the "cpu_seconds" field.
func (m *JobObservationMutation) SetCPUSeconds(f float64) {
	m.cpu_seconds = &f
	m.addcpu_seconds = nil
}

// CPUSeconds returns the value of the "cpu_seconds" field in the mutation.
func (m *JobObservationMutation) CPUSeconds() (r float64, exists bool) {
	v := m.cpu_seconds
	if v == nil {
		return
	}
	return *v, true
}

// OldCPUSeconds returns the old "cpu_seconds" field's value of the JobObservation entity.
// If the JobObservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobObservationMutation) OldCPUSeconds(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCPUSeconds is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCPUSeconds requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCPUSeconds: %w", err)
	}
	return oldValue.CPUSeconds, nil
}

// AddCPUSeconds adds f to the "cpu_seconds" field.
func (m *JobObservationMutation) AddCPUSeconds(f float64) {
	if m.addcpu_seconds != nil {
		*m.addcpu_seconds += f
	} else {
		m.addcpu_seconds = &f
	}
}

// AddedCPUSeconds returns the value that was added to the "cpu_seconds" field in this mutation.
func (m *JobObservationMutation) AddedCPUSeconds() (r float64, exists bool) {
	v := m.addcpu_seconds
	if v == nil {
		return
	}
	return *v, true
}

// ResetCPUSeconds resets all changes to the "cpu_seconds" field.
func (m *JobObservationMutation) ResetCPUSeconds() {
	m.cpu_seconds = nil
	m.addcpu_seconds = nil
}

// SetMemByteSeconds sets the "mem_byte_seconds" field.
func (m *JobObservationMutation) SetMemByteSeconds(f float64) {
	m.mem_byte_seconds = &f
	m.addmem_byte_seconds = nil
}

// MemByteSeconds returns the value of the "mem_byte_seconds" field in the mutation.
func (m *JobObservationMutation) MemByteSeconds() (r float64, exists bool) {
	v := m.mem_byte_seconds
	if v == nil {
		return
	}
	return *v, true
}

// OldMemByteSeconds returns the old "mem_byte_seconds" field's value of the JobObservation entity.
// If the JobObservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobObservationMutation) OldMemByteSeconds(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMemByteSeconds is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMemByteSeconds requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMemByteSeconds: %w", err)
	}
	return oldValue.MemByteSeconds, nil
}

// AddMemByteSeconds adds f to the "mem_byte_seconds" field.
func (m *JobObservationMutation) AddMemByteSeconds(f float64) {
	if m.addmem_byte_seconds != nil {
		*m.addmem_byte_seconds += f
	} else {
		m.addmem_byte_seconds = &f
	}
}

// AddedMemByteSeconds returns the value that was added to the "mem_byte_seconds" field in this mutation.
func (m *JobObservationMutation) AddedMemByteSeconds() (r float64, exists bool) {
	v := m.addmem_byte_seconds
	if v == nil {
		return
	}
	return *v, true
}

// ResetMemByteSeconds resets all changes to the "mem_byte_seconds" field.
func (m *JobObservationMutation) ResetMemByteSeconds() {
	m.mem_byte_seconds = nil
	m.addmem_byte_seconds = nil
}

// Where appends a list predicates to the JobObservationMutation builder.
func (m *JobObservationMutation) Where(ps ...predicate.JobObservation) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the JobObservationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *JobObservationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.JobObservation, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *JobObservationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *JobObservationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (JobObservation).
func (m *JobObservationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *JobObservationMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.runner_name != nil {
		fields = append(fields, jobobservation.FieldRunnerName)
	}
	if m.set_name != nil {
		fields = append(fields, jobobservation.FieldSetName)
	}
	if m.repository != nil {
		fields = append(fields, jobobservation.FieldRepository)
	}
	if m.workflow != nil {
		fields = append(fields, jobobservation.FieldWorkflow)
	}
	if m.job_name != nil {
		fields = append(fields, jobobservation.FieldJobName)
	}
	if m.run_id != nil {
		fields = append(fields, jobobservation.FieldRunID)
	}
	if m.started_at != nil {
		fields = append(fields, jobobservation.FieldStartedAt)
	}
	if m.finished_at != nil {
		fields = append(fields, jobobservation.FieldFinishedAt)
	}
	if m.succeeded != nil {
		fields = append(fields, jobobservation.FieldSucceeded)
	}
	if m.cpu_seconds != nil {
		fields = append(fields, jobobservation.FieldCPUSeconds)
	}
	if m.mem_byte_seconds != nil {
		fields = append(fields, jobobservation.FieldMemByteSeconds)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *JobObservationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case jobobservation.FieldRunnerName:
		return m.RunnerName()
	case jobobservation.FieldSetName:
		return m.SetName()
	case jobobservation.FieldRepository:
		return m.Repository()
	case jobobservation.FieldWorkflow:
		return m.Workflow()
	case jobobservation.FieldJobName:
		return m.JobName()
	case jobobservation.FieldRunID:
		return m.RunID()
	case jobobservation.FieldStartedAt:
		return m.StartedAt()
	case jobobservation.FieldFinishedAt:
		return m.FinishedAt()
	case jobobservation.FieldSucceeded:
		return m.Succeeded()
	case jobobservation.FieldCPUSeconds:
		return m.CPUSeconds()
	case jobobservation.FieldMemByteSeconds:
		return m.MemByteSeconds()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *JobObservationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case jobobservation.FieldRunnerName:
		return m.OldRunnerName(ctx)
	case jobobservation.FieldSetName:
		return m.OldSetName(ctx)
	case jobobservation.FieldRepository:
		return m.OldRepository(ctx)
	case jobobservation.FieldWorkflow:
		return m.OldWorkflow(ctx)
	case jobobservation.FieldJobName:
		return m.OldJobName(ctx)
	case jobobservation.FieldRunID:
		return m.OldRunID(ctx)
	case jobobservation.FieldStartedAt:
		return m.OldStartedAt(ctx)
	case jobobservation.FieldFinishedAt:
		return m.OldFinishedAt(ctx)
	case jobobservation.FieldSucceeded:
		return m.OldSucceeded(ctx)
	case jobobservation.FieldCPUSeconds:
		return m.OldCPUSeconds(ctx)
	case jobobservation.FieldMemByteSeconds:
		return m.OldMemByteSeconds(ctx)
	}
	return nil, fmt.Errorf("unknown JobObservation field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *JobObservationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case jobobservation.FieldRunnerName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRunnerName(v)
		return nil
	case jobobservation.FieldSetName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSetName(v)
		return nil
	case jobobservation.FieldRepository:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRepository(v)
		return nil
	case jobobservation.FieldWorkflow:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorkflow(v)
		return nil
	case jobobservation.FieldJobName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetJobName(v)
		return nil
	case jobobservation.FieldRunID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRunID(v)
		return nil
	case jobobservation.FieldStartedAt:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartedAt(v)
		return nil
	case jobobservation.FieldFinishedAt:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFinishedAt(v)
		return nil
	case jobobservation.FieldSucceeded:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSucceeded(v)
		return nil
	case jobobservation.FieldCPUSeconds:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCPUSeconds(v)
		return nil
	case jobobservation.FieldMemByteSeconds:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMemByteSeconds(v)
		return nil
	}
	return fmt.Errorf("unknown JobObservation field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *JobObservationMutation) AddedFields() []string {
	var fields []string
	if m.addrun_id != nil {
		fields = append(fields, jobobservation.FieldRunID)
	}
	if m.addstarted_at != nil {
		fields = append(fields, jobobservation.FieldStartedAt)
	}
	if m.addfinished_at != nil {
		fields = append(fields, jobobservation.FieldFinishedAt)
	}
	if m.addcpu_seconds != nil {
		fields = append(fields, jobobservation.FieldCPUSeconds)
	}
	if m.addmem_byte_seconds != nil {
		fields = append(fields, jobobservation.FieldMemByteSeconds)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *JobObservationMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case jobobservation.FieldRunID:
		return m.AddedRunID()
	case jobobservation.FieldStartedAt:
		return m.AddedStartedAt()
	case jobobservation.FieldFinishedAt:
		return m.AddedFinishedAt()
	case jobobservation.FieldCPUSeconds:
		return m.AddedCPUSeconds()
	case jobobservation.FieldMemByteSeconds:
		return m.AddedMemByteSeconds()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *JobObservationMutation) AddField(name string, value ent.Value) error {
	switch name {
	case jobobservation.FieldRunID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRunID(v)
		return nil
	case jobobservation.FieldStartedAt:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStartedAt(v)
		return nil
	case jobobservation.FieldFinishedAt:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFinishedAt(v)
		return nil
	case jobobservation.FieldCPUSeconds:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCPUSeconds(v)
		return nil
	case jobobservation.FieldMemByteSeconds:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMemByteSeconds(v)
		return nil
	}
	return fmt.Errorf("unknown JobObservation numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *JobObservationMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *JobObservationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *JobObservationMutation) ClearField(name string) error {
	return fmt.Errorf("unknown JobObservation nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *JobObservationMutation) ResetField(name string) error {
	switch name {
	case jobobservation.FieldRunnerName:
		m.ResetRunnerName()
		return nil
	case jobobservation.FieldSetName:
		m.ResetSetName()
		return nil
	case jobobservation.FieldRepository:
		m.ResetRepository()
		return nil
	case jobobservation.FieldWorkflow:
		m.ResetWorkflow()
		return nil
	case jobobservation.FieldJobName:
		m.ResetJobName()
		return nil
	case jobobservation.FieldRunID:
		m.ResetRunID()
		return nil
	case jobobservation.FieldStartedAt:
		m.ResetStartedAt()
		return nil
	case jobobservation.FieldFinishedAt:
		m.ResetFinishedAt()
		return nil
	case jobobservation.FieldSucceeded:
		m.ResetSucceeded()
		return nil
	case jobobservation.FieldCPUSeconds:
		m.ResetCPUSeconds()
		return nil
	case jobobservation.FieldMemByteSeconds:
		m.ResetMemByteSeconds()
		return nil
	}
	return fmt.Errorf("unknown JobObservation field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *JobObservationMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *JobObservationMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *JobObservationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *JobObservationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *JobObservationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *JobObservationMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *JobObservationMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown JobObservation unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *JobObservationMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown JobObservation edge %s", name)
}

// PhaseTransitionMutation represents an operation that mutates the PhaseTransition nodes in the graph.
type PhaseTransitionMutation struct {
	config
	op            Op
	typ           string
	id            *int
	runner_name   *string
	set_name      *string
	phase         *string
	started_at    *int64
	addstarted_at *int64
	ended_at      *int64
	addended_at   *int64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*PhaseTransition, error)
	predicates    []predicate.PhaseTransition
}

var _ ent.Mutation = (*PhaseTransitionMutation)(nil)

// phasetransitionOption allows management of the mutation configuration using functional options.
type phasetransitionOption func(*PhaseTransitionMutation)

// newPhaseTransitionMutation creates new mutation for the PhaseTransition entity.
func newPhaseTransitionMutation(c config, op Op, opts ...phasetransitionOption) *PhaseTransitionMutation {
	m := &PhaseTransitionMutation{
		config:        c,
		op:            op,
		typ:           TypePhaseTransition,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPhaseTransitionID sets the ID field of the mutation.
func withPhaseTransitionID(id int) phasetransitionOption {
	return func(m *PhaseTransitionMutation) {
		var (
			err   error
			once  sync.Once
			value *PhaseTransition
		)
		m.oldValue = func(ctx context.Context) (*PhaseTransition, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PhaseTransition.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPhaseTransition sets the old PhaseTransition of the mutation.
func withPhaseTransition(node *PhaseTransition) phasetransitionOption {
	return func(m *PhaseTransitionMutation) {
		m.oldValue = func(context.Context) (*PhaseTransition, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PhaseTransitionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PhaseTransitionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PhaseTransitionMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PhaseTransitionMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PhaseTransition.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetRunnerName sets the "runner_name" field.
func (m *PhaseTransitionMutation) SetRunnerName(s string) {
	m.runner_name = &s
}

// RunnerName returns the value of the "runner_name" field in the mutation.
func (m *PhaseTransitionMutation) RunnerName() (r string, exists bool) {
	v := m.runner_name
	if v == nil {
		return
	}
	return *v, true
}

// OldRunnerName returns the old "runner_name" field's value of the PhaseTransition entity.
// If the PhaseTransition object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PhaseTransitionMutation) OldRunnerName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRunnerName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRunnerName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRunnerName: %w", err)
	}
	return oldValue.RunnerName, nil
}

// ResetRunnerName resets all changes to the "runner_name" field.
func (m *PhaseTransitionMutation) ResetRunnerName() {
	m.runner_name = nil
}

// SetSetName sets the "set_name" field.
func (m *PhaseTransitionMutation) SetSetName(s string) {
	m.set_name = &s
}

// SetName returns the value of the "set_name" field in the mutation.
func (m *PhaseTransitionMutation) SetName() (r string, exists bool) {
	v := m.set_name
	if v == nil {
		return
	}
	return *v, true
}

// OldSetName returns the old "set_name" field's value of the PhaseTransition entity.
// If the PhaseTransition object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PhaseTransitionMutation) OldSetName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSetName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSetName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSetName: %w", err)
	}
	return oldValue.SetName, nil
}

// ResetSetName resets all changes to the "set_name" field.
func (m *PhaseTransitionMutation) ResetSetName() {
	m.set_name = nil
}

// SetPhase sets the "phase" field.
func (m *PhaseTransitionMutation) SetPhase(s string) {
	m.phase = &s
}

// Phase returns the value of the "phase" field in the mutation.
func (m *PhaseTransitionMutation) Phase() (r string, exists bool) {
	v := m.phase
	if v == nil {
		return
	}
	return *v, true
}

// OldPhase returns the old "phase" field's value of the PhaseTransition entity.
// If the PhaseTransition object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PhaseTransitionMutation) OldPhase(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPhase is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPhase requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPhase: %w", err)
	}
	return oldValue.Phase, nil
}

// ResetPhase resets all changes to the "phase" field.
func (m *PhaseTransitionMutation) ResetPhase() {
	m.phase = nil
}

// SetStartedAt sets the "started_at" field.
func (m *PhaseTransitionMutation) SetStartedAt(i int64) {
	m.started_at = &i
	m.addstarted_at = nil
}

// StartedAt returns the value of the "started_at" field in the mutation.
func (m *PhaseTransitionMutation) StartedAt() (r int64, exists bool) {
	v := m.started_at
	if v == nil {
		return
	}
	return *v, true
}

// OldStartedAt returns the old "started_at" field's value of the PhaseTransition entity.
// If the PhaseTransition object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PhaseTransitionMutation) OldStartedAt(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartedAt: %w", err)
	}
	return oldValue.StartedAt, nil
}

// AddStartedAt adds i to the "started_at" field.
func (m *PhaseTransitionMutation) AddStartedAt(i int64) {
	if m.addstarted_at != nil {
		*m.addstarted_at += i
	} else {
		m.addstarted_at = &i
	}
}

// AddedStartedAt returns the value that was added to the "started_at" field in this mutation.
func (m *PhaseTransitionMutation) AddedStartedAt() (r int64, exists bool) {
	v := m.addstarted_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetStartedAt resets all changes to the "started_at" field.
func (m *PhaseTransitionMutation) ResetStartedAt() {
	m.started_at = nil
	m.addstarted_at = nil
}

// SetEndedAt sets the "ended_at" field.
func (m *PhaseTransitionMutation) SetEndedAt(i int64) {
	m.ended_at = &i
	m.addended_at = nil
}

// EndedAt returns the value of the "ended_at" field in the mutation.
func (m *PhaseTransitionMutation) EndedAt() (r int64, exists bool) {
	v := m.ended_at
	if v == nil {
		return
	}
	return *v, true
}

// OldEndedAt returns the old "ended_at" field's value of the PhaseTransition entity.
// If the PhaseTransition object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PhaseTransitionMutation) OldEndedAt(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEndedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEndedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEndedAt: %w", err)
	}
	return oldValue.EndedAt, nil
}

// AddEndedAt adds i to the "ended_at" field.
func (m *PhaseTransitionMutation) AddEndedAt(i int64) {
	if m.addended_at != nil {
		*m.addended_at += i
	} else {
		m.addended_at = &i
	}
}

// AddedEndedAt returns the value that was added to the "ended_at" field in this mutation.
func (m *PhaseTransitionMutation) AddedEndedAt() (r int64, exists bool) {
	v := m.addended_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetEndedAt resets all changes to the "ended_at" field.
func (m *PhaseTransitionMutation) ResetEndedAt() {
	m.ended_at = nil
	m.addended_at = nil
}

// Where appends a list predicates to the PhaseTransitionMutation builder.
func (m *PhaseTransitionMutation) Where(ps ...predicate.PhaseTransition) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PhaseTransitionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PhaseTransitionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PhaseTransition, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PhaseTransitionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PhaseTransitionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PhaseTransition).
func (m *PhaseTransitionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PhaseTransitionMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.runner_name != nil {
		fields = append(fields, phasetransition.FieldRunnerName)
	}
	if m.set_name != nil {
		fields = append(fields, phasetransition.FieldSetName)
	}
	if m.phase != nil {
		fields = append(fields, phasetransition.FieldPhase)
	}
	if m.started_at != nil {
		fields = append(fields, phasetransition.FieldStartedAt)
	}
	if m.ended_at != nil {
		fields = append(fields, phasetransition.FieldEndedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PhaseTransitionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case phasetransition.FieldRunnerName:
		return m.RunnerName()
	case phasetransition.FieldSetName:
		return m.SetName()
	case phasetransition.FieldPhase:
		return m.Phase()
	case phasetransition.FieldStartedAt:
		return m.StartedAt()
	case phasetransition.FieldEndedAt:
		return m.EndedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PhaseTransitionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case phasetransition.FieldRunnerName:
		return m.OldRunnerName(ctx)
	case phasetransition.FieldSetName:
		return m.OldSetName(ctx)
	case phasetransition.FieldPhase:
		return m.OldPhase(ctx)
	case phasetransition.FieldStartedAt:
		return m.OldStartedAt(ctx)
	case phasetransition.FieldEndedAt:
		return m.OldEndedAt(ctx)
	}
	return nil, fmt.Errorf("unknown PhaseTransition field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PhaseTransitionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case phasetransition.FieldRunnerName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRunnerName(v)
		return nil
	case phasetransition.FieldSetName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSetName(v)
		return nil
	case phasetransition.FieldPhase:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPhase(v)
		return nil
	case phasetransition.FieldStartedAt:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartedAt(v)
		return nil
	case phasetransition.FieldEndedAt:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEndedAt(v)
		return nil
	}
	return fmt.Errorf("unknown PhaseTransition field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PhaseTransitionMutation) AddedFields() []string {
	var fields []string
	if m.addstarted_at != nil {
		fields = append(fields, phasetransition.FieldStartedAt)
	}
	if m.addended_at != nil {
		fields = append(fields, phasetransition.FieldEndedAt)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PhaseTransitionMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case phasetransition.FieldStartedAt:
		return m.AddedStartedAt()
	case phasetransition.FieldEndedAt:
		return m.AddedEndedAt()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PhaseTransitionMutation) AddField(name string, value ent.Value) error {
	switch name {
	case phasetransition.FieldStartedAt:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStartedAt(v)
		return nil
	case phasetransition.FieldEndedAt:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddEndedAt(v)
		return nil
	}
	return fmt.Errorf("unknown PhaseTransition numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PhaseTransitionMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PhaseTransitionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PhaseTransitionMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PhaseTransition nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PhaseTransitionMutation) ResetField(name string) error {
	switch name {
	case phasetransition.FieldRunnerName:
		m.ResetRunnerName()
		return nil
	case phasetransition.FieldSetName:
		m.ResetSetName()
		return nil
	case phasetransition.FieldPhase:
		m.ResetPhase()
		return nil
	case phasetransition.FieldStartedAt:
		m.ResetStartedAt()
		return nil
	case phasetransition.FieldEndedAt:
		m.ResetEndedAt()
		return nil
	}
	return fmt.Errorf("unknown PhaseTransition field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PhaseTransitionMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PhaseTransitionMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PhaseTransitionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PhaseTransitionMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PhaseTransitionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PhaseTransitionMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PhaseTransitionMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PhaseTransition unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PhaseTransitionMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PhaseTransition edge %s", name)
}

// SampleMutation represents an operation that mutates the Sample nodes in the graph.
type SampleMutation struct {
	config
	op            Op
	typ           string
	id            *int
	ts            *int64
	addts         *int64
	scope         *string
	scope_id      *string
	tier          *string
	metric        *string
	value         *float64
	addvalue      *float64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Sample, error)
	predicates    []predicate.Sample
}

var _ ent.Mutation = (*SampleMutation)(nil)

// sampleOption allows management of the mutation configuration using functional options.
type sampleOption func(*SampleMutation)

// newSampleMutation creates new mutation for the Sample entity.
func newSampleMutation(c config, op Op, opts ...sampleOption) *SampleMutation {
	m := &SampleMutation{
		config:        c,
		op:            op,
		typ:           TypeSample,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSampleID sets the ID field of the mutation.
func withSampleID(id int) sampleOption {
	return func(m *SampleMutation) {
		var (
			err   error
			once  sync.Once
			value *Sample
		)
		m.oldValue = func(ctx context.Context) (*Sample, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Sample.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSample sets the old Sample of the mutation.
func withSample(node *Sample) sampleOption {
	return func(m *SampleMutation) {
		m.oldValue = func(context.Context) (*Sample, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SampleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SampleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SampleMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SampleMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Sample.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTs sets the "ts" field.
func (m *SampleMutation) SetTs(i int64) {
	m.ts = &i
	m.addts = nil
}

// Ts returns the value of the "ts" field in the mutation.
func (m *SampleMutation) Ts() (r int64, exists bool) {
	v := m.ts
	if v == nil {
		return
	}
	return *v, true
}

// OldTs returns the old "ts" field's value of the Sample entity.
// If the Sample object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SampleMutation) OldTs(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTs: %w", err)
	}
	return oldValue.Ts, nil
}

// AddTs adds i to the "ts" field.
func (m *SampleMutation) AddTs(i int64) {
	if m.addts != nil {
		*m.addts += i
	} else {
		m.addts = &i
	}
}

// AddedTs returns the value that was added to the "ts" field in this mutation.
func (m *SampleMutation) AddedTs() (r int64, exists bool) {
	v := m.addts
	if v == nil {
		return
	}
	return *v, true
}

// ResetTs resets all changes to the "ts" field.
func (m *SampleMutation) ResetTs() {
	m.ts = nil
	m.addts = nil
}

// SetScope sets the "scope" field.
func (m *SampleMutation) SetScope(s string) {
	m.scope = &s
}

// Scope returns the value of the "scope" field in the mutation.
func (m *SampleMutation) Scope() (r string, exists bool) {
	v := m.scope
	if v == nil {
		return
	}
	return *v, true
}

// OldScope returns the old "scope" field's value of the Sample entity.
// If the Sample object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SampleMutation) OldScope(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScope is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScope requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScope: %w", err)
	}
	return oldValue.Scope, nil
}

// ResetScope resets all changes to the "scope" field.
func (m *SampleMutation) ResetScope() {
	m.scope = nil
}

// SetScopeID sets the "scope_id" field.
func (m *SampleMutation) SetScopeID(s string) {
	m.scope_id = &s
}

// ScopeID returns the value of the "scope_id" field in the mutation.
func (m *SampleMutation) ScopeID() (r string, exists bool) {
	v := m.scope_id
	if v == nil {
		return
	}
	return *v, true
}

// OldScopeID returns the old "scope_id" field's value of the Sample entity.
// If the Sample object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SampleMutation) OldScopeID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScopeID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScopeID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScopeID: %w", err)
	}
	return oldValue.ScopeID, nil
}

// ResetScopeID resets all changes to the "scope_id" field.
func (m *SampleMutation) ResetScopeID() {
	m.scope_id = nil
}

// SetTier sets the "tier" field.
func (m *SampleMutation) SetTier(s string) {
	m.tier = &s
}

// Tier returns the value of the "tier" field in the mutation.
func (m *SampleMutation) Tier() (r string, exists bool) {
	v := m.tier
	if v == nil {
		return
	}
	return *v, true
}

// OldTier returns the old "tier" field's value of the Sample entity.
// If the Sample object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SampleMutation) OldTier(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTier is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTier requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTier: %w", err)
	}
	return oldValue.Tier, nil
}

// ResetTier resets all changes to the "tier" field.
func (m *SampleMutation) ResetTier() {
	m.tier = nil
}

// SetMetric sets the "metric" field.
func (m *SampleMutation) SetMetric(s string) {
	m.metric = &s
}

// Metric returns the value of the "metric" field in the mutation.
func (m *SampleMutation) Metric() (r string, exists bool) {
	v := m.metric
	if v == nil {
		return
	}
	return *v, true
}

// OldMetric returns the old "metric" field's value of the Sample entity.
// If the Sample object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SampleMutation) OldMetric(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMetric is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMetric requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMetric: %w", err)
	}
	return oldValue.Metric, nil
}

// ResetMetric resets all changes to the "metric" field.
func (m *SampleMutation) ResetMetric() {
	m.metric = nil
}

// SetValue sets the "value" field.
func (m *SampleMutation) SetValue(f float64) {
	m.value = &f
	m.addvalue = nil
}

// Value returns the value of the "value" field in the mutation.
func (m *SampleMutation) Value() (r float64, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// OldValue returns the old "value" field's value of the Sample entity.
// If the Sample object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SampleMutation) OldValue(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue: %w", err)
	}
	return oldValue.Value, nil
}

// AddValue adds f to the "value" field.
func (m *SampleMutation) AddValue(f float64) {
	if m.addvalue != nil {
		*m.addvalue += f
	} else {
		m.addvalue = &f
	}
}

// AddedValue returns the value that was added to the "value" field in this mutation.
func (m *SampleMutation) AddedValue() (r float64, exists bool) {
	v := m.addvalue
	if v == nil {
		return
	}
	return *v, true
}

// ResetValue resets all changes to the "value" field.
func (m *SampleMutation) ResetValue() {
	m.value = nil
	m.addvalue = nil
}

// Where appends a list predicates to the SampleMutation builder.
func (m *SampleMutation) Where(ps ...predicate.Sample) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SampleMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SampleMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Sample, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SampleMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SampleMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Sample).
func (m *SampleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SampleMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.ts != nil {
		fields = append(fields, sample.FieldTs)
	}
	if m.scope != nil {
		fields = append(fields, sample.FieldScope)
	}
	if m.scope_id != nil {
		fields = append(fields, sample.FieldScopeID)
	}
	if m.tier != nil {
		fields = append(fields, sample.FieldTier)
	}
	if m.metric != nil {
		fields = append(fields, sample.FieldMetric)
	}
	if m.value != nil {
		fields = append(fields, sample.FieldValue)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SampleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case sample.FieldTs:
		return m.Ts()
	case sample.FieldScope:
		return m.Scope()
	case sample.FieldScopeID:
		return m.ScopeID()
	case sample.FieldTier:
		return m.Tier()
	case sample.FieldMetric:
		return m.Metric()
	case sample.FieldValue:
		return m.Value()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SampleMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case sample.FieldTs:
		return m.OldTs(ctx)
	case sample.FieldScope:
		return m.OldScope(ctx)
	case sample.FieldScopeID:
		return m.OldScopeID(ctx)
	case sample.FieldTier:
		return m.OldTier(ctx)
	case sample.FieldMetric:
		return m.OldMetric(ctx)
	case sample.FieldValue:
		return m.OldValue(ctx)
	}
	return nil, fmt.Errorf("unknown Sample field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SampleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case sample.FieldTs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTs(v)
		return nil
	case sample.FieldScope:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScope(v)
		return nil
	case sample.FieldScopeID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScopeID(v)
		return nil
	case sample.FieldTier:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTier(v)
		return nil
	case sample.FieldMetric:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMetric(v)
		return nil
	case sample.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	}
	return fmt.Errorf("unknown Sample field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SampleMutation) AddedFields() []string {
	var fields []string
	if m.addts != nil {
		fields = append(fields, sample.FieldTs)
	}
	if m.addvalue != nil {
		fields = append(fields, sample.FieldValue)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SampleMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case sample.FieldTs:
		return m.AddedTs()
	case sample.FieldValue:
		return m.AddedValue()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SampleMutation) AddField(name string, value ent.Value) error {
	switch name {
	case sample.FieldTs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTs(v)
		return nil
	case sample.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddValue(v)
		return nil
	}
	return fmt.Errorf("unknown Sample numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SampleMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SampleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SampleMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Sample nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SampleMutation) ResetField(name string) error {
	switch name {
	case sample.FieldTs:
		m.ResetTs()
		return nil
	case sample.FieldScope:
		m.ResetScope()
		return nil
	case sample.FieldScopeID:
		m.ResetScopeID()
		return nil
	case sample.FieldTier:
		m.ResetTier()
		return nil
	case sample.FieldMetric:
		m.ResetMetric()
		return nil
	case sample.FieldValue:
		m.ResetValue()
		return nil
	}
	return fmt.Errorf("unknown Sample field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SampleMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SampleMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SampleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SampleMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SampleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SampleMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SampleMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Sample unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SampleMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Sample edge %s", name)
}
