// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/phasetransition"
	"arc-ui/internal/store/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PhaseTransitionUpdate is the builder for updating PhaseTransition entities.
type PhaseTransitionUpdate struct {
	config
	hooks    []Hook
	mutation *PhaseTransitionMutation
}

// Where appends a list predicates to the PhaseTransitionUpdate builder.
func (_u *PhaseTransitionUpdate) Where(ps ...predicate.PhaseTransition) *PhaseTransitionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRunnerName sets the "runner_name" field.
func (_u *PhaseTransitionUpdate) SetRunnerName(v string) *PhaseTransitionUpdate {
	_u.mutation.SetRunnerName(v)
	return _u
}

// SetNillableRunnerName sets the "runner_name" field if the given value is not nil.
func (_u *PhaseTransitionUpdate) SetNillableRunnerName(v *string) *PhaseTransitionUpdate {
	if v != nil {
		_u.SetRunnerName(*v)
	}
	return _u
}

// SetSetName sets the "set_name" field.
func (_u *PhaseTransitionUpdate) SetSetName(v string) *PhaseTransitionUpdate {
	_u.mutation.SetSetName(v)
	return _u
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_u *PhaseTransitionUpdate) SetNillableSetName(v *string) *PhaseTransitionUpdate {
	if v != nil {
		_u.SetSetName(*v)
	}
	return _u
}

// SetPhase sets the "phase" field.
func (_u *PhaseTransitionUpdate) SetPhase(v string) *PhaseTransitionUpdate {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *PhaseTransitionUpdate) SetNillablePhase(v *string) *PhaseTransitionUpdate {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *PhaseTransitionUpdate) SetStartedAt(v int64) *PhaseTransitionUpdate {
	_u.mutation.ResetStartedAt()
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *PhaseTransitionUpdate) SetNillableStartedAt(v *int64) *PhaseTransitionUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// AddStartedAt adds value to the "started_at" field.
func (_u *PhaseTransitionUpdate) AddStartedAt(v int64) *PhaseTransitionUpdate {
	_u.mutation.AddStartedAt(v)
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *PhaseTransitionUpdate) SetEndedAt(v int64) *PhaseTransitionUpdate {
	_u.mutation.ResetEndedAt()
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *PhaseTransitionUpdate) SetNillableEndedAt(v *int64) *PhaseTransitionUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// AddEndedAt adds value to the "ended_at" field.
func (_u *PhaseTransitionUpdate) AddEndedAt(v int64) *PhaseTransitionUpdate {
	_u.mutation.AddEndedAt(v)
	return _u
}

// Mutation returns the PhaseTransitionMutation object of the builder.
func (_u *PhaseTransitionUpdate) Mutation() *PhaseTransitionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PhaseTransitionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PhaseTransitionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PhaseTransitionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PhaseTransitionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PhaseTransitionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(phasetransition.Table, phasetransition.Columns, sqlgraph.NewFieldSpec(phasetransition.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunnerName(); ok {
		_spec.SetField(phasetransition.FieldRunnerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SetName(); ok {
		_spec.SetField(phasetransition.FieldSetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(phasetransition.FieldPhase, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(phasetransition.FieldStartedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStartedAt(); ok {
		_spec.AddField(phasetransition.FieldStartedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(phasetransition.FieldEndedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEndedAt(); ok {
		_spec.AddField(phasetransition.FieldEndedAt, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{phasetransition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PhaseTransitionUpdateOne is the builder for updating a single PhaseTransition entity.
type PhaseTransitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PhaseTransitionMutation
}

// SetRunnerName sets the "runner_name" field.
func (_u *PhaseTransitionUpdateOne) SetRunnerName(v string) *PhaseTransitionUpdateOne {
	_u.mutation.SetRunnerName(v)
	return _u
}

// SetNillableRunnerName sets the "runner_name" field if the given value is not nil.
func (_u *PhaseTransitionUpdateOne) SetNillableRunnerName(v *string) *PhaseTransitionUpdateOne {
	if v != nil {
		_u.SetRunnerName(*v)
	}
	return _u
}

// SetSetName sets the "set_name" field.
func (_u *PhaseTransitionUpdateOne) SetSetName(v string) *PhaseTransitionUpdateOne {
	_u.mutation.SetSetName(v)
	return _u
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_u *PhaseTransitionUpdateOne) SetNillableSetName(v *string) *PhaseTransitionUpdateOne {
	if v != nil {
		_u.SetSetName(*v)
	}
	return _u
}

// SetPhase sets the "phase" field.
func (_u *PhaseTransitionUpdateOne) SetPhase(v string) *PhaseTransitionUpdateOne {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *PhaseTransitionUpdateOne) SetNillablePhase(v *string) *PhaseTransitionUpdateOne {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *PhaseTransitionUpdateOne) SetStartedAt(v int64) *PhaseTransitionUpdateOne {
	_u.mutation.ResetStartedAt()
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *PhaseTransitionUpdateOne) SetNillableStartedAt(v *int64) *PhaseTransitionUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// AddStartedAt adds value to the "started_at" field.
func (_u *PhaseTransitionUpdateOne) AddStartedAt(v int64) *PhaseTransitionUpdateOne {
	_u.mutation.AddStartedAt(v)
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *PhaseTransitionUpdateOne) SetEndedAt(v int64) *PhaseTransitionUpdateOne {
	_u.mutation.ResetEndedAt()
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *PhaseTransitionUpdateOne) SetNillableEndedAt(v *int64) *PhaseTransitionUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// AddEndedAt adds value to the "ended_at" field.
func (_u *PhaseTransitionUpdateOne) AddEndedAt(v int64) *PhaseTransitionUpdateOne {
	_u.mutation.AddEndedAt(v)
	return _u
}

// Mutation returns the PhaseTransitionMutation object of the builder.
func (_u *PhaseTransitionUpdateOne) Mutation() *PhaseTransitionMutation {
	return _u.mutation
}

// Where appends a list predicates to the PhaseTransitionUpdate builder.
func (_u *PhaseTransitionUpdateOne) Where(ps ...predicate.PhaseTransition) *PhaseTransitionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PhaseTransitionUpdateOne) Select(field string, fields ...string) *PhaseTransitionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PhaseTransition entity.
func (_u *PhaseTransitionUpdateOne) Save(ctx context.Context) (*PhaseTransition, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PhaseTransitionUpdateOne) SaveX(ctx context.Context) *PhaseTransition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PhaseTransitionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PhaseTransitionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PhaseTransitionUpdateOne) sqlSave(ctx context.Context) (_node *PhaseTransition, err error) {
	_spec := sqlgraph.NewUpdateSpec(phasetransition.Table, phasetransition.Columns, sqlgraph.NewFieldSpec(phasetransition.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PhaseTransition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, phasetransition.FieldID)
		for _, f := range fields {
			if !phasetransition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != phasetransition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunnerName(); ok {
		_spec.SetField(phasetransition.FieldRunnerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SetName(); ok {
		_spec.SetField(phasetransition.FieldSetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(phasetransition.FieldPhase, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(phasetransition.FieldStartedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStartedAt(); ok {
		_spec.AddField(phasetransition.FieldStartedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(phasetransition.FieldEndedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEndedAt(); ok {
		_spec.AddField(phasetransition.FieldEndedAt, field.TypeInt64, value)
	}
	_node = &PhaseTransition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{phasetransition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
