// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/phasetransition"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PhaseTransition is the model entity for the PhaseTransition schema.
type PhaseTransition struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RunnerName holds the value of the "runner_name" field.
	RunnerName string `json:"runner_name,omitempty"`
	// SetName holds the value of the "set_name" field.
	SetName string `json:"set_name,omitempty"`
	// Phase holds the value of the "phase" field.
	Phase string `json:"phase,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt int64 `json:"started_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt      int64 `json:"ended_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PhaseTransition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case phasetransition.FieldID, phasetransition.FieldStartedAt, phasetransition.FieldEndedAt:
			values[i] = new(sql.NullInt64)
		case phasetransition.FieldRunnerName, phasetransition.FieldSetName, phasetransition.FieldPhase:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PhaseTransition fields.
func (_m *PhaseTransition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case phasetransition.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case phasetransition.FieldRunnerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field runner_name", values[i])
			} else if value.Valid {
				_m.RunnerName = value.String
			}
		case phasetransition.FieldSetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field set_name", values[i])
			} else if value.Valid {
				_m.SetName = value.String
			}
		case phasetransition.FieldPhase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phase", values[i])
			} else if value.Valid {
				_m.Phase = value.String
			}
		case phasetransition.FieldStartedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Int64
			}
		case phasetransition.FieldEndedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PhaseTransition.
// This includes values selected through modifiers, order, etc.
func (_m *PhaseTransition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PhaseTransition.
// Note that you need to call PhaseTransition.Unwrap() before calling this method if this PhaseTransition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PhaseTransition) Update() *PhaseTransitionUpdateOne {
	return NewPhaseTransitionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PhaseTransition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PhaseTransition) Unwrap() *PhaseTransition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PhaseTransition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PhaseTransition) String() string {
	var builder strings.Builder
	builder.WriteString("PhaseTransition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("runner_name=")
	builder.WriteString(_m.RunnerName)
	builder.WriteString(", ")
	builder.WriteString("set_name=")
	builder.WriteString(_m.SetName)
	builder.WriteString(", ")
	builder.WriteString("phase=")
	builder.WriteString(_m.Phase)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartedAt))
	builder.WriteString(", ")
	builder.WriteString("ended_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.EndedAt))
	builder.WriteByte(')')
	return builder.String()
}

// PhaseTransitions is a parsable slice of PhaseTransition.
type PhaseTransitions []*PhaseTransition
