// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/phasetransition"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PhaseTransitionCreate is the builder for creating a PhaseTransition entity.
type PhaseTransitionCreate struct {
	config
	mutation *PhaseTransitionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRunnerName sets the "runner_name" field.
func (_c *PhaseTransitionCreate) SetRunnerName(v string) *PhaseTransitionCreate {
	_c.mutation.SetRunnerName(v)
	return _c
}

// SetSetName sets the "set_name" field.
func (_c *PhaseTransitionCreate) SetSetName(v string) *PhaseTransitionCreate {
	_c.mutation.SetSetName(v)
	return _c
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_c *PhaseTransitionCreate) SetNillableSetName(v *string) *PhaseTransitionCreate {
	if v != nil {
		_c.SetSetName(*v)
	}
	return _c
}

// SetPhase sets the "phase" field.
func (_c *PhaseTransitionCreate) SetPhase(v string) *PhaseTransitionCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *PhaseTransitionCreate) SetStartedAt(v int64) *PhaseTransitionCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *PhaseTransitionCreate) SetEndedAt(v int64) *PhaseTransitionCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *PhaseTransitionCreate) SetNillableEndedAt(v *int64) *PhaseTransitionCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// Mutation returns the PhaseTransitionMutation object of the builder.
func (_c *PhaseTransitionCreate) Mutation() *PhaseTransitionMutation {
	return _c.mutation
}

// Save creates the PhaseTransition in the database.
func (_c *PhaseTransitionCreate) Save(ctx context.Context) (*PhaseTransition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PhaseTransitionCreate) SaveX(ctx context.Context) *PhaseTransition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PhaseTransitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PhaseTransitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PhaseTransitionCreate) defaults() {
	if _, ok := _c.mutation.SetName(); !ok {
		v := phasetransition.DefaultSetName
		_c.mutation.SetSetName(v)
	}
	if _, ok := _c.mutation.EndedAt(); !ok {
		v := phasetransition.DefaultEndedAt
		_c.mutation.SetEndedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PhaseTransitionCreate) check() error {
	if _, ok := _c.mutation.RunnerName(); !ok {
		return &ValidationError{Name: "runner_name", err: errors.New(`ent: missing required field "PhaseTransition.runner_name"`)}
	}
	if _, ok := _c.mutation.SetName(); !ok {
		return &ValidationError{Name: "set_name", err: errors.New(`ent: missing required field "PhaseTransition.set_name"`)}
	}
	if _, ok := _c.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`ent: missing required field "PhaseTransition.phase"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "PhaseTransition.started_at"`)}
	}
	if _, ok := _c.mutation.EndedAt(); !ok {
		return &ValidationError{Name: "ended_at", err: errors.New(`ent: missing required field "PhaseTransition.ended_at"`)}
	}
	return nil
}

func (_c *PhaseTransitionCreate) sqlSave(ctx context.Context) (*PhaseTransition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PhaseTransitionCreate) createSpec() (*PhaseTransition, *sqlgraph.CreateSpec) {
	var (
		_node = &PhaseTransition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(phasetransition.Table, sqlgraph.NewFieldSpec(phasetransition.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RunnerName(); ok {
		_spec.SetField(phasetransition.FieldRunnerName, field.TypeString, value)
		_node.RunnerName = value
	}
	if value, ok := _c.mutation.SetName(); ok {
		_spec.SetField(phasetransition.FieldSetName, field.TypeString, value)
		_node.SetName = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(phasetransition.FieldPhase, field.TypeString, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(phasetransition.FieldStartedAt, field.TypeInt64, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(phasetransition.FieldEndedAt, field.TypeInt64, value)
		_node.EndedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PhaseTransition.Create().
//		SetRunnerName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PhaseTransitionUpsert) {
//			SetRunnerName(v+v).
//		}).
//		Exec(ctx)
func (_c *PhaseTransitionCreate) OnConflict(opts ...sql.ConflictOption) *PhaseTransitionUpsertOne {
	_c.conflict = opts
	return &PhaseTransitionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PhaseTransition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PhaseTransitionCreate) OnConflictColumns(columns ...string) *PhaseTransitionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PhaseTransitionUpsertOne{
		create: _c,
	}
}

type (
	// PhaseTransitionUpsertOne is the builder for "upsert"-ing
	//  one PhaseTransition node.
	PhaseTransitionUpsertOne struct {
		create *PhaseTransitionCreate
	}

	// PhaseTransitionUpsert is the "OnConflict" setter.
	PhaseTransitionUpsert struct {
		*sql.UpdateSet
	}
)

// SetRunnerName sets the "runner_name" field.
func (u *PhaseTransitionUpsert) SetRunnerName(v string) *PhaseTransitionUpsert {
	u.Set(phasetransition.FieldRunnerName, v)
	return u
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *PhaseTransitionUpsert) UpdateRunnerName() *PhaseTransitionUpsert {
	u.SetExcluded(phasetransition.FieldRunnerName)
	return u
}

// SetSetName sets the "set_name" field.
func (u *PhaseTransitionUpsert) SetSetName(v string) *PhaseTransitionUpsert {
	u.Set(phasetransition.FieldSetName, v)
	return u
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *PhaseTransitionUpsert) UpdateSetName() *PhaseTransitionUpsert {
	u.SetExcluded(phasetransition.FieldSetName)
	return u
}

// SetPhase sets the "phase" field.
func (u *PhaseTransitionUpsert) SetPhase(v string) *PhaseTransitionUpsert {
	u.Set(phasetransition.FieldPhase, v)
	return u
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *PhaseTransitionUpsert) UpdatePhase() *PhaseTransitionUpsert {
	u.SetExcluded(phasetransition.FieldPhase)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *PhaseTransitionUpsert) SetStartedAt(v int64) *PhaseTransitionUpsert {
	u.Set(phasetransition.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *PhaseTransitionUpsert) UpdateStartedAt() *PhaseTransitionUpsert {
	u.SetExcluded(phasetransition.FieldStartedAt)
	return u
}

// AddStartedAt adds v to the "started_at" field.
func (u *PhaseTransitionUpsert) AddStartedAt(v int64) *PhaseTransitionUpsert {
	u.Add(phasetransition.FieldStartedAt, v)
	return u
}

// SetEndedAt sets the "ended_at" field.
func (u *PhaseTransitionUpsert) SetEndedAt(v int64) *PhaseTransitionUpsert {
	u.Set(phasetransition.FieldEndedAt, v)
	return u
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *PhaseTransitionUpsert) UpdateEndedAt() *PhaseTransitionUpsert {
	u.SetExcluded(phasetransition.FieldEndedAt)
	return u
}

// AddEndedAt adds v to the "ended_at" field.
func (u *PhaseTransitionUpsert) AddEndedAt(v int64) *PhaseTransitionUpsert {
	u.Add(phasetransition.FieldEndedAt, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PhaseTransition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PhaseTransitionUpsertOne) UpdateNewValues() *PhaseTransitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PhaseTransition.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PhaseTransitionUpsertOne) Ignore() *PhaseTransitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PhaseTransitionUpsertOne) DoNothing() *PhaseTransitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PhaseTransitionCreate.OnConflict
// documentation for more info.
func (u *PhaseTransitionUpsertOne) Update(set func(*PhaseTransitionUpsert)) *PhaseTransitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PhaseTransitionUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunnerName sets the "runner_name" field.
func (u *PhaseTransitionUpsertOne) SetRunnerName(v string) *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.SetRunnerName(v)
	})
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *PhaseTransitionUpsertOne) UpdateRunnerName() *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.UpdateRunnerName()
	})
}

// SetSetName sets the "set_name" field.
func (u *PhaseTransitionUpsertOne) SetSetName(v string) *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.SetSetName(v)
	})
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *PhaseTransitionUpsertOne) UpdateSetName() *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.UpdateSetName()
	})
}

// SetPhase sets the "phase" field.
func (u *PhaseTransitionUpsertOne) SetPhase(v string) *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.SetPhase(v)
	})
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *PhaseTransitionUpsertOne) UpdatePhase() *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.UpdatePhase()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *PhaseTransitionUpsertOne) SetStartedAt(v int64) *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.SetStartedAt(v)
	})
}

// AddStartedAt adds v to the "started_at" field.
func (u *PhaseTransitionUpsertOne) AddStartedAt(v int64) *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.AddStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *PhaseTransitionUpsertOne) UpdateStartedAt() *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.UpdateStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *PhaseTransitionUpsertOne) SetEndedAt(v int64) *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.SetEndedAt(v)
	})
}

// AddEndedAt adds v to the "ended_at" field.
func (u *PhaseTransitionUpsertOne) AddEndedAt(v int64) *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.AddEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *PhaseTransitionUpsertOne) UpdateEndedAt() *PhaseTransitionUpsertOne {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.UpdateEndedAt()
	})
}

// Exec executes the query.
func (u *PhaseTransitionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PhaseTransitionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PhaseTransitionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PhaseTransitionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PhaseTransitionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PhaseTransitionCreateBulk is the builder for creating many PhaseTransition entities in bulk.
type PhaseTransitionCreateBulk struct {
	config
	err      error
	builders []*PhaseTransitionCreate
	conflict []sql.ConflictOption
}

// Save creates the PhaseTransition entities in the database.
func (_c *PhaseTransitionCreateBulk) Save(ctx context.Context) ([]*PhaseTransition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PhaseTransition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PhaseTransitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PhaseTransitionCreateBulk) SaveX(ctx context.Context) []*PhaseTransition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PhaseTransitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PhaseTransitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PhaseTransition.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PhaseTransitionUpsert) {
//			SetRunnerName(v+v).
//		}).
//		Exec(ctx)
func (_c *PhaseTransitionCreateBulk) OnConflict(opts ...sql.ConflictOption) *PhaseTransitionUpsertBulk {
	_c.conflict = opts
	return &PhaseTransitionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PhaseTransition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PhaseTransitionCreateBulk) OnConflictColumns(columns ...string) *PhaseTransitionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PhaseTransitionUpsertBulk{
		create: _c,
	}
}

// PhaseTransitionUpsertBulk is the builder for "upsert"-ing
// a bulk of PhaseTransition nodes.
type PhaseTransitionUpsertBulk struct {
	create *PhaseTransitionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PhaseTransition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PhaseTransitionUpsertBulk) UpdateNewValues() *PhaseTransitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PhaseTransition.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PhaseTransitionUpsertBulk) Ignore() *PhaseTransitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PhaseTransitionUpsertBulk) DoNothing() *PhaseTransitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PhaseTransitionCreateBulk.OnConflict
// documentation for more info.
func (u *PhaseTransitionUpsertBulk) Update(set func(*PhaseTransitionUpsert)) *PhaseTransitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PhaseTransitionUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunnerName sets the "runner_name" field.
func (u *PhaseTransitionUpsertBulk) SetRunnerName(v string) *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.SetRunnerName(v)
	})
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *PhaseTransitionUpsertBulk) UpdateRunnerName() *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.UpdateRunnerName()
	})
}

// SetSetName sets the "set_name" field.
func (u *PhaseTransitionUpsertBulk) SetSetName(v string) *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.SetSetName(v)
	})
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *PhaseTransitionUpsertBulk) UpdateSetName() *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.UpdateSetName()
	})
}

// SetPhase sets the "phase" field.
func (u *PhaseTransitionUpsertBulk) SetPhase(v string) *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.SetPhase(v)
	})
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *PhaseTransitionUpsertBulk) UpdatePhase() *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.UpdatePhase()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *PhaseTransitionUpsertBulk) SetStartedAt(v int64) *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.SetStartedAt(v)
	})
}

// AddStartedAt adds v to the "started_at" field.
func (u *PhaseTransitionUpsertBulk) AddStartedAt(v int64) *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.AddStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *PhaseTransitionUpsertBulk) UpdateStartedAt() *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.UpdateStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *PhaseTransitionUpsertBulk) SetEndedAt(v int64) *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.SetEndedAt(v)
	})
}

// AddEndedAt adds v to the "ended_at" field.
func (u *PhaseTransitionUpsertBulk) AddEndedAt(v int64) *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.AddEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *PhaseTransitionUpsertBulk) UpdateEndedAt() *PhaseTransitionUpsertBulk {
	return u.Update(func(s *PhaseTransitionUpsert) {
		s.UpdateEndedAt()
	})
}

// Exec executes the query.
func (u *PhaseTransitionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PhaseTransitionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PhaseTransitionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PhaseTransitionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
