// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/predicate"
	"arc-ui/internal/store/ent/runnerfailure"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RunnerFailureUpdate is the builder for updating RunnerFailure entities.
type RunnerFailureUpdate struct {
	config
	hooks    []Hook
	mutation *RunnerFailureMutation
}

// Where appends a list predicates to the RunnerFailureUpdate builder.
func (_u *RunnerFailureUpdate) Where(ps ...predicate.RunnerFailure) *RunnerFailureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRunnerName sets the "runner_name" field.
func (_u *RunnerFailureUpdate) SetRunnerName(v string) *RunnerFailureUpdate {
	_u.mutation.SetRunnerName(v)
	return _u
}

// SetNillableRunnerName sets the "runner_name" field if the given value is not nil.
func (_u *RunnerFailureUpdate) SetNillableRunnerName(v *string) *RunnerFailureUpdate {
	if v != nil {
		_u.SetRunnerName(*v)
	}
	return _u
}

// SetSetName sets the "set_name" field.
func (_u *RunnerFailureUpdate) SetSetName(v string) *RunnerFailureUpdate {
	_u.mutation.SetSetName(v)
	return _u
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_u *RunnerFailureUpdate) SetNillableSetName(v *string) *RunnerFailureUpdate {
	if v != nil {
		_u.SetSetName(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *RunnerFailureUpdate) SetReason(v string) *RunnerFailureUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RunnerFailureUpdate) SetNillableReason(v *string) *RunnerFailureUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetSevere sets the "severe" field.
func (_u *RunnerFailureUpdate) SetSevere(v bool) *RunnerFailureUpdate {
	_u.mutation.SetSevere(v)
	return _u
}

// SetNillableSevere sets the "severe" field if the given value is not nil.
func (_u *RunnerFailureUpdate) SetNillableSevere(v *bool) *RunnerFailureUpdate {
	if v != nil {
		_u.SetSevere(*v)
	}
	return _u
}

// SetTs sets the "ts" field.
func (_u *RunnerFailureUpdate) SetTs(v int64) *RunnerFailureUpdate {
	_u.mutation.ResetTs()
	_u.mutation.SetTs(v)
	return _u
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (_u *RunnerFailureUpdate) SetNillableTs(v *int64) *RunnerFailureUpdate {
	if v != nil {
		_u.SetTs(*v)
	}
	return _u
}

// AddTs adds value to the "ts" field.
func (_u *RunnerFailureUpdate) AddTs(v int64) *RunnerFailureUpdate {
	_u.mutation.AddTs(v)
	return _u
}

// Mutation returns the RunnerFailureMutation object of the builder.
func (_u *RunnerFailureUpdate) Mutation() *RunnerFailureMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RunnerFailureUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunnerFailureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RunnerFailureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunnerFailureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RunnerFailureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(runnerfailure.Table, runnerfailure.Columns, sqlgraph.NewFieldSpec(runnerfailure.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunnerName(); ok {
		_spec.SetField(runnerfailure.FieldRunnerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SetName(); ok {
		_spec.SetField(runnerfailure.FieldSetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(runnerfailure.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severe(); ok {
		_spec.SetField(runnerfailure.FieldSevere, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Ts(); ok {
		_spec.SetField(runnerfailure.FieldTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTs(); ok {
		_spec.AddField(runnerfailure.FieldTs, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runnerfailure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RunnerFailureUpdateOne is the builder for updating a single RunnerFailure entity.
type RunnerFailureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RunnerFailureMutation
}

// SetRunnerName sets the "runner_name" field.
func (_u *RunnerFailureUpdateOne) SetRunnerName(v string) *RunnerFailureUpdateOne {
	_u.mutation.SetRunnerName(v)
	return _u
}

// SetNillableRunnerName sets the "runner_name" field if the given value is not nil.
func (_u *RunnerFailureUpdateOne) SetNillableRunnerName(v *string) *RunnerFailureUpdateOne {
	if v != nil {
		_u.SetRunnerName(*v)
	}
	return _u
}

// SetSetName sets the "set_name" field.
func (_u *RunnerFailureUpdateOne) SetSetName(v string) *RunnerFailureUpdateOne {
	_u.mutation.SetSetName(v)
	return _u
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_u *RunnerFailureUpdateOne) SetNillableSetName(v *string) *RunnerFailureUpdateOne {
	if v != nil {
		_u.SetSetName(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *RunnerFailureUpdateOne) SetReason(v string) *RunnerFailureUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RunnerFailureUpdateOne) SetNillableReason(v *string) *RunnerFailureUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetSevere sets the "severe" field.
func (_u *RunnerFailureUpdateOne) SetSevere(v bool) *RunnerFailureUpdateOne {
	_u.mutation.SetSevere(v)
	return _u
}

// SetNillableSevere sets the "severe" field if the given value is not nil.
func (_u *RunnerFailureUpdateOne) SetNillableSevere(v *bool) *RunnerFailureUpdateOne {
	if v != nil {
		_u.SetSevere(*v)
	}
	return _u
}

// SetTs sets the "ts" field.
func (_u *RunnerFailureUpdateOne) SetTs(v int64) *RunnerFailureUpdateOne {
	_u.mutation.ResetTs()
	_u.mutation.SetTs(v)
	return _u
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (_u *RunnerFailureUpdateOne) SetNillableTs(v *int64) *RunnerFailureUpdateOne {
	if v != nil {
		_u.SetTs(*v)
	}
	return _u
}

// AddTs adds value to the "ts" field.
func (_u *RunnerFailureUpdateOne) AddTs(v int64) *RunnerFailureUpdateOne {
	_u.mutation.AddTs(v)
	return _u
}

// Mutation returns the RunnerFailureMutation object of the builder.
func (_u *RunnerFailureUpdateOne) Mutation() *RunnerFailureMutation {
	return _u.mutation
}

// Where appends a list predicates to the RunnerFailureUpdate builder.
func (_u *RunnerFailureUpdateOne) Where(ps ...predicate.RunnerFailure) *RunnerFailureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RunnerFailureUpdateOne) Select(field string, fields ...string) *RunnerFailureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RunnerFailure entity.
func (_u *RunnerFailureUpdateOne) Save(ctx context.Context) (*RunnerFailure, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunnerFailureUpdateOne) SaveX(ctx context.Context) *RunnerFailure {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RunnerFailureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunnerFailureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RunnerFailureUpdateOne) sqlSave(ctx context.Context) (_node *RunnerFailure, err error) {
	_spec := sqlgraph.NewUpdateSpec(runnerfailure.Table, runnerfailure.Columns, sqlgraph.NewFieldSpec(runnerfailure.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RunnerFailure.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, runnerfailure.FieldID)
		for _, f := range fields {
			if !runnerfailure.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != runnerfailure.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunnerName(); ok {
		_spec.SetField(runnerfailure.FieldRunnerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SetName(); ok {
		_spec.SetField(runnerfailure.FieldSetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(runnerfailure.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severe(); ok {
		_spec.SetField(runnerfailure.FieldSevere, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Ts(); ok {
		_spec.SetField(runnerfailure.FieldTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTs(); ok {
		_spec.AddField(runnerfailure.FieldTs, field.TypeInt64, value)
	}
	_node = &RunnerFailure{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runnerfailure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
