// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/runnerfailure"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RunnerFailureCreate is the builder for creating a RunnerFailure entity.
type RunnerFailureCreate struct {
	config
	mutation *RunnerFailureMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRunnerName sets the "runner_name" field.
func (_c *RunnerFailureCreate) SetRunnerName(v string) *RunnerFailureCreate {
	_c.mutation.SetRunnerName(v)
	return _c
}

// SetSetName sets the "set_name" field.
func (_c *RunnerFailureCreate) SetSetName(v string) *RunnerFailureCreate {
	_c.mutation.SetSetName(v)
	return _c
}

// SetNillableSetName sets the "set_name" field if the given value is not nil.
func (_c *RunnerFailureCreate) SetNillableSetName(v *string) *RunnerFailureCreate {
	if v != nil {
		_c.SetSetName(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *RunnerFailureCreate) SetReason(v string) *RunnerFailureCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetSevere sets the "severe" field.
func (_c *RunnerFailureCreate) SetSevere(v bool) *RunnerFailureCreate {
	_c.mutation.SetSevere(v)
	return _c
}

// SetNillableSevere sets the "severe" field if the given value is not nil.
func (_c *RunnerFailureCreate) SetNillableSevere(v *bool) *RunnerFailureCreate {
	if v != nil {
		_c.SetSevere(*v)
	}
	return _c
}

// SetTs sets the "ts" field.
func (_c *RunnerFailureCreate) SetTs(v int64) *RunnerFailureCreate {
	_c.mutation.SetTs(v)
	return _c
}

// Mutation returns the RunnerFailureMutation object of the builder.
func (_c *RunnerFailureCreate) Mutation() *RunnerFailureMutation {
	return _c.mutation
}

// Save creates the RunnerFailure in the database.
func (_c *RunnerFailureCreate) Save(ctx context.Context) (*RunnerFailure, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RunnerFailureCreate) SaveX(ctx context.Context) *RunnerFailure {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunnerFailureCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunnerFailureCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RunnerFailureCreate) defaults() {
	if _, ok := _c.mutation.SetName(); !ok {
		v := runnerfailure.DefaultSetName
		_c.mutation.SetSetName(v)
	}
	if _, ok := _c.mutation.Severe(); !ok {
		v := runnerfailure.DefaultSevere
		_c.mutation.SetSevere(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RunnerFailureCreate) check() error {
	if _, ok := _c.mutation.RunnerName(); !ok {
		return &ValidationError{Name: "runner_name", err: errors.New(`ent: missing required field "RunnerFailure.runner_name"`)}
	}
	if _, ok := _c.mutation.SetName(); !ok {
		return &ValidationError{Name: "set_name", err: errors.New(`ent: missing required field "RunnerFailure.set_name"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "RunnerFailure.reason"`)}
	}
	if _, ok := _c.mutation.Severe(); !ok {
		return &ValidationError{Name: "severe", err: errors.New(`ent: missing required field "RunnerFailure.severe"`)}
	}
	if _, ok := _c.mutation.Ts(); !ok {
		return &ValidationError{Name: "ts", err: errors.New(`ent: missing required field "RunnerFailure.ts"`)}
	}
	return nil
}

func (_c *RunnerFailureCreate) sqlSave(ctx context.Context) (*RunnerFailure, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RunnerFailureCreate) createSpec() (*RunnerFailure, *sqlgraph.CreateSpec) {
	var (
		_node = &RunnerFailure{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(runnerfailure.Table, sqlgraph.NewFieldSpec(runnerfailure.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RunnerName(); ok {
		_spec.SetField(runnerfailure.FieldRunnerName, field.TypeString, value)
		_node.RunnerName = value
	}
	if value, ok := _c.mutation.SetName(); ok {
		_spec.SetField(runnerfailure.FieldSetName, field.TypeString, value)
		_node.SetName = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(runnerfailure.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Severe(); ok {
		_spec.SetField(runnerfailure.FieldSevere, field.TypeBool, value)
		_node.Severe = value
	}
	if value, ok := _c.mutation.Ts(); ok {
		_spec.SetField(runnerfailure.FieldTs, field.TypeInt64, value)
		_node.Ts = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RunnerFailure.Create().
//		SetRunnerName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RunnerFailureUpsert) {
//			SetRunnerName(v+v).
//		}).
//		Exec(ctx)
func (_c *RunnerFailureCreate) OnConflict(opts ...sql.ConflictOption) *RunnerFailureUpsertOne {
	_c.conflict = opts
	return &RunnerFailureUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RunnerFailure.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RunnerFailureCreate) OnConflictColumns(columns ...string) *RunnerFailureUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RunnerFailureUpsertOne{
		create: _c,
	}
}

type (
	// RunnerFailureUpsertOne is the builder for "upsert"-ing
	//  one RunnerFailure node.
	RunnerFailureUpsertOne struct {
		create *RunnerFailureCreate
	}

	// RunnerFailureUpsert is the "OnConflict" setter.
	RunnerFailureUpsert struct {
		*sql.UpdateSet
	}
)

// SetRunnerName sets the "runner_name" field.
func (u *RunnerFailureUpsert) SetRunnerName(v string) *RunnerFailureUpsert {
	u.Set(runnerfailure.FieldRunnerName, v)
	return u
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *RunnerFailureUpsert) UpdateRunnerName() *RunnerFailureUpsert {
	u.SetExcluded(runnerfailure.FieldRunnerName)
	return u
}

// SetSetName sets the "set_name" field.
func (u *RunnerFailureUpsert) SetSetName(v string) *RunnerFailureUpsert {
	u.Set(runnerfailure.FieldSetName, v)
	return u
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *RunnerFailureUpsert) UpdateSetName() *RunnerFailureUpsert {
	u.SetExcluded(runnerfailure.FieldSetName)
	return u
}

// SetReason sets the "reason" field.
func (u *RunnerFailureUpsert) SetReason(v string) *RunnerFailureUpsert {
	u.Set(runnerfailure.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *RunnerFailureUpsert) UpdateReason() *RunnerFailureUpsert {
	u.SetExcluded(runnerfailure.FieldReason)
	return u
}

// SetSevere sets the "severe" field.
func (u *RunnerFailureUpsert) SetSevere(v bool) *RunnerFailureUpsert {
	u.Set(runnerfailure.FieldSevere, v)
	return u
}

// UpdateSevere sets the "severe" field to the value that was provided on create.
func (u *RunnerFailureUpsert) UpdateSevere() *RunnerFailureUpsert {
	u.SetExcluded(runnerfailure.FieldSevere)
	return u
}

// SetTs sets the "ts" field.
func (u *RunnerFailureUpsert) SetTs(v int64) *RunnerFailureUpsert {
	u.Set(runnerfailure.FieldTs, v)
	return u
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *RunnerFailureUpsert) UpdateTs() *RunnerFailureUpsert {
	u.SetExcluded(runnerfailure.FieldTs)
	return u
}

// AddTs adds v to the "ts" field.
func (u *RunnerFailureUpsert) AddTs(v int64) *RunnerFailureUpsert {
	u.Add(runnerfailure.FieldTs, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RunnerFailure.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RunnerFailureUpsertOne) UpdateNewValues() *RunnerFailureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RunnerFailure.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RunnerFailureUpsertOne) Ignore() *RunnerFailureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RunnerFailureUpsertOne) DoNothing() *RunnerFailureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RunnerFailureCreate.OnConflict
// documentation for more info.
func (u *RunnerFailureUpsertOne) Update(set func(*RunnerFailureUpsert)) *RunnerFailureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RunnerFailureUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunnerName sets the "runner_name" field.
func (u *RunnerFailureUpsertOne) SetRunnerName(v string) *RunnerFailureUpsertOne {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.SetRunnerName(v)
	})
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *RunnerFailureUpsertOne) UpdateRunnerName() *RunnerFailureUpsertOne {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.UpdateRunnerName()
	})
}

// SetSetName sets the "set_name" field.
func (u *RunnerFailureUpsertOne) SetSetName(v string) *RunnerFailureUpsertOne {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.SetSetName(v)
	})
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *RunnerFailureUpsertOne) UpdateSetName() *RunnerFailureUpsertOne {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.UpdateSetName()
	})
}

// SetReason sets the "reason" field.
func (u *RunnerFailureUpsertOne) SetReason(v string) *RunnerFailureUpsertOne {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *RunnerFailureUpsertOne) UpdateReason() *RunnerFailureUpsertOne {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.UpdateReason()
	})
}

// SetSevere sets the "severe" field.
func (u *RunnerFailureUpsertOne) SetSevere(v bool) *RunnerFailureUpsertOne {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.SetSevere(v)
	})
}

// UpdateSevere sets the "severe" field to the value that was provided on create.
func (u *RunnerFailureUpsertOne) UpdateSevere() *RunnerFailureUpsertOne {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.UpdateSevere()
	})
}

// SetTs sets the "ts" field.
func (u *RunnerFailureUpsertOne) SetTs(v int64) *RunnerFailureUpsertOne {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *RunnerFailureUpsertOne) AddTs(v int64) *RunnerFailureUpsertOne {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *RunnerFailureUpsertOne) UpdateTs() *RunnerFailureUpsertOne {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.UpdateTs()
	})
}

// Exec executes the query.
func (u *RunnerFailureUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RunnerFailureCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RunnerFailureUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RunnerFailureUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RunnerFailureUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RunnerFailureCreateBulk is the builder for creating many RunnerFailure entities in bulk.
type RunnerFailureCreateBulk struct {
	config
	err      error
	builders []*RunnerFailureCreate
	conflict []sql.ConflictOption
}

// Save creates the RunnerFailure entities in the database.
func (_c *RunnerFailureCreateBulk) Save(ctx context.Context) ([]*RunnerFailure, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RunnerFailure, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RunnerFailureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RunnerFailureCreateBulk) SaveX(ctx context.Context) []*RunnerFailure {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunnerFailureCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunnerFailureCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RunnerFailure.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RunnerFailureUpsert) {
//			SetRunnerName(v+v).
//		}).
//		Exec(ctx)
func (_c *RunnerFailureCreateBulk) OnConflict(opts ...sql.ConflictOption) *RunnerFailureUpsertBulk {
	_c.conflict = opts
	return &RunnerFailureUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RunnerFailure.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RunnerFailureCreateBulk) OnConflictColumns(columns ...string) *RunnerFailureUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RunnerFailureUpsertBulk{
		create: _c,
	}
}

// RunnerFailureUpsertBulk is the builder for "upsert"-ing
// a bulk of RunnerFailure nodes.
type RunnerFailureUpsertBulk struct {
	create *RunnerFailureCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RunnerFailure.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RunnerFailureUpsertBulk) UpdateNewValues() *RunnerFailureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RunnerFailure.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RunnerFailureUpsertBulk) Ignore() *RunnerFailureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RunnerFailureUpsertBulk) DoNothing() *RunnerFailureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RunnerFailureCreateBulk.OnConflict
// documentation for more info.
func (u *RunnerFailureUpsertBulk) Update(set func(*RunnerFailureUpsert)) *RunnerFailureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RunnerFailureUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunnerName sets the "runner_name" field.
func (u *RunnerFailureUpsertBulk) SetRunnerName(v string) *RunnerFailureUpsertBulk {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.SetRunnerName(v)
	})
}

// UpdateRunnerName sets the "runner_name" field to the value that was provided on create.
func (u *RunnerFailureUpsertBulk) UpdateRunnerName() *RunnerFailureUpsertBulk {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.UpdateRunnerName()
	})
}

// SetSetName sets the "set_name" field.
func (u *RunnerFailureUpsertBulk) SetSetName(v string) *RunnerFailureUpsertBulk {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.SetSetName(v)
	})
}

// UpdateSetName sets the "set_name" field to the value that was provided on create.
func (u *RunnerFailureUpsertBulk) UpdateSetName() *RunnerFailureUpsertBulk {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.UpdateSetName()
	})
}

// SetReason sets the "reason" field.
func (u *RunnerFailureUpsertBulk) SetReason(v string) *RunnerFailureUpsertBulk {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *RunnerFailureUpsertBulk) UpdateReason() *RunnerFailureUpsertBulk {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.UpdateReason()
	})
}

// SetSevere sets the "severe" field.
func (u *RunnerFailureUpsertBulk) SetSevere(v bool) *RunnerFailureUpsertBulk {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.SetSevere(v)
	})
}

// UpdateSevere sets the "severe" field to the value that was provided on create.
func (u *RunnerFailureUpsertBulk) UpdateSevere() *RunnerFailureUpsertBulk {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.UpdateSevere()
	})
}

// SetTs sets the "ts" field.
func (u *RunnerFailureUpsertBulk) SetTs(v int64) *RunnerFailureUpsertBulk {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *RunnerFailureUpsertBulk) AddTs(v int64) *RunnerFailureUpsertBulk {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *RunnerFailureUpsertBulk) UpdateTs() *RunnerFailureUpsertBulk {
	return u.Update(func(s *RunnerFailureUpsert) {
		s.UpdateTs()
	})
}

// Exec executes the query.
func (u *RunnerFailureUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RunnerFailureCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RunnerFailureCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RunnerFailureUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
