// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/predicate"
	"arc-ui/internal/store/ent/runnerfailure"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RunnerFailureDelete is the builder for deleting a RunnerFailure entity.
type RunnerFailureDelete struct {
	config
	hooks    []Hook
	mutation *RunnerFailureMutation
}

// Where appends a list predicates to the RunnerFailureDelete builder.
func (_d *RunnerFailureDelete) Where(ps ...predicate.RunnerFailure) *RunnerFailureDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RunnerFailureDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RunnerFailureDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RunnerFailureDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(runnerfailure.Table, sqlgraph.NewFieldSpec(runnerfailure.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RunnerFailureDeleteOne is the builder for deleting a single RunnerFailure entity.
type RunnerFailureDeleteOne struct {
	_d *RunnerFailureDelete
}

// Where appends a list predicates to the RunnerFailureDelete builder.
func (_d *RunnerFailureDeleteOne) Where(ps ...predicate.RunnerFailure) *RunnerFailureDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RunnerFailureDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{runnerfailure.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RunnerFailureDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
