// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/churnevent"
	"arc-ui/internal/store/ent/jobobservation"
	"arc-ui/internal/store/ent/phasetransition"
	"arc-ui/internal/store/ent/runnerfailure"
	"arc-ui/internal/store/ent/sample"
	"arc-ui/internal/store/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	churneventFields := schema.ChurnEvent{}.Fields()
	_ = churneventFields
	// churneventDescSetName is the schema descriptor for set_name field.
	churneventDescSetName := churneventFields[1].Descriptor()
	// churnevent.DefaultSetName holds the default value on creation for the set_name field.
	churnevent.DefaultSetName = churneventDescSetName.Default.(string)
	jobobservationFields := schema.JobObservation{}.Fields()
	_ = jobobservationFields
	// jobobservationDescSetName is the schema descriptor for set_name field.
	jobobservationDescSetName := jobobservationFields[1].Descriptor()
	// jobobservation.DefaultSetName holds the default value on creation for the set_name field.
	jobobservation.DefaultSetName = jobobservationDescSetName.Default.(string)
	// jobobservationDescRepository is the schema descriptor for repository field.
	jobobservationDescRepository := jobobservationFields[2].Descriptor()
	// jobobservation.DefaultRepository holds the default value on creation for the repository field.
	jobobservation.DefaultRepository = jobobservationDescRepository.Default.(string)
	// jobobservationDescWorkflow is the schema descriptor for workflow field.
	jobobservationDescWorkflow := jobobservationFields[3].Descriptor()
	// jobobservation.DefaultWorkflow holds the default value on creation for the workflow field.
	jobobservation.DefaultWorkflow = jobobservationDescWorkflow.Default.(string)
	// jobobservationDescJobName is the schema descriptor for job_name field.
	jobobservationDescJobName := jobobservationFields[4].Descriptor()
	// jobobservation.DefaultJobName holds the default value on creation for the job_name field.
	jobobservation.DefaultJobName = jobobservationDescJobName.Default.(string)
	// jobobservationDescRunID is the schema descriptor for run_id field.
	jobobservationDescRunID := jobobservationFields[5].Descriptor()
	// jobobservation.DefaultRunID holds the default value on creation for the run_id field.
	jobobservation.DefaultRunID = jobobservationDescRunID.Default.(int64)
	// jobobservationDescFinishedAt is the schema descriptor for finished_at field.
	jobobservationDescFinishedAt := jobobservationFields[7].Descriptor()
	// jobobservation.DefaultFinishedAt holds the default value on creation for the finished_at field.
	jobobservation.DefaultFinishedAt = jobobservationDescFinishedAt.Default.(int64)
	// jobobservationDescSucceeded is the schema descriptor for succeeded field.
	jobobservationDescSucceeded := jobobservationFields[8].Descriptor()
	// jobobservation.DefaultSucceeded holds the default value on creation for the succeeded field.
	jobobservation.DefaultSucceeded = jobobservationDescSucceeded.Default.(bool)
	// jobobservationDescCPUSeconds is the schema descriptor for cpu_seconds field.
	jobobservationDescCPUSeconds := jobobservationFields[9].Descriptor()
	// jobobservation.DefaultCPUSeconds holds the default value on creation for the cpu_seconds field.
	jobobservation.DefaultCPUSeconds = jobobservationDescCPUSeconds.Default.(float64)
	// jobobservationDescMemByteSeconds is the schema descriptor for mem_byte_seconds field.
	jobobservationDescMemByteSeconds := jobobservationFields[10].Descriptor()
	// jobobservation.DefaultMemByteSeconds holds the default value on creation for the mem_byte_seconds field.
	jobobservation.DefaultMemByteSeconds = jobobservationDescMemByteSeconds.Default.(float64)
	phasetransitionFields := schema.PhaseTransition{}.Fields()
	_ = phasetransitionFields
	// phasetransitionDescSetName is the schema descriptor for set_name field.
	phasetransitionDescSetName := phasetransitionFields[1].Descriptor()
	// phasetransition.DefaultSetName holds the default value on creation for the set_name field.
	phasetransition.DefaultSetName = phasetransitionDescSetName.Default.(string)
	// phasetransitionDescEndedAt is the schema descriptor for ended_at field.
	phasetransitionDescEndedAt := phasetransitionFields[4].Descriptor()
	// phasetransition.DefaultEndedAt holds the default value on creation for the ended_at field.
	phasetransition.DefaultEndedAt = phasetransitionDescEndedAt.Default.(int64)
	runnerfailureFields := schema.RunnerFailure{}.Fields()
	_ = runnerfailureFields
	// runnerfailureDescSetName is the schema descriptor for set_name field.
	runnerfailureDescSetName := runnerfailureFields[1].Descriptor()
	// runnerfailure.DefaultSetName holds the default value on creation for the set_name field.
	runnerfailure.DefaultSetName = runnerfailureDescSetName.Default.(string)
	// runnerfailureDescSevere is the schema descriptor for severe field.
	runnerfailureDescSevere := runnerfailureFields[3].Descriptor()
	// runnerfailure.DefaultSevere holds the default value on creation for the severe field.
	runnerfailure.DefaultSevere = runnerfailureDescSevere.Default.(bool)
	sampleFields := schema.Sample{}.Fields()
	_ = sampleFields
	// sampleDescScopeID is the schema descriptor for scope_id field.
	sampleDescScopeID := sampleFields[2].Descriptor()
	// sample.DefaultScopeID holds the default value on creation for the scope_id field.
	sample.DefaultScopeID = sampleDescScopeID.Default.(string)
}
