// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arc-ui/internal/store/ent/sample"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SampleCreate is the builder for creating a Sample entity.
type SampleCreate struct {
	config
	mutation *SampleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTs sets the "ts" field.
func (_c *SampleCreate) SetTs(v int64) *SampleCreate {
	_c.mutation.SetTs(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *SampleCreate) SetScope(v string) *SampleCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetScopeID sets the "scope_id" field.
func (_c *SampleCreate) SetScopeID(v string) *SampleCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_c *SampleCreate) SetNillableScopeID(v *string) *SampleCreate {
	if v != nil {
		_c.SetScopeID(*v)
	}
	return _c
}

// SetTier sets the "tier" field.
func (_c *SampleCreate) SetTier(v string) *SampleCreate {
	_c.mutation.SetTier(v)
	return _c
}

// SetMetric sets the "metric" field.
func (_c *SampleCreate) SetMetric(v string) *SampleCreate {
	_c.mutation.SetMetric(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *SampleCreate) SetValue(v float64) *SampleCreate {
	_c.mutation.SetValue(v)
	return _c
}

// Mutation returns the SampleMutation object of the builder.
func (_c *SampleCreate) Mutation() *SampleMutation {
	return _c.mutation
}

// Save creates the Sample in the database.
func (_c *SampleCreate) Save(ctx context.Context) (*Sample, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SampleCreate) SaveX(ctx context.Context) *Sample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SampleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SampleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SampleCreate) defaults() {
	if _, ok := _c.mutation.ScopeID(); !ok {
		v := sample.DefaultScopeID
		_c.mutation.SetScopeID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SampleCreate) check() error {
	if _, ok := _c.mutation.Ts(); !ok {
		return &ValidationError{Name: "ts", err: errors.New(`ent: missing required field "Sample.ts"`)}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "Sample.scope"`)}
	}
	if _, ok := _c.mutation.ScopeID(); !ok {
		return &ValidationError{Name: "scope_id", err: errors.New(`ent: missing required field "Sample.scope_id"`)}
	}
	if _, ok := _c.mutation.Tier(); !ok {
		return &ValidationError{Name: "tier", err: errors.New(`ent: missing required field "Sample.tier"`)}
	}
	if _, ok := _c.mutation.Metric(); !ok {
		return &ValidationError{Name: "metric", err: errors.New(`ent: missing required field "Sample.metric"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "Sample.value"`)}
	}
	return nil
}

func (_c *SampleCreate) sqlSave(ctx context.Context) (*Sample, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SampleCreate) createSpec() (*Sample, *sqlgraph.CreateSpec) {
	var (
		_node = &Sample{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sample.Table, sqlgraph.NewFieldSpec(sample.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Ts(); ok {
		_spec.SetField(sample.FieldTs, field.TypeInt64, value)
		_node.Ts = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(sample.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(sample.FieldScopeID, field.TypeString, value)
		_node.ScopeID = value
	}
	if value, ok := _c.mutation.Tier(); ok {
		_spec.SetField(sample.FieldTier, field.TypeString, value)
		_node.Tier = value
	}
	if value, ok := _c.mutation.Metric(); ok {
		_spec.SetField(sample.FieldMetric, field.TypeString, value)
		_node.Metric = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(sample.FieldValue, field.TypeFloat64, value)
		_node.Value = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Sample.Create().
//		SetTs(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SampleUpsert) {
//			SetTs(v+v).
//		}).
//		Exec(ctx)
func (_c *SampleCreate) OnConflict(opts ...sql.ConflictOption) *SampleUpsertOne {
	_c.conflict = opts
	return &SampleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Sample.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SampleCreate) OnConflictColumns(columns ...string) *SampleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SampleUpsertOne{
		create: _c,
	}
}

type (
	// SampleUpsertOne is the builder for "upsert"-ing
	//  one Sample node.
	SampleUpsertOne struct {
		create *SampleCreate
	}

	// SampleUpsert is the "OnConflict" setter.
	SampleUpsert struct {
		*sql.UpdateSet
	}
)

// SetTs sets the "ts" field.
func (u *SampleUpsert) SetTs(v int64) *SampleUpsert {
	u.Set(sample.FieldTs, v)
	return u
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *SampleUpsert) UpdateTs() *SampleUpsert {
	u.SetExcluded(sample.FieldTs)
	return u
}

// AddTs adds v to the "ts" field.
func (u *SampleUpsert) AddTs(v int64) *SampleUpsert {
	u.Add(sample.FieldTs, v)
	return u
}

// SetScope sets the "scope" field.
func (u *SampleUpsert) SetScope(v string) *SampleUpsert {
	u.Set(sample.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SampleUpsert) UpdateScope() *SampleUpsert {
	u.SetExcluded(sample.FieldScope)
	return u
}

// SetScopeID sets the "scope_id" field.
func (u *SampleUpsert) SetScopeID(v string) *SampleUpsert {
	u.Set(sample.FieldScopeID, v)
	return u
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SampleUpsert) UpdateScopeID() *SampleUpsert {
	u.SetExcluded(sample.FieldScopeID)
	return u
}

// SetTier sets the "tier" field.
func (u *SampleUpsert) SetTier(v string) *SampleUpsert {
	u.Set(sample.FieldTier, v)
	return u
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *SampleUpsert) UpdateTier() *SampleUpsert {
	u.SetExcluded(sample.FieldTier)
	return u
}

// SetMetric sets the "metric" field.
func (u *SampleUpsert) SetMetric(v string) *SampleUpsert {
	u.Set(sample.FieldMetric, v)
	return u
}

// UpdateMetric sets the "metric" field to the value that was provided on create.
func (u *SampleUpsert) UpdateMetric() *SampleUpsert {
	u.SetExcluded(sample.FieldMetric)
	return u
}

// SetValue sets the "value" field.
func (u *SampleUpsert) SetValue(v float64) *SampleUpsert {
	u.Set(sample.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SampleUpsert) UpdateValue() *SampleUpsert {
	u.SetExcluded(sample.FieldValue)
	return u
}

// AddValue adds v to the "value" field.
func (u *SampleUpsert) AddValue(v float64) *SampleUpsert {
	u.Add(sample.FieldValue, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Sample.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SampleUpsertOne) UpdateNewValues() *SampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Sample.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SampleUpsertOne) Ignore() *SampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SampleUpsertOne) DoNothing() *SampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SampleCreate.OnConflict
// documentation for more info.
func (u *SampleUpsertOne) Update(set func(*SampleUpsert)) *SampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SampleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTs sets the "ts" field.
func (u *SampleUpsertOne) SetTs(v int64) *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *SampleUpsertOne) AddTs(v int64) *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *SampleUpsertOne) UpdateTs() *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateTs()
	})
}

// SetScope sets the "scope" field.
func (u *SampleUpsertOne) SetScope(v string) *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SampleUpsertOne) UpdateScope() *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateScope()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *SampleUpsertOne) SetScopeID(v string) *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SampleUpsertOne) UpdateScopeID() *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateScopeID()
	})
}

// SetTier sets the "tier" field.
func (u *SampleUpsertOne) SetTier(v string) *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.SetTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *SampleUpsertOne) UpdateTier() *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateTier()
	})
}

// SetMetric sets the "metric" field.
func (u *SampleUpsertOne) SetMetric(v string) *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.SetMetric(v)
	})
}

// UpdateMetric sets the "metric" field to the value that was provided on create.
func (u *SampleUpsertOne) UpdateMetric() *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateMetric()
	})
}

// SetValue sets the "value" field.
func (u *SampleUpsertOne) SetValue(v float64) *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *SampleUpsertOne) AddValue(v float64) *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SampleUpsertOne) UpdateValue() *SampleUpsertOne {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *SampleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SampleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SampleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SampleUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SampleUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SampleCreateBulk is the builder for creating many Sample entities in bulk.
type SampleCreateBulk struct {
	config
	err      error
	builders []*SampleCreate
	conflict []sql.ConflictOption
}

// Save creates the Sample entities in the database.
func (_c *SampleCreateBulk) Save(ctx context.Context) ([]*Sample, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Sample, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SampleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SampleCreateBulk) SaveX(ctx context.Context) []*Sample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SampleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SampleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Sample.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SampleUpsert) {
//			SetTs(v+v).
//		}).
//		Exec(ctx)
func (_c *SampleCreateBulk) OnConflict(opts ...sql.ConflictOption) *SampleUpsertBulk {
	_c.conflict = opts
	return &SampleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Sample.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SampleCreateBulk) OnConflictColumns(columns ...string) *SampleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SampleUpsertBulk{
		create: _c,
	}
}

// SampleUpsertBulk is the builder for "upsert"-ing
// a bulk of Sample nodes.
type SampleUpsertBulk struct {
	create *SampleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Sample.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SampleUpsertBulk) UpdateNewValues() *SampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Sample.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SampleUpsertBulk) Ignore() *SampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SampleUpsertBulk) DoNothing() *SampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SampleCreateBulk.OnConflict
// documentation for more info.
func (u *SampleUpsertBulk) Update(set func(*SampleUpsert)) *SampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SampleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTs sets the "ts" field.
func (u *SampleUpsertBulk) SetTs(v int64) *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *SampleUpsertBulk) AddTs(v int64) *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *SampleUpsertBulk) UpdateTs() *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateTs()
	})
}

// SetScope sets the "scope" field.
func (u *SampleUpsertBulk) SetScope(v string) *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SampleUpsertBulk) UpdateScope() *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateScope()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *SampleUpsertBulk) SetScopeID(v string) *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SampleUpsertBulk) UpdateScopeID() *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateScopeID()
	})
}

// SetTier sets the "tier" field.
func (u *SampleUpsertBulk) SetTier(v string) *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.SetTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *SampleUpsertBulk) UpdateTier() *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateTier()
	})
}

// SetMetric sets the "metric" field.
func (u *SampleUpsertBulk) SetMetric(v string) *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.SetMetric(v)
	})
}

// UpdateMetric sets the "metric" field to the value that was provided on create.
func (u *SampleUpsertBulk) UpdateMetric() *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateMetric()
	})
}

// SetValue sets the "value" field.
func (u *SampleUpsertBulk) SetValue(v float64) *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *SampleUpsertBulk) AddValue(v float64) *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SampleUpsertBulk) UpdateValue() *SampleUpsertBulk {
	return u.Update(func(s *SampleUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *SampleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SampleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SampleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SampleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
