// Code generated by ent, DO NOT EDIT.

package runnerfailure

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the runnerfailure type in the database.
	Label = "runner_failure"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRunnerName holds the string denoting the runner_name field in the database.
	FieldRunnerName = "runner_name"
	// FieldSetName holds the string denoting the set_name field in the database.
	FieldSetName = "set_name"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldSevere holds the string denoting the severe field in the database.
	FieldSevere = "severe"
	// FieldTs holds the string denoting the ts field in the database.
	FieldTs = "ts"
	// Table holds the table name of the runnerfailure in the database.
	Table = "runner_failures"
)

// Columns holds all SQL columns for runnerfailure fields.
var Columns = []string{
	FieldID,
	FieldRunnerName,
	FieldSetName,
	FieldReason,
	FieldSevere,
	FieldTs,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSetName holds the default value on creation for the "set_name" field.
	DefaultSetName string
	// DefaultSevere holds the default value on creation for the "severe" field.
	DefaultSevere bool
)

// OrderOption defines the ordering options for the RunnerFailure queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunnerName orders the results by the runner_name field.
func ByRunnerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunnerName, opts...).ToFunc()
}

// BySetName orders the results by the set_name field.
func BySetName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSetName, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// BySevere orders the results by the severe field.
func BySevere(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSevere, opts...).ToFunc()
}

// ByTs orders the results by the ts field.
func ByTs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTs, opts...).ToFunc()
}
