// Code generated by ent, DO NOT EDIT.

package sample

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sample type in the database.
	Label = "sample"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTs holds the string denoting the ts field in the database.
	FieldTs = "ts"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldScopeID holds the string denoting the scope_id field in the database.
	FieldScopeID = "scope_id"
	// FieldTier holds the string denoting the tier field in the database.
	FieldTier = "tier"
	// FieldMetric holds the string denoting the metric field in the database.
	FieldMetric = "metric"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// Table holds the table name of the sample in the database.
	Table = "samples"
)

// Columns holds all SQL columns for sample fields.
var Columns = []string{
	FieldID,
	FieldTs,
	FieldScope,
	FieldScopeID,
	FieldTier,
	FieldMetric,
	FieldValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultScopeID holds the default value on creation for the "scope_id" field.
	DefaultScopeID string
)

// OrderOption defines the ordering options for the Sample queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTs orders the results by the ts field.
func ByTs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTs, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByScopeID orders the results by the scope_id field.
func ByScopeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeID, opts...).ToFunc()
}

// ByTier orders the results by the tier field.
func ByTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTier, opts...).ToFunc()
}

// ByMetric orders the results by the metric field.
func ByMetric(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetric, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}
