// Code generated by ent, DO NOT EDIT.

package sample

import (
	"arc-ui/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Sample {
	return predicate.Sample(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Sample {
	return predicate.Sample(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Sample {
	return predicate.Sample(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Sample {
	return predicate.Sample(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Sample {
	return predicate.Sample(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Sample {
	return predicate.Sample(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Sample {
	return predicate.Sample(sql.FieldLTE(FieldID, id))
}

// Ts applies equality check predicate on the "ts" field. It's identical to TsEQ.
func Ts(v int64) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldTs, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldScope, v))
}

// ScopeID applies equality check predicate on the "scope_id" field. It's identical to ScopeIDEQ.
func ScopeID(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldScopeID, v))
}

// Tier applies equality check predicate on the "tier" field. It's identical to TierEQ.
func Tier(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldTier, v))
}

// Metric applies equality check predicate on the "metric" field. It's identical to MetricEQ.
func Metric(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldMetric, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v float64) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldValue, v))
}

// TsEQ applies the EQ predicate on the "ts" field.
func TsEQ(v int64) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldTs, v))
}

// TsNEQ applies the NEQ predicate on the "ts" field.
func TsNEQ(v int64) predicate.Sample {
	return predicate.Sample(sql.FieldNEQ(FieldTs, v))
}

// TsIn applies the In predicate on the "ts" field.
func TsIn(vs ...int64) predicate.Sample {
	return predicate.Sample(sql.FieldIn(FieldTs, vs...))
}

// TsNotIn applies the NotIn predicate on the "ts" field.
func TsNotIn(vs ...int64) predicate.Sample {
	return predicate.Sample(sql.FieldNotIn(FieldTs, vs...))
}

// TsGT applies the GT predicate on the "ts" field.
func TsGT(v int64) predicate.Sample {
	return predicate.Sample(sql.FieldGT(FieldTs, v))
}

// TsGTE applies the GTE predicate on the "ts" field.
func TsGTE(v int64) predicate.Sample {
	return predicate.Sample(sql.FieldGTE(FieldTs, v))
}

// TsLT applies the LT predicate on the "ts" field.
func TsLT(v int64) predicate.Sample {
	return predicate.Sample(sql.FieldLT(FieldTs, v))
}

// TsLTE applies the LTE predicate on the "ts" field.
func TsLTE(v int64) predicate.Sample {
	return predicate.Sample(sql.FieldLTE(FieldTs, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.Sample {
	return predicate.Sample(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.Sample {
	return predicate.Sample(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.Sample {
	return predicate.Sample(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.Sample {
	return predicate.Sample(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.Sample {
	return predicate.Sample(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.Sample {
	return predicate.Sample(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.Sample {
	return predicate.Sample(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.Sample {
	return predicate.Sample(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.Sample {
	return predicate.Sample(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.Sample {
	return predicate.Sample(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.Sample {
	return predicate.Sample(sql.FieldContainsFold(FieldScope, v))
}

// ScopeIDEQ applies the EQ predicate on the "scope_id" field.
func ScopeIDEQ(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldScopeID, v))
}

// ScopeIDNEQ applies the NEQ predicate on the "scope_id" field.
func ScopeIDNEQ(v string) predicate.Sample {
	return predicate.Sample(sql.FieldNEQ(FieldScopeID, v))
}

// ScopeIDIn applies the In predicate on the "scope_id" field.
func ScopeIDIn(vs ...string) predicate.Sample {
	return predicate.Sample(sql.FieldIn(FieldScopeID, vs...))
}

// ScopeIDNotIn applies the NotIn predicate on the "scope_id" field.
func ScopeIDNotIn(vs ...string) predicate.Sample {
	return predicate.Sample(sql.FieldNotIn(FieldScopeID, vs...))
}

// ScopeIDGT applies the GT predicate on the "scope_id" field.
func ScopeIDGT(v string) predicate.Sample {
	return predicate.Sample(sql.FieldGT(FieldScopeID, v))
}

// ScopeIDGTE applies the GTE predicate on the "scope_id" field.
func ScopeIDGTE(v string) predicate.Sample {
	return predicate.Sample(sql.FieldGTE(FieldScopeID, v))
}

// ScopeIDLT applies the LT predicate on the "scope_id" field.
func ScopeIDLT(v string) predicate.Sample {
	return predicate.Sample(sql.FieldLT(FieldScopeID, v))
}

// ScopeIDLTE applies the LTE predicate on the "scope_id" field.
func ScopeIDLTE(v string) predicate.Sample {
	return predicate.Sample(sql.FieldLTE(FieldScopeID, v))
}

// ScopeIDContains applies the Contains predicate on the "scope_id" field.
func ScopeIDContains(v string) predicate.Sample {
	return predicate.Sample(sql.FieldContains(FieldScopeID, v))
}

// ScopeIDHasPrefix applies the HasPrefix predicate on the "scope_id" field.
func ScopeIDHasPrefix(v string) predicate.Sample {
	return predicate.Sample(sql.FieldHasPrefix(FieldScopeID, v))
}

// ScopeIDHasSuffix applies the HasSuffix predicate on the "scope_id" field.
func ScopeIDHasSuffix(v string) predicate.Sample {
	return predicate.Sample(sql.FieldHasSuffix(FieldScopeID, v))
}

// ScopeIDEqualFold applies the EqualFold predicate on the "scope_id" field.
func ScopeIDEqualFold(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEqualFold(FieldScopeID, v))
}

// ScopeIDContainsFold applies the ContainsFold predicate on the "scope_id" field.
func ScopeIDContainsFold(v string) predicate.Sample {
	return predicate.Sample(sql.FieldContainsFold(FieldScopeID, v))
}

// TierEQ applies the EQ predicate on the "tier" field.
func TierEQ(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldTier, v))
}

// TierNEQ applies the NEQ predicate on the "tier" field.
func TierNEQ(v string) predicate.Sample {
	return predicate.Sample(sql.FieldNEQ(FieldTier, v))
}

// TierIn applies the In predicate on the "tier" field.
func TierIn(vs ...string) predicate.Sample {
	return predicate.Sample(sql.FieldIn(FieldTier, vs...))
}

// TierNotIn applies the NotIn predicate on the "tier" field.
func TierNotIn(vs ...string) predicate.Sample {
	return predicate.Sample(sql.FieldNotIn(FieldTier, vs...))
}

// TierGT applies the GT predicate on the "tier" field.
func TierGT(v string) predicate.Sample {
	return predicate.Sample(sql.FieldGT(FieldTier, v))
}

// TierGTE applies the GTE predicate on the "tier" field.
func TierGTE(v string) predicate.Sample {
	return predicate.Sample(sql.FieldGTE(FieldTier, v))
}

// TierLT applies the LT predicate on the "tier" field.
func TierLT(v string) predicate.Sample {
	return predicate.Sample(sql.FieldLT(FieldTier, v))
}

// TierLTE applies the LTE predicate on the "tier" field.
func TierLTE(v string) predicate.Sample {
	return predicate.Sample(sql.FieldLTE(FieldTier, v))
}

// TierContains applies the Contains predicate on the "tier" field.
func TierContains(v string) predicate.Sample {
	return predicate.Sample(sql.FieldContains(FieldTier, v))
}

// TierHasPrefix applies the HasPrefix predicate on the "tier" field.
func TierHasPrefix(v string) predicate.Sample {
	return predicate.Sample(sql.FieldHasPrefix(FieldTier, v))
}

// TierHasSuffix applies the HasSuffix predicate on the "tier" field.
func TierHasSuffix(v string) predicate.Sample {
	return predicate.Sample(sql.FieldHasSuffix(FieldTier, v))
}

// TierEqualFold applies the EqualFold predicate on the "tier" field.
func TierEqualFold(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEqualFold(FieldTier, v))
}

// TierContainsFold applies the ContainsFold predicate on the "tier" field.
func TierContainsFold(v string) predicate.Sample {
	return predicate.Sample(sql.FieldContainsFold(FieldTier, v))
}

// MetricEQ applies the EQ predicate on the "metric" field.
func MetricEQ(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldMetric, v))
}

// MetricNEQ applies the NEQ predicate on the "metric" field.
func MetricNEQ(v string) predicate.Sample {
	return predicate.Sample(sql.FieldNEQ(FieldMetric, v))
}

// MetricIn applies the In predicate on the "metric" field.
func MetricIn(vs ...string) predicate.Sample {
	return predicate.Sample(sql.FieldIn(FieldMetric, vs...))
}

// MetricNotIn applies the NotIn predicate on the "metric" field.
func MetricNotIn(vs ...string) predicate.Sample {
	return predicate.Sample(sql.FieldNotIn(FieldMetric, vs...))
}

// MetricGT applies the GT predicate on the "metric" field.
func MetricGT(v string) predicate.Sample {
	return predicate.Sample(sql.FieldGT(FieldMetric, v))
}

// MetricGTE applies the GTE predicate on the "metric" field.
func MetricGTE(v string) predicate.Sample {
	return predicate.Sample(sql.FieldGTE(FieldMetric, v))
}

// MetricLT applies the LT predicate on the "metric" field.
func MetricLT(v string) predicate.Sample {
	return predicate.Sample(sql.FieldLT(FieldMetric, v))
}

// MetricLTE applies the LTE predicate on the "metric" field.
func MetricLTE(v string) predicate.Sample {
	return predicate.Sample(sql.FieldLTE(FieldMetric, v))
}

// MetricContains applies the Contains predicate on the "metric" field.
func MetricContains(v string) predicate.Sample {
	return predicate.Sample(sql.FieldContains(FieldMetric, v))
}

// MetricHasPrefix applies the HasPrefix predicate on the "metric" field.
func MetricHasPrefix(v string) predicate.Sample {
	return predicate.Sample(sql.FieldHasPrefix(FieldMetric, v))
}

// MetricHasSuffix applies the HasSuffix predicate on the "metric" field.
func MetricHasSuffix(v string) predicate.Sample {
	return predicate.Sample(sql.FieldHasSuffix(FieldMetric, v))
}

// MetricEqualFold applies the EqualFold predicate on the "metric" field.
func MetricEqualFold(v string) predicate.Sample {
	return predicate.Sample(sql.FieldEqualFold(FieldMetric, v))
}

// MetricContainsFold applies the ContainsFold predicate on the "metric" field.
func MetricContainsFold(v string) predicate.Sample {
	return predicate.Sample(sql.FieldContainsFold(FieldMetric, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v float64) predicate.Sample {
	return predicate.Sample(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v float64) predicate.Sample {
	return predicate.Sample(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...float64) predicate.Sample {
	return predicate.Sample(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...float64) predicate.Sample {
	return predicate.Sample(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v float64) predicate.Sample {
	return predicate.Sample(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v float64) predicate.Sample {
	return predicate.Sample(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v float64) predicate.Sample {
	return predicate.Sample(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v float64) predicate.Sample {
	return predicate.Sample(sql.FieldLTE(FieldValue, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sample) predicate.Sample {
	return predicate.Sample(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sample) predicate.Sample {
	return predicate.Sample(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sample) predicate.Sample {
	return predicate.Sample(sql.NotPredicates(p))
}
