// Code generated by ent, DO NOT EDIT.

package phasetransition

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the phasetransition type in the database.
	Label = "phase_transition"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRunnerName holds the string denoting the runner_name field in the database.
	FieldRunnerName = "runner_name"
	// FieldSetName holds the string denoting the set_name field in the database.
	FieldSetName = "set_name"
	// FieldPhase holds the string denoting the phase field in the database.
	FieldPhase = "phase"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// Table holds the table name of the phasetransition in the database.
	Table = "phase_transitions"
)

// Columns holds all SQL columns for phasetransition fields.
var Columns = []string{
	FieldID,
	FieldRunnerName,
	FieldSetName,
	FieldPhase,
	FieldStartedAt,
	FieldEndedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSetName holds the default value on creation for the "set_name" field.
	DefaultSetName string
	// DefaultEndedAt holds the default value on creation for the "ended_at" field.
	DefaultEndedAt int64
)

// OrderOption defines the ordering options for the PhaseTransition queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunnerName orders the results by the runner_name field.
func ByRunnerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunnerName, opts...).ToFunc()
}

// BySetName orders the results by the set_name field.
func BySetName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSetName, opts...).ToFunc()
}

// ByPhase orders the results by the phase field.
func ByPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhase, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}
