// Code generated by ent, DO NOT EDIT.

package phasetransition

import (
	"arc-ui/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLTE(FieldID, id))
}

// RunnerName applies equality check predicate on the "runner_name" field. It's identical to RunnerNameEQ.
func RunnerName(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldRunnerName, v))
}

// SetName applies equality check predicate on the "set_name" field. It's identical to SetNameEQ.
func SetName(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldSetName, v))
}

// Phase applies equality check predicate on the "phase" field. It's identical to PhaseEQ.
func Phase(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldPhase, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldEndedAt, v))
}

// RunnerNameEQ applies the EQ predicate on the "runner_name" field.
func RunnerNameEQ(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldRunnerName, v))
}

// RunnerNameNEQ applies the NEQ predicate on the "runner_name" field.
func RunnerNameNEQ(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldRunnerName, v))
}

// RunnerNameIn applies the In predicate on the "runner_name" field.
func RunnerNameIn(vs ...string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldRunnerName, vs...))
}

// RunnerNameNotIn applies the NotIn predicate on the "runner_name" field.
func RunnerNameNotIn(vs ...string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldRunnerName, vs...))
}

// RunnerNameGT applies the GT predicate on the "runner_name" field.
func RunnerNameGT(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGT(FieldRunnerName, v))
}

// RunnerNameGTE applies the GTE predicate on the "runner_name" field.
func RunnerNameGTE(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGTE(FieldRunnerName, v))
}

// RunnerNameLT applies the LT predicate on the "runner_name" field.
func RunnerNameLT(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLT(FieldRunnerName, v))
}

// RunnerNameLTE applies the LTE predicate on the "runner_name" field.
func RunnerNameLTE(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLTE(FieldRunnerName, v))
}

// RunnerNameContains applies the Contains predicate on the "runner_name" field.
func RunnerNameContains(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldContains(FieldRunnerName, v))
}

// RunnerNameHasPrefix applies the HasPrefix predicate on the "runner_name" field.
func RunnerNameHasPrefix(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldHasPrefix(FieldRunnerName, v))
}

// RunnerNameHasSuffix applies the HasSuffix predicate on the "runner_name" field.
func RunnerNameHasSuffix(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldHasSuffix(FieldRunnerName, v))
}

// RunnerNameEqualFold applies the EqualFold predicate on the "runner_name" field.
func RunnerNameEqualFold(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEqualFold(FieldRunnerName, v))
}

// RunnerNameContainsFold applies the ContainsFold predicate on the "runner_name" field.
func RunnerNameContainsFold(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldContainsFold(FieldRunnerName, v))
}

// SetNameEQ applies the EQ predicate on the "set_name" field.
func SetNameEQ(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldSetName, v))
}

// SetNameNEQ applies the NEQ predicate on the "set_name" field.
func SetNameNEQ(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldSetName, v))
}

// SetNameIn applies the In predicate on the "set_name" field.
func SetNameIn(vs ...string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldSetName, vs...))
}

// SetNameNotIn applies the NotIn predicate on the "set_name" field.
func SetNameNotIn(vs ...string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldSetName, vs...))
}

// SetNameGT applies the GT predicate on the "set_name" field.
func SetNameGT(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGT(FieldSetName, v))
}

// SetNameGTE applies the GTE predicate on the "set_name" field.
func SetNameGTE(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGTE(FieldSetName, v))
}

// SetNameLT applies the LT predicate on the "set_name" field.
func SetNameLT(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLT(FieldSetName, v))
}

// SetNameLTE applies the LTE predicate on the "set_name" field.
func SetNameLTE(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLTE(FieldSetName, v))
}

// SetNameContains applies the Contains predicate on the "set_name" field.
func SetNameContains(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldContains(FieldSetName, v))
}

// SetNameHasPrefix applies the HasPrefix predicate on the "set_name" field.
func SetNameHasPrefix(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldHasPrefix(FieldSetName, v))
}

// SetNameHasSuffix applies the HasSuffix predicate on the "set_name" field.
func SetNameHasSuffix(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldHasSuffix(FieldSetName, v))
}

// SetNameEqualFold applies the EqualFold predicate on the "set_name" field.
func SetNameEqualFold(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEqualFold(FieldSetName, v))
}

// SetNameContainsFold applies the ContainsFold predicate on the "set_name" field.
func SetNameContainsFold(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldContainsFold(FieldSetName, v))
}

// PhaseEQ applies the EQ predicate on the "phase" field.
func PhaseEQ(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldPhase, v))
}

// PhaseNEQ applies the NEQ predicate on the "phase" field.
func PhaseNEQ(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldPhase, v))
}

// PhaseIn applies the In predicate on the "phase" field.
func PhaseIn(vs ...string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldPhase, vs...))
}

// PhaseNotIn applies the NotIn predicate on the "phase" field.
func PhaseNotIn(vs ...string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldPhase, vs...))
}

// PhaseGT applies the GT predicate on the "phase" field.
func PhaseGT(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGT(FieldPhase, v))
}

// PhaseGTE applies the GTE predicate on the "phase" field.
func PhaseGTE(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGTE(FieldPhase, v))
}

// PhaseLT applies the LT predicate on the "phase" field.
func PhaseLT(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLT(FieldPhase, v))
}

// PhaseLTE applies the LTE predicate on the "phase" field.
func PhaseLTE(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLTE(FieldPhase, v))
}

// PhaseContains applies the Contains predicate on the "phase" field.
func PhaseContains(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldContains(FieldPhase, v))
}

// PhaseHasPrefix applies the HasPrefix predicate on the "phase" field.
func PhaseHasPrefix(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldHasPrefix(FieldPhase, v))
}

// PhaseHasSuffix applies the HasSuffix predicate on the "phase" field.
func PhaseHasSuffix(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldHasSuffix(FieldPhase, v))
}

// PhaseEqualFold applies the EqualFold predicate on the "phase" field.
func PhaseEqualFold(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEqualFold(FieldPhase, v))
}

// PhaseContainsFold applies the ContainsFold predicate on the "phase" field.
func PhaseContainsFold(v string) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldContainsFold(FieldPhase, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v int64) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLTE(FieldEndedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PhaseTransition) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PhaseTransition) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PhaseTransition) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.NotPredicates(p))
}
