// Code generated by ent, DO NOT EDIT.

package churnevent

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the churnevent type in the database.
	Label = "churn_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRunnerName holds the string denoting the runner_name field in the database.
	FieldRunnerName = "runner_name"
	// FieldSetName holds the string denoting the set_name field in the database.
	FieldSetName = "set_name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldTs holds the string denoting the ts field in the database.
	FieldTs = "ts"
	// Table holds the table name of the churnevent in the database.
	Table = "churn_events"
)

// Columns holds all SQL columns for churnevent fields.
var Columns = []string{
	FieldID,
	FieldRunnerName,
	FieldSetName,
	FieldKind,
	FieldTs,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSetName holds the default value on creation for the "set_name" field.
	DefaultSetName string
)

// OrderOption defines the ordering options for the ChurnEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunnerName orders the results by the runner_name field.
func ByRunnerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunnerName, opts...).ToFunc()
}

// BySetName orders the results by the set_name field.
func BySetName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSetName, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByTs orders the results by the ts field.
func ByTs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTs, opts...).ToFunc()
}
