// Code generated by ent, DO NOT EDIT.

package churnevent

import (
	"arc-ui/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldLTE(FieldID, id))
}

// RunnerName applies equality check predicate on the "runner_name" field. It's identical to RunnerNameEQ.
func RunnerName(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEQ(FieldRunnerName, v))
}

// SetName applies equality check predicate on the "set_name" field. It's identical to SetNameEQ.
func SetName(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEQ(FieldSetName, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEQ(FieldKind, v))
}

// Ts applies equality check predicate on the "ts" field. It's identical to TsEQ.
func Ts(v int64) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEQ(FieldTs, v))
}

// RunnerNameEQ applies the EQ predicate on the "runner_name" field.
func RunnerNameEQ(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEQ(FieldRunnerName, v))
}

// RunnerNameNEQ applies the NEQ predicate on the "runner_name" field.
func RunnerNameNEQ(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldNEQ(FieldRunnerName, v))
}

// RunnerNameIn applies the In predicate on the "runner_name" field.
func RunnerNameIn(vs ...string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldIn(FieldRunnerName, vs...))
}

// RunnerNameNotIn applies the NotIn predicate on the "runner_name" field.
func RunnerNameNotIn(vs ...string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldNotIn(FieldRunnerName, vs...))
}

// RunnerNameGT applies the GT predicate on the "runner_name" field.
func RunnerNameGT(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldGT(FieldRunnerName, v))
}

// RunnerNameGTE applies the GTE predicate on the "runner_name" field.
func RunnerNameGTE(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldGTE(FieldRunnerName, v))
}

// RunnerNameLT applies the LT predicate on the "runner_name" field.
func RunnerNameLT(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldLT(FieldRunnerName, v))
}

// RunnerNameLTE applies the LTE predicate on the "runner_name" field.
func RunnerNameLTE(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldLTE(FieldRunnerName, v))
}

// RunnerNameContains applies the Contains predicate on the "runner_name" field.
func RunnerNameContains(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldContains(FieldRunnerName, v))
}

// RunnerNameHasPrefix applies the HasPrefix predicate on the "runner_name" field.
func RunnerNameHasPrefix(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldHasPrefix(FieldRunnerName, v))
}

// RunnerNameHasSuffix applies the HasSuffix predicate on the "runner_name" field.
func RunnerNameHasSuffix(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldHasSuffix(FieldRunnerName, v))
}

// RunnerNameEqualFold applies the EqualFold predicate on the "runner_name" field.
func RunnerNameEqualFold(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEqualFold(FieldRunnerName, v))
}

// RunnerNameContainsFold applies the ContainsFold predicate on the "runner_name" field.
func RunnerNameContainsFold(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldContainsFold(FieldRunnerName, v))
}

// SetNameEQ applies the EQ predicate on the "set_name" field.
func SetNameEQ(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEQ(FieldSetName, v))
}

// SetNameNEQ applies the NEQ predicate on the "set_name" field.
func SetNameNEQ(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldNEQ(FieldSetName, v))
}

// SetNameIn applies the In predicate on the "set_name" field.
func SetNameIn(vs ...string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldIn(FieldSetName, vs...))
}

// SetNameNotIn applies the NotIn predicate on the "set_name" field.
func SetNameNotIn(vs ...string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldNotIn(FieldSetName, vs...))
}

// SetNameGT applies the GT predicate on the "set_name" field.
func SetNameGT(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldGT(FieldSetName, v))
}

// SetNameGTE applies the GTE predicate on the "set_name" field.
func SetNameGTE(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldGTE(FieldSetName, v))
}

// SetNameLT applies the LT predicate on the "set_name" field.
func SetNameLT(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldLT(FieldSetName, v))
}

// SetNameLTE applies the LTE predicate on the "set_name" field.
func SetNameLTE(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldLTE(FieldSetName, v))
}

// SetNameContains applies the Contains predicate on the "set_name" field.
func SetNameContains(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldContains(FieldSetName, v))
}

// SetNameHasPrefix applies the HasPrefix predicate on the "set_name" field.
func SetNameHasPrefix(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldHasPrefix(FieldSetName, v))
}

// SetNameHasSuffix applies the HasSuffix predicate on the "set_name" field.
func SetNameHasSuffix(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldHasSuffix(FieldSetName, v))
}

// SetNameEqualFold applies the EqualFold predicate on the "set_name" field.
func SetNameEqualFold(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEqualFold(FieldSetName, v))
}

// SetNameContainsFold applies the ContainsFold predicate on the "set_name" field.
func SetNameContainsFold(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldContainsFold(FieldSetName, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldContainsFold(FieldKind, v))
}

// TsEQ applies the EQ predicate on the "ts" field.
func TsEQ(v int64) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldEQ(FieldTs, v))
}

// TsNEQ applies the NEQ predicate on the "ts" field.
func TsNEQ(v int64) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldNEQ(FieldTs, v))
}

// TsIn applies the In predicate on the "ts" field.
func TsIn(vs ...int64) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldIn(FieldTs, vs...))
}

// TsNotIn applies the NotIn predicate on the "ts" field.
func TsNotIn(vs ...int64) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldNotIn(FieldTs, vs...))
}

// TsGT applies the GT predicate on the "ts" field.
func TsGT(v int64) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldGT(FieldTs, v))
}

// TsGTE applies the GTE predicate on the "ts" field.
func TsGTE(v int64) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldGTE(FieldTs, v))
}

// TsLT applies the LT predicate on the "ts" field.
func TsLT(v int64) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldLT(FieldTs, v))
}

// TsLTE applies the LTE predicate on the "ts" field.
func TsLTE(v int64) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.FieldLTE(FieldTs, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChurnEvent) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChurnEvent) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChurnEvent) predicate.ChurnEvent {
	return predicate.ChurnEvent(sql.NotPredicates(p))
}
