// Code generated by ent, DO NOT EDIT.

package jobobservation

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the jobobservation type in the database.
	Label = "job_observation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRunnerName holds the string denoting the runner_name field in the database.
	FieldRunnerName = "runner_name"
	// FieldSetName holds the string denoting the set_name field in the database.
	FieldSetName = "set_name"
	// FieldRepository holds the string denoting the repository field in the database.
	FieldRepository = "repository"
	// FieldWorkflow holds the string denoting the workflow field in the database.
	FieldWorkflow = "workflow"
	// FieldJobName holds the string denoting the job_name field in the database.
	FieldJobName = "job_name"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldSucceeded holds the string denoting the succeeded field in the database.
	FieldSucceeded = "succeeded"
	// FieldCPUSeconds holds the string denoting the cpu_seconds field in the database.
	FieldCPUSeconds = "cpu_seconds"
	// FieldMemByteSeconds holds the string denoting the mem_byte_seconds field in the database.
	FieldMemByteSeconds = "mem_byte_seconds"
	// FieldCPURequest holds the string denoting the cpu_request field in the database.
	FieldCPURequest = "cpu_request"
	// FieldCPULimit holds the string denoting the cpu_limit field in the database.
	FieldCPULimit = "cpu_limit"
	// FieldMemRequest holds the string denoting the mem_request field in the database.
	FieldMemRequest = "mem_request"
	// FieldMemLimit holds the string denoting the mem_limit field in the database.
	FieldMemLimit = "mem_limit"
	// Table holds the table name of the jobobservation in the database.
	Table = "job_observations"
)

// Columns holds all SQL columns for jobobservation fields.
var Columns = []string{
	FieldID,
	FieldRunnerName,
	FieldSetName,
	FieldRepository,
	FieldWorkflow,
	FieldJobName,
	FieldRunID,
	FieldStartedAt,
	FieldFinishedAt,
	FieldSucceeded,
	FieldCPUSeconds,
	FieldMemByteSeconds,
	FieldCPURequest,
	FieldCPULimit,
	FieldMemRequest,
	FieldMemLimit,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSetName holds the default value on creation for the "set_name" field.
	DefaultSetName string
	// DefaultRepository holds the default value on creation for the "repository" field.
	DefaultRepository string
	// DefaultWorkflow holds the default value on creation for the "workflow" field.
	DefaultWorkflow string
	// DefaultJobName holds the default value on creation for the "job_name" field.
	DefaultJobName string
	// DefaultRunID holds the default value on creation for the "run_id" field.
	DefaultRunID int64
	// DefaultFinishedAt holds the default value on creation for the "finished_at" field.
	DefaultFinishedAt int64
	// DefaultSucceeded holds the default value on creation for the "succeeded" field.
	DefaultSucceeded bool
	// DefaultCPUSeconds holds the default value on creation for the "cpu_seconds" field.
	DefaultCPUSeconds float64
	// DefaultMemByteSeconds holds the default value on creation for the "mem_byte_seconds" field.
	DefaultMemByteSeconds float64
	// DefaultCPURequest holds the default value on creation for the "cpu_request" field.
	DefaultCPURequest float64
	// DefaultCPULimit holds the default value on creation for the "cpu_limit" field.
	DefaultCPULimit float64
	// DefaultMemRequest holds the default value on creation for the "mem_request" field.
	DefaultMemRequest float64
	// DefaultMemLimit holds the default value on creation for the "mem_limit" field.
	DefaultMemLimit float64
)

// OrderOption defines the ordering options for the JobObservation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunnerName orders the results by the runner_name field.
func ByRunnerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunnerName, opts...).ToFunc()
}

// BySetName orders the results by the set_name field.
func BySetName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSetName, opts...).ToFunc()
}

// ByRepository orders the results by the repository field.
func ByRepository(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepository, opts...).ToFunc()
}

// ByWorkflow orders the results by the workflow field.
func ByWorkflow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflow, opts...).ToFunc()
}

// ByJobName orders the results by the job_name field.
func ByJobName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobName, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// BySucceeded orders the results by the succeeded field.
func BySucceeded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSucceeded, opts...).ToFunc()
}

// ByCPUSeconds orders the results by the cpu_seconds field.
func ByCPUSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCPUSeconds, opts...).ToFunc()
}

// ByMemByteSeconds orders the results by the mem_byte_seconds field.
func ByMemByteSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemByteSeconds, opts...).ToFunc()
}

// ByCPURequest orders the results by the cpu_request field.
func ByCPURequest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCPURequest, opts...).ToFunc()
}

// ByCPULimit orders the results by the cpu_limit field.
func ByCPULimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCPULimit, opts...).ToFunc()
}

// ByMemRequest orders the results by the mem_request field.
func ByMemRequest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemRequest, opts...).ToFunc()
}

// ByMemLimit orders the results by the mem_limit field.
func ByMemLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemLimit, opts...).ToFunc()
}
