// Code generated by ent, DO NOT EDIT.

package jobsample

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the jobsample type in the database.
	Label = "job_sample"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldTs holds the string denoting the ts field in the database.
	FieldTs = "ts"
	// FieldCPUCores holds the string denoting the cpu_cores field in the database.
	FieldCPUCores = "cpu_cores"
	// FieldMemBytes holds the string denoting the mem_bytes field in the database.
	FieldMemBytes = "mem_bytes"
	// FieldSamples holds the string denoting the samples field in the database.
	FieldSamples = "samples"
	// Table holds the table name of the jobsample in the database.
	Table = "job_samples"
)

// Columns holds all SQL columns for jobsample fields.
var Columns = []string{
	FieldID,
	FieldJobID,
	FieldTs,
	FieldCPUCores,
	FieldMemBytes,
	FieldSamples,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCPUCores holds the default value on creation for the "cpu_cores" field.
	DefaultCPUCores float64
	// DefaultMemBytes holds the default value on creation for the "mem_bytes" field.
	DefaultMemBytes float64
	// DefaultSamples holds the default value on creation for the "samples" field.
	DefaultSamples int
)

// OrderOption defines the ordering options for the JobSample queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJobID orders the results by the job_id field.
func ByJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobID, opts...).ToFunc()
}

// ByTs orders the results by the ts field.
func ByTs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTs, opts...).ToFunc()
}

// ByCPUCores orders the results by the cpu_cores field.
func ByCPUCores(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCPUCores, opts...).ToFunc()
}

// ByMemBytes orders the results by the mem_bytes field.
func ByMemBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemBytes, opts...).ToFunc()
}

// BySamples orders the results by the samples field.
func BySamples(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSamples, opts...).ToFunc()
}
