// Code generated by ent, DO NOT EDIT.

package jobsample

import (
	"arc-ui/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.JobSample {
	return predicate.JobSample(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.JobSample {
	return predicate.JobSample(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.JobSample {
	return predicate.JobSample(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.JobSample {
	return predicate.JobSample(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.JobSample {
	return predicate.JobSample(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.JobSample {
	return predicate.JobSample(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.JobSample {
	return predicate.JobSample(sql.FieldLTE(FieldID, id))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldJobID, v))
}

// Ts applies equality check predicate on the "ts" field. It's identical to TsEQ.
func Ts(v int64) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldTs, v))
}

// CPUCores applies equality check predicate on the "cpu_cores" field. It's identical to CPUCoresEQ.
func CPUCores(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldCPUCores, v))
}

// MemBytes applies equality check predicate on the "mem_bytes" field. It's identical to MemBytesEQ.
func MemBytes(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldMemBytes, v))
}

// Samples applies equality check predicate on the "samples" field. It's identical to SamplesEQ.
func Samples(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldSamples, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...int) predicate.JobSample {
	return predicate.JobSample(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...int) predicate.JobSample {
	return predicate.JobSample(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldLTE(FieldJobID, v))
}

// TsEQ applies the EQ predicate on the "ts" field.
func TsEQ(v int64) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldTs, v))
}

// TsNEQ applies the NEQ predicate on the "ts" field.
func TsNEQ(v int64) predicate.JobSample {
	return predicate.JobSample(sql.FieldNEQ(FieldTs, v))
}

// TsIn applies the In predicate on the "ts" field.
func TsIn(vs ...int64) predicate.JobSample {
	return predicate.JobSample(sql.FieldIn(FieldTs, vs...))
}

// TsNotIn applies the NotIn predicate on the "ts" field.
func TsNotIn(vs ...int64) predicate.JobSample {
	return predicate.JobSample(sql.FieldNotIn(FieldTs, vs...))
}

// TsGT applies the GT predicate on the "ts" field.
func TsGT(v int64) predicate.JobSample {
	return predicate.JobSample(sql.FieldGT(FieldTs, v))
}

// TsGTE applies the GTE predicate on the "ts" field.
func TsGTE(v int64) predicate.JobSample {
	return predicate.JobSample(sql.FieldGTE(FieldTs, v))
}

// TsLT applies the LT predicate on the "ts" field.
func TsLT(v int64) predicate.JobSample {
	return predicate.JobSample(sql.FieldLT(FieldTs, v))
}

// TsLTE applies the LTE predicate on the "ts" field.
func TsLTE(v int64) predicate.JobSample {
	return predicate.JobSample(sql.FieldLTE(FieldTs, v))
}

// CPUCoresEQ applies the EQ predicate on the "cpu_cores" field.
func CPUCoresEQ(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldCPUCores, v))
}

// CPUCoresNEQ applies the NEQ predicate on the "cpu_cores" field.
func CPUCoresNEQ(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldNEQ(FieldCPUCores, v))
}

// CPUCoresIn applies the In predicate on the "cpu_cores" field.
func CPUCoresIn(vs ...float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldIn(FieldCPUCores, vs...))
}

// CPUCoresNotIn applies the NotIn predicate on the "cpu_cores" field.
func CPUCoresNotIn(vs ...float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldNotIn(FieldCPUCores, vs...))
}

// CPUCoresGT applies the GT predicate on the "cpu_cores" field.
func CPUCoresGT(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldGT(FieldCPUCores, v))
}

// CPUCoresGTE applies the GTE predicate on the "cpu_cores" field.
func CPUCoresGTE(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldGTE(FieldCPUCores, v))
}

// CPUCoresLT applies the LT predicate on the "cpu_cores" field.
func CPUCoresLT(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldLT(FieldCPUCores, v))
}

// CPUCoresLTE applies the LTE predicate on the "cpu_cores" field.
func CPUCoresLTE(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldLTE(FieldCPUCores, v))
}

// MemBytesEQ applies the EQ predicate on the "mem_bytes" field.
func MemBytesEQ(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldMemBytes, v))
}

// MemBytesNEQ applies the NEQ predicate on the "mem_bytes" field.
func MemBytesNEQ(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldNEQ(FieldMemBytes, v))
}

// MemBytesIn applies the In predicate on the "mem_bytes" field.
func MemBytesIn(vs ...float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldIn(FieldMemBytes, vs...))
}

// MemBytesNotIn applies the NotIn predicate on the "mem_bytes" field.
func MemBytesNotIn(vs ...float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldNotIn(FieldMemBytes, vs...))
}

// MemBytesGT applies the GT predicate on the "mem_bytes" field.
func MemBytesGT(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldGT(FieldMemBytes, v))
}

// MemBytesGTE applies the GTE predicate on the "mem_bytes" field.
func MemBytesGTE(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldGTE(FieldMemBytes, v))
}

// MemBytesLT applies the LT predicate on the "mem_bytes" field.
func MemBytesLT(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldLT(FieldMemBytes, v))
}

// MemBytesLTE applies the LTE predicate on the "mem_bytes" field.
func MemBytesLTE(v float64) predicate.JobSample {
	return predicate.JobSample(sql.FieldLTE(FieldMemBytes, v))
}

// SamplesEQ applies the EQ predicate on the "samples" field.
func SamplesEQ(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldEQ(FieldSamples, v))
}

// SamplesNEQ applies the NEQ predicate on the "samples" field.
func SamplesNEQ(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldNEQ(FieldSamples, v))
}

// SamplesIn applies the In predicate on the "samples" field.
func SamplesIn(vs ...int) predicate.JobSample {
	return predicate.JobSample(sql.FieldIn(FieldSamples, vs...))
}

// SamplesNotIn applies the NotIn predicate on the "samples" field.
func SamplesNotIn(vs ...int) predicate.JobSample {
	return predicate.JobSample(sql.FieldNotIn(FieldSamples, vs...))
}

// SamplesGT applies the GT predicate on the "samples" field.
func SamplesGT(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldGT(FieldSamples, v))
}

// SamplesGTE applies the GTE predicate on the "samples" field.
func SamplesGTE(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldGTE(FieldSamples, v))
}

// SamplesLT applies the LT predicate on the "samples" field.
func SamplesLT(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldLT(FieldSamples, v))
}

// SamplesLTE applies the LTE predicate on the "samples" field.
func SamplesLTE(v int) predicate.JobSample {
	return predicate.JobSample(sql.FieldLTE(FieldSamples, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.JobSample) predicate.JobSample {
	return predicate.JobSample(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.JobSample) predicate.JobSample {
	return predicate.JobSample(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.JobSample) predicate.JobSample {
	return predicate.JobSample(sql.NotPredicates(p))
}
